namespace Spa_Management_System
{
    partial class Consumable : Form
    {
        /// <summary>
        ///  Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        ///  Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        ///  Required method for Designer support - do not modify
        ///  the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Consumable));
            Bunifu.UI.WinForms.BunifuButton.BunifuIconButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuIconButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            DataGridViewCellStyle dataGridViewCellStyle1 = new DataGridViewCellStyle();
            DataGridViewCellStyle dataGridViewCellStyle2 = new DataGridViewCellStyle();
            DataGridViewCellStyle dataGridViewCellStyle3 = new DataGridViewCellStyle();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties25 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties26 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties27 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties28 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties29 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties30 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties31 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties32 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            bunifuPanel2 = new Bunifu.UI.WinForms.BunifuPanel();
            label11 = new Label();
            btnExitProgram = new Bunifu.UI.WinForms.BunifuButton.BunifuIconButton();
            txtSearch = new Bunifu.UI.WinForms.BunifuTextBox();
            btnClear = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            btnDelete = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            btnUpdate = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            btnInsert = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            btnNew = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            dgvConsumable = new Bunifu.UI.WinForms.BunifuDataGridView();
            txtID = new Bunifu.UI.WinForms.BunifuTextBox();
            label1 = new Label();
            cboCategory = new Bunifu.UI.WinForms.BunifuDropdown();
            label4 = new Label();
            txtName = new Bunifu.UI.WinForms.BunifuTextBox();
            label2 = new Label();
            txtPrice = new Bunifu.UI.WinForms.BunifuTextBox();
            label3 = new Label();
            txtQuantity = new Bunifu.UI.WinForms.BunifuTextBox();
            label5 = new Label();
            txtDescription = new Bunifu.UI.WinForms.BunifuTextBox();
            label6 = new Label();
            txtCreatedAt = new Bunifu.UI.WinForms.BunifuTextBox();
            label7 = new Label();
            txtModifiedAt = new Bunifu.UI.WinForms.BunifuTextBox();
            label8 = new Label();
            btnSelectPicture = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            picConsumable = new PictureBox();
            bunifuFormDock1 = new Bunifu.UI.WinForms.BunifuFormDock();
            bunifuPanel2.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)dgvConsumable).BeginInit();
            ((System.ComponentModel.ISupportInitialize)picConsumable).BeginInit();
            SuspendLayout();
            // 
            // bunifuPanel2
            // 
            bunifuPanel2.BackgroundColor = Color.White;
            bunifuPanel2.BackgroundImage = (Image)resources.GetObject("bunifuPanel2.BackgroundImage");
            bunifuPanel2.BackgroundImageLayout = ImageLayout.Stretch;
            bunifuPanel2.BorderColor = Color.Transparent;
            bunifuPanel2.BorderRadius = 3;
            bunifuPanel2.BorderThickness = 1;
            bunifuPanel2.Controls.Add(label11);
            bunifuPanel2.Controls.Add(btnExitProgram);
            bunifuPanel2.Dock = DockStyle.Top;
            bunifuPanel2.Location = new Point(0, 0);
            bunifuPanel2.Name = "bunifuPanel2";
            bunifuPanel2.ShowBorders = true;
            bunifuPanel2.Size = new Size(1176, 65);
            bunifuPanel2.TabIndex = 91;
            // 
            // label11
            // 
            label11.AutoSize = true;
            label11.BackColor = Color.Transparent;
            label11.Font = new Font("Microsoft Sans Serif", 14.25F, FontStyle.Bold, GraphicsUnit.Point, 0);
            label11.Location = new Point(474, 15);
            label11.Name = "label11";
            label11.Size = new Size(254, 24);
            label11.TabIndex = 74;
            label11.Text = "Consumable Management";
            // 
            // btnExitProgram
            // 
            btnExitProgram.AllowAnimations = true;
            btnExitProgram.AllowBorderColorChanges = true;
            btnExitProgram.AllowMouseEffects = true;
            btnExitProgram.AnimationSpeed = 200;
            btnExitProgram.BackColor = Color.Transparent;
            btnExitProgram.BackgroundColor = Color.Transparent;
            btnExitProgram.BorderColor = Color.Transparent;
            btnExitProgram.BorderRadius = 1;
            btnExitProgram.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuIconButton.BorderStyles.Solid;
            btnExitProgram.BorderThickness = 1;
            btnExitProgram.ColorContrastOnClick = 30;
            btnExitProgram.ColorContrastOnHover = -30;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            btnExitProgram.CustomizableEdges = borderEdges1;
            btnExitProgram.DialogResult = DialogResult.None;
            btnExitProgram.Image = (Image)resources.GetObject("btnExitProgram.Image");
            btnExitProgram.ImageMargin = new Padding(0);
            btnExitProgram.Location = new Point(1126, 15);
            btnExitProgram.Name = "btnExitProgram";
            btnExitProgram.RoundBorders = true;
            btnExitProgram.ShowBorders = true;
            btnExitProgram.Size = new Size(26, 26);
            btnExitProgram.Style = Bunifu.UI.WinForms.BunifuButton.BunifuIconButton.ButtonStyles.Round;
            btnExitProgram.TabIndex = 69;
            btnExitProgram.Click += btnExitProgram_Click;
            // 
            // txtSearch
            // 
            txtSearch.AcceptsReturn = false;
            txtSearch.AcceptsTab = false;
            txtSearch.AnimationSpeed = 200;
            txtSearch.AutoCompleteMode = AutoCompleteMode.None;
            txtSearch.AutoCompleteSource = AutoCompleteSource.None;
            txtSearch.AutoSizeHeight = true;
            txtSearch.BackColor = Color.Transparent;
            txtSearch.BackgroundImage = (Image)resources.GetObject("txtSearch.BackgroundImage");
            txtSearch.BorderColorActive = Color.DarkGoldenrod;
            txtSearch.BorderColorDisabled = Color.FromArgb(204, 204, 204);
            txtSearch.BorderColorHover = Color.DarkGoldenrod;
            txtSearch.BorderColorIdle = Color.Silver;
            txtSearch.BorderRadius = 35;
            txtSearch.BorderThickness = 1;
            txtSearch.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            txtSearch.CharacterCasing = CharacterCasing.Normal;
            txtSearch.DefaultFont = new Font("Microsoft Sans Serif", 9F, FontStyle.Regular, GraphicsUnit.Point, 0);
            txtSearch.DefaultText = "";
            txtSearch.FillColor = Color.White;
            txtSearch.HideSelection = true;
            txtSearch.IconLeft = null;
            txtSearch.IconLeftCursor = Cursors.IBeam;
            txtSearch.IconPadding = 10;
            txtSearch.IconRight = null;
            txtSearch.IconRightCursor = Cursors.IBeam;
            txtSearch.Location = new Point(487, 72);
            txtSearch.MaxLength = 32767;
            txtSearch.MinimumSize = new Size(1, 1);
            txtSearch.Modified = false;
            txtSearch.Multiline = false;
            txtSearch.Name = "txtSearch";
            stateProperties1.BorderColor = Color.DarkGoldenrod;
            stateProperties1.FillColor = Color.Empty;
            stateProperties1.ForeColor = Color.Empty;
            stateProperties1.PlaceholderForeColor = Color.Empty;
            txtSearch.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = Color.FromArgb(204, 204, 204);
            stateProperties2.FillColor = Color.FromArgb(240, 240, 240);
            stateProperties2.ForeColor = Color.FromArgb(109, 109, 109);
            stateProperties2.PlaceholderForeColor = Color.DarkGray;
            txtSearch.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = Color.DarkGoldenrod;
            stateProperties3.FillColor = Color.Empty;
            stateProperties3.ForeColor = Color.Empty;
            stateProperties3.PlaceholderForeColor = Color.Empty;
            txtSearch.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = Color.Silver;
            stateProperties4.FillColor = Color.White;
            stateProperties4.ForeColor = Color.Empty;
            stateProperties4.PlaceholderForeColor = Color.Empty;
            txtSearch.OnIdleState = stateProperties4;
            txtSearch.Padding = new Padding(3);
            txtSearch.PasswordChar = '\0';
            txtSearch.PlaceholderForeColor = Color.Silver;
            txtSearch.PlaceholderText = "Search ...";
            txtSearch.ReadOnly = false;
            txtSearch.ScrollBars = ScrollBars.None;
            txtSearch.SelectedText = "";
            txtSearch.SelectionLength = 0;
            txtSearch.SelectionStart = 0;
            txtSearch.ShortcutsEnabled = true;
            txtSearch.Size = new Size(661, 36);
            txtSearch.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            txtSearch.TabIndex = 112;
            txtSearch.TextAlign = HorizontalAlignment.Left;
            txtSearch.TextMarginBottom = 0;
            txtSearch.TextMarginLeft = 3;
            txtSearch.TextMarginTop = 1;
            txtSearch.TextPlaceholder = "Search ...";
            txtSearch.UseSystemPasswordChar = false;
            txtSearch.WordWrap = true;
            // 
            // btnClear
            // 
            btnClear.AllowAnimations = true;
            btnClear.AllowMouseEffects = true;
            btnClear.AllowToggling = false;
            btnClear.AnimationSpeed = 200;
            btnClear.AutoGenerateColors = false;
            btnClear.AutoRoundBorders = false;
            btnClear.AutoSizeLeftIcon = true;
            btnClear.AutoSizeRightIcon = true;
            btnClear.BackColor = Color.Transparent;
            btnClear.BackColor1 = Color.White;
            btnClear.BackgroundImage = (Image)resources.GetObject("btnClear.BackgroundImage");
            btnClear.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnClear.ButtonText = "Clear";
            btnClear.ButtonTextMarginLeft = 0;
            btnClear.ColorContrastOnClick = 45;
            btnClear.ColorContrastOnHover = 45;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            btnClear.CustomizableEdges = borderEdges2;
            btnClear.DialogResult = DialogResult.None;
            btnClear.DisabledBorderColor = Color.FromArgb(191, 191, 191);
            btnClear.DisabledFillColor = Color.FromArgb(204, 204, 204);
            btnClear.DisabledForecolor = Color.FromArgb(168, 160, 168);
            btnClear.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            btnClear.Font = new Font("Sitka Text", 9F);
            btnClear.ForeColor = Color.Black;
            btnClear.IconLeftAlign = ContentAlignment.MiddleLeft;
            btnClear.IconLeftCursor = Cursors.Default;
            btnClear.IconLeftPadding = new Padding(11, 3, 3, 3);
            btnClear.IconMarginLeft = 11;
            btnClear.IconPadding = 10;
            btnClear.IconRightAlign = ContentAlignment.MiddleRight;
            btnClear.IconRightCursor = Cursors.Default;
            btnClear.IconRightPadding = new Padding(3, 3, 7, 3);
            btnClear.IconSize = 25;
            btnClear.IdleBorderColor = Color.White;
            btnClear.IdleBorderRadius = 35;
            btnClear.IdleBorderThickness = 1;
            btnClear.IdleFillColor = Color.White;
            btnClear.IdleIconLeftImage = null;
            btnClear.IdleIconRightImage = null;
            btnClear.IndicateFocus = false;
            btnClear.Location = new Point(356, 71);
            btnClear.Name = "btnClear";
            btnClear.OnDisabledState.BorderColor = Color.FromArgb(191, 191, 191);
            btnClear.OnDisabledState.BorderRadius = 35;
            btnClear.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnClear.OnDisabledState.BorderThickness = 1;
            btnClear.OnDisabledState.FillColor = Color.FromArgb(204, 204, 204);
            btnClear.OnDisabledState.ForeColor = Color.FromArgb(168, 160, 168);
            btnClear.OnDisabledState.IconLeftImage = null;
            btnClear.OnDisabledState.IconRightImage = null;
            btnClear.onHoverState.BorderColor = Color.DarkGoldenrod;
            btnClear.onHoverState.BorderRadius = 35;
            btnClear.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnClear.onHoverState.BorderThickness = 1;
            btnClear.onHoverState.FillColor = Color.White;
            btnClear.onHoverState.ForeColor = Color.Black;
            btnClear.onHoverState.IconLeftImage = null;
            btnClear.onHoverState.IconRightImage = null;
            btnClear.OnIdleState.BorderColor = Color.White;
            btnClear.OnIdleState.BorderRadius = 35;
            btnClear.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnClear.OnIdleState.BorderThickness = 1;
            btnClear.OnIdleState.FillColor = Color.White;
            btnClear.OnIdleState.ForeColor = Color.Black;
            btnClear.OnIdleState.IconLeftImage = null;
            btnClear.OnIdleState.IconRightImage = null;
            btnClear.OnPressedState.BorderColor = Color.FromArgb(40, 96, 144);
            btnClear.OnPressedState.BorderRadius = 35;
            btnClear.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnClear.OnPressedState.BorderThickness = 1;
            btnClear.OnPressedState.FillColor = Color.FromArgb(40, 96, 144);
            btnClear.OnPressedState.ForeColor = Color.White;
            btnClear.OnPressedState.IconLeftImage = null;
            btnClear.OnPressedState.IconRightImage = null;
            btnClear.Size = new Size(80, 39);
            btnClear.TabIndex = 117;
            btnClear.TextAlign = ContentAlignment.MiddleCenter;
            btnClear.TextAlignment = HorizontalAlignment.Center;
            btnClear.TextMarginLeft = 0;
            btnClear.TextPadding = new Padding(0);
            btnClear.UseDefaultRadiusAndThickness = true;
            // 
            // btnDelete
            // 
            btnDelete.AllowAnimations = true;
            btnDelete.AllowMouseEffects = true;
            btnDelete.AllowToggling = false;
            btnDelete.AnimationSpeed = 200;
            btnDelete.AutoGenerateColors = false;
            btnDelete.AutoRoundBorders = false;
            btnDelete.AutoSizeLeftIcon = true;
            btnDelete.AutoSizeRightIcon = true;
            btnDelete.BackColor = Color.Transparent;
            btnDelete.BackColor1 = Color.White;
            btnDelete.BackgroundImage = (Image)resources.GetObject("btnDelete.BackgroundImage");
            btnDelete.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnDelete.ButtonText = "Delete";
            btnDelete.ButtonTextMarginLeft = 0;
            btnDelete.ColorContrastOnClick = 45;
            btnDelete.ColorContrastOnHover = 45;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            btnDelete.CustomizableEdges = borderEdges3;
            btnDelete.DialogResult = DialogResult.None;
            btnDelete.DisabledBorderColor = Color.FromArgb(191, 191, 191);
            btnDelete.DisabledFillColor = Color.FromArgb(204, 204, 204);
            btnDelete.DisabledForecolor = Color.FromArgb(168, 160, 168);
            btnDelete.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            btnDelete.Font = new Font("Sitka Text", 9F);
            btnDelete.ForeColor = Color.Black;
            btnDelete.IconLeftAlign = ContentAlignment.MiddleLeft;
            btnDelete.IconLeftCursor = Cursors.Default;
            btnDelete.IconLeftPadding = new Padding(11, 3, 3, 3);
            btnDelete.IconMarginLeft = 11;
            btnDelete.IconPadding = 10;
            btnDelete.IconRightAlign = ContentAlignment.MiddleRight;
            btnDelete.IconRightCursor = Cursors.Default;
            btnDelete.IconRightPadding = new Padding(3, 3, 7, 3);
            btnDelete.IconSize = 25;
            btnDelete.IdleBorderColor = Color.White;
            btnDelete.IdleBorderRadius = 35;
            btnDelete.IdleBorderThickness = 1;
            btnDelete.IdleFillColor = Color.White;
            btnDelete.IdleIconLeftImage = null;
            btnDelete.IdleIconRightImage = null;
            btnDelete.IndicateFocus = false;
            btnDelete.Location = new Point(270, 71);
            btnDelete.Name = "btnDelete";
            btnDelete.OnDisabledState.BorderColor = Color.FromArgb(191, 191, 191);
            btnDelete.OnDisabledState.BorderRadius = 35;
            btnDelete.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnDelete.OnDisabledState.BorderThickness = 1;
            btnDelete.OnDisabledState.FillColor = Color.FromArgb(204, 204, 204);
            btnDelete.OnDisabledState.ForeColor = Color.FromArgb(168, 160, 168);
            btnDelete.OnDisabledState.IconLeftImage = null;
            btnDelete.OnDisabledState.IconRightImage = null;
            btnDelete.onHoverState.BorderColor = Color.DarkGoldenrod;
            btnDelete.onHoverState.BorderRadius = 35;
            btnDelete.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnDelete.onHoverState.BorderThickness = 1;
            btnDelete.onHoverState.FillColor = Color.White;
            btnDelete.onHoverState.ForeColor = Color.Black;
            btnDelete.onHoverState.IconLeftImage = null;
            btnDelete.onHoverState.IconRightImage = null;
            btnDelete.OnIdleState.BorderColor = Color.White;
            btnDelete.OnIdleState.BorderRadius = 35;
            btnDelete.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnDelete.OnIdleState.BorderThickness = 1;
            btnDelete.OnIdleState.FillColor = Color.White;
            btnDelete.OnIdleState.ForeColor = Color.Black;
            btnDelete.OnIdleState.IconLeftImage = null;
            btnDelete.OnIdleState.IconRightImage = null;
            btnDelete.OnPressedState.BorderColor = Color.FromArgb(40, 96, 144);
            btnDelete.OnPressedState.BorderRadius = 35;
            btnDelete.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnDelete.OnPressedState.BorderThickness = 1;
            btnDelete.OnPressedState.FillColor = Color.FromArgb(40, 96, 144);
            btnDelete.OnPressedState.ForeColor = Color.White;
            btnDelete.OnPressedState.IconLeftImage = null;
            btnDelete.OnPressedState.IconRightImage = null;
            btnDelete.Size = new Size(80, 39);
            btnDelete.TabIndex = 116;
            btnDelete.TextAlign = ContentAlignment.MiddleCenter;
            btnDelete.TextAlignment = HorizontalAlignment.Center;
            btnDelete.TextMarginLeft = 0;
            btnDelete.TextPadding = new Padding(0);
            btnDelete.UseDefaultRadiusAndThickness = true;
            // 
            // btnUpdate
            // 
            btnUpdate.AllowAnimations = true;
            btnUpdate.AllowMouseEffects = true;
            btnUpdate.AllowToggling = false;
            btnUpdate.AnimationSpeed = 200;
            btnUpdate.AutoGenerateColors = false;
            btnUpdate.AutoRoundBorders = false;
            btnUpdate.AutoSizeLeftIcon = true;
            btnUpdate.AutoSizeRightIcon = true;
            btnUpdate.BackColor = Color.Transparent;
            btnUpdate.BackColor1 = Color.White;
            btnUpdate.BackgroundImage = (Image)resources.GetObject("btnUpdate.BackgroundImage");
            btnUpdate.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnUpdate.ButtonText = "Update";
            btnUpdate.ButtonTextMarginLeft = 0;
            btnUpdate.ColorContrastOnClick = 45;
            btnUpdate.ColorContrastOnHover = 45;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            btnUpdate.CustomizableEdges = borderEdges4;
            btnUpdate.DialogResult = DialogResult.None;
            btnUpdate.DisabledBorderColor = Color.FromArgb(191, 191, 191);
            btnUpdate.DisabledFillColor = Color.FromArgb(204, 204, 204);
            btnUpdate.DisabledForecolor = Color.FromArgb(168, 160, 168);
            btnUpdate.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            btnUpdate.Font = new Font("Sitka Text", 9F);
            btnUpdate.ForeColor = Color.Black;
            btnUpdate.IconLeftAlign = ContentAlignment.MiddleLeft;
            btnUpdate.IconLeftCursor = Cursors.Default;
            btnUpdate.IconLeftPadding = new Padding(11, 3, 3, 3);
            btnUpdate.IconMarginLeft = 11;
            btnUpdate.IconPadding = 10;
            btnUpdate.IconRightAlign = ContentAlignment.MiddleRight;
            btnUpdate.IconRightCursor = Cursors.Default;
            btnUpdate.IconRightPadding = new Padding(3, 3, 7, 3);
            btnUpdate.IconSize = 25;
            btnUpdate.IdleBorderColor = Color.White;
            btnUpdate.IdleBorderRadius = 35;
            btnUpdate.IdleBorderThickness = 1;
            btnUpdate.IdleFillColor = Color.White;
            btnUpdate.IdleIconLeftImage = null;
            btnUpdate.IdleIconRightImage = null;
            btnUpdate.IndicateFocus = false;
            btnUpdate.Location = new Point(184, 71);
            btnUpdate.Name = "btnUpdate";
            btnUpdate.OnDisabledState.BorderColor = Color.FromArgb(191, 191, 191);
            btnUpdate.OnDisabledState.BorderRadius = 35;
            btnUpdate.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnUpdate.OnDisabledState.BorderThickness = 1;
            btnUpdate.OnDisabledState.FillColor = Color.FromArgb(204, 204, 204);
            btnUpdate.OnDisabledState.ForeColor = Color.FromArgb(168, 160, 168);
            btnUpdate.OnDisabledState.IconLeftImage = null;
            btnUpdate.OnDisabledState.IconRightImage = null;
            btnUpdate.onHoverState.BorderColor = Color.DarkGoldenrod;
            btnUpdate.onHoverState.BorderRadius = 35;
            btnUpdate.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnUpdate.onHoverState.BorderThickness = 1;
            btnUpdate.onHoverState.FillColor = Color.White;
            btnUpdate.onHoverState.ForeColor = Color.Black;
            btnUpdate.onHoverState.IconLeftImage = null;
            btnUpdate.onHoverState.IconRightImage = null;
            btnUpdate.OnIdleState.BorderColor = Color.White;
            btnUpdate.OnIdleState.BorderRadius = 35;
            btnUpdate.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnUpdate.OnIdleState.BorderThickness = 1;
            btnUpdate.OnIdleState.FillColor = Color.White;
            btnUpdate.OnIdleState.ForeColor = Color.Black;
            btnUpdate.OnIdleState.IconLeftImage = null;
            btnUpdate.OnIdleState.IconRightImage = null;
            btnUpdate.OnPressedState.BorderColor = Color.FromArgb(40, 96, 144);
            btnUpdate.OnPressedState.BorderRadius = 35;
            btnUpdate.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnUpdate.OnPressedState.BorderThickness = 1;
            btnUpdate.OnPressedState.FillColor = Color.FromArgb(40, 96, 144);
            btnUpdate.OnPressedState.ForeColor = Color.White;
            btnUpdate.OnPressedState.IconLeftImage = null;
            btnUpdate.OnPressedState.IconRightImage = null;
            btnUpdate.Size = new Size(80, 39);
            btnUpdate.TabIndex = 115;
            btnUpdate.TextAlign = ContentAlignment.MiddleCenter;
            btnUpdate.TextAlignment = HorizontalAlignment.Center;
            btnUpdate.TextMarginLeft = 0;
            btnUpdate.TextPadding = new Padding(0);
            btnUpdate.UseDefaultRadiusAndThickness = true;
            // 
            // btnInsert
            // 
            btnInsert.AllowAnimations = true;
            btnInsert.AllowMouseEffects = true;
            btnInsert.AllowToggling = false;
            btnInsert.AnimationSpeed = 200;
            btnInsert.AutoGenerateColors = false;
            btnInsert.AutoRoundBorders = false;
            btnInsert.AutoSizeLeftIcon = true;
            btnInsert.AutoSizeRightIcon = true;
            btnInsert.BackColor = Color.Transparent;
            btnInsert.BackColor1 = Color.White;
            btnInsert.BackgroundImage = (Image)resources.GetObject("btnInsert.BackgroundImage");
            btnInsert.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnInsert.ButtonText = "Insert";
            btnInsert.ButtonTextMarginLeft = 0;
            btnInsert.ColorContrastOnClick = 45;
            btnInsert.ColorContrastOnHover = 45;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            btnInsert.CustomizableEdges = borderEdges5;
            btnInsert.DialogResult = DialogResult.None;
            btnInsert.DisabledBorderColor = Color.FromArgb(191, 191, 191);
            btnInsert.DisabledFillColor = Color.FromArgb(204, 204, 204);
            btnInsert.DisabledForecolor = Color.FromArgb(168, 160, 168);
            btnInsert.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            btnInsert.Font = new Font("Sitka Text", 9F);
            btnInsert.ForeColor = Color.Black;
            btnInsert.IconLeftAlign = ContentAlignment.MiddleLeft;
            btnInsert.IconLeftCursor = Cursors.Default;
            btnInsert.IconLeftPadding = new Padding(11, 3, 3, 3);
            btnInsert.IconMarginLeft = 11;
            btnInsert.IconPadding = 10;
            btnInsert.IconRightAlign = ContentAlignment.MiddleRight;
            btnInsert.IconRightCursor = Cursors.Default;
            btnInsert.IconRightPadding = new Padding(3, 3, 7, 3);
            btnInsert.IconSize = 25;
            btnInsert.IdleBorderColor = Color.White;
            btnInsert.IdleBorderRadius = 35;
            btnInsert.IdleBorderThickness = 1;
            btnInsert.IdleFillColor = Color.White;
            btnInsert.IdleIconLeftImage = null;
            btnInsert.IdleIconRightImage = null;
            btnInsert.IndicateFocus = false;
            btnInsert.Location = new Point(98, 71);
            btnInsert.Name = "btnInsert";
            btnInsert.OnDisabledState.BorderColor = Color.FromArgb(191, 191, 191);
            btnInsert.OnDisabledState.BorderRadius = 35;
            btnInsert.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnInsert.OnDisabledState.BorderThickness = 1;
            btnInsert.OnDisabledState.FillColor = Color.FromArgb(204, 204, 204);
            btnInsert.OnDisabledState.ForeColor = Color.FromArgb(168, 160, 168);
            btnInsert.OnDisabledState.IconLeftImage = null;
            btnInsert.OnDisabledState.IconRightImage = null;
            btnInsert.onHoverState.BorderColor = Color.DarkGoldenrod;
            btnInsert.onHoverState.BorderRadius = 35;
            btnInsert.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnInsert.onHoverState.BorderThickness = 1;
            btnInsert.onHoverState.FillColor = Color.White;
            btnInsert.onHoverState.ForeColor = Color.Black;
            btnInsert.onHoverState.IconLeftImage = null;
            btnInsert.onHoverState.IconRightImage = null;
            btnInsert.OnIdleState.BorderColor = Color.White;
            btnInsert.OnIdleState.BorderRadius = 35;
            btnInsert.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnInsert.OnIdleState.BorderThickness = 1;
            btnInsert.OnIdleState.FillColor = Color.White;
            btnInsert.OnIdleState.ForeColor = Color.Black;
            btnInsert.OnIdleState.IconLeftImage = null;
            btnInsert.OnIdleState.IconRightImage = null;
            btnInsert.OnPressedState.BorderColor = Color.FromArgb(40, 96, 144);
            btnInsert.OnPressedState.BorderRadius = 35;
            btnInsert.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnInsert.OnPressedState.BorderThickness = 1;
            btnInsert.OnPressedState.FillColor = Color.FromArgb(40, 96, 144);
            btnInsert.OnPressedState.ForeColor = Color.White;
            btnInsert.OnPressedState.IconLeftImage = null;
            btnInsert.OnPressedState.IconRightImage = null;
            btnInsert.Size = new Size(80, 39);
            btnInsert.TabIndex = 114;
            btnInsert.TextAlign = ContentAlignment.MiddleCenter;
            btnInsert.TextAlignment = HorizontalAlignment.Center;
            btnInsert.TextMarginLeft = 0;
            btnInsert.TextPadding = new Padding(0);
            btnInsert.UseDefaultRadiusAndThickness = true;
            // 
            // btnNew
            // 
            btnNew.AllowAnimations = true;
            btnNew.AllowMouseEffects = true;
            btnNew.AllowToggling = false;
            btnNew.AnimationSpeed = 200;
            btnNew.AutoGenerateColors = false;
            btnNew.AutoRoundBorders = false;
            btnNew.AutoSizeLeftIcon = true;
            btnNew.AutoSizeRightIcon = true;
            btnNew.BackColor = Color.Transparent;
            btnNew.BackColor1 = Color.White;
            btnNew.BackgroundImage = (Image)resources.GetObject("btnNew.BackgroundImage");
            btnNew.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnNew.ButtonText = "New";
            btnNew.ButtonTextMarginLeft = 0;
            btnNew.ColorContrastOnClick = 45;
            btnNew.ColorContrastOnHover = 45;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            btnNew.CustomizableEdges = borderEdges6;
            btnNew.DialogResult = DialogResult.None;
            btnNew.DisabledBorderColor = Color.FromArgb(191, 191, 191);
            btnNew.DisabledFillColor = Color.FromArgb(204, 204, 204);
            btnNew.DisabledForecolor = Color.FromArgb(168, 160, 168);
            btnNew.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            btnNew.Font = new Font("Sitka Text", 9F);
            btnNew.ForeColor = Color.Black;
            btnNew.IconLeftAlign = ContentAlignment.MiddleLeft;
            btnNew.IconLeftCursor = Cursors.Default;
            btnNew.IconLeftPadding = new Padding(11, 3, 3, 3);
            btnNew.IconMarginLeft = 11;
            btnNew.IconPadding = 10;
            btnNew.IconRightAlign = ContentAlignment.MiddleRight;
            btnNew.IconRightCursor = Cursors.Default;
            btnNew.IconRightPadding = new Padding(3, 3, 7, 3);
            btnNew.IconSize = 25;
            btnNew.IdleBorderColor = Color.White;
            btnNew.IdleBorderRadius = 35;
            btnNew.IdleBorderThickness = 1;
            btnNew.IdleFillColor = Color.White;
            btnNew.IdleIconLeftImage = null;
            btnNew.IdleIconRightImage = null;
            btnNew.IndicateFocus = false;
            btnNew.Location = new Point(12, 71);
            btnNew.Name = "btnNew";
            btnNew.OnDisabledState.BorderColor = Color.FromArgb(191, 191, 191);
            btnNew.OnDisabledState.BorderRadius = 35;
            btnNew.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnNew.OnDisabledState.BorderThickness = 1;
            btnNew.OnDisabledState.FillColor = Color.FromArgb(204, 204, 204);
            btnNew.OnDisabledState.ForeColor = Color.FromArgb(168, 160, 168);
            btnNew.OnDisabledState.IconLeftImage = null;
            btnNew.OnDisabledState.IconRightImage = null;
            btnNew.onHoverState.BorderColor = Color.DarkGoldenrod;
            btnNew.onHoverState.BorderRadius = 35;
            btnNew.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnNew.onHoverState.BorderThickness = 1;
            btnNew.onHoverState.FillColor = Color.White;
            btnNew.onHoverState.ForeColor = Color.Black;
            btnNew.onHoverState.IconLeftImage = null;
            btnNew.onHoverState.IconRightImage = null;
            btnNew.OnIdleState.BorderColor = Color.White;
            btnNew.OnIdleState.BorderRadius = 35;
            btnNew.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnNew.OnIdleState.BorderThickness = 1;
            btnNew.OnIdleState.FillColor = Color.White;
            btnNew.OnIdleState.ForeColor = Color.Black;
            btnNew.OnIdleState.IconLeftImage = null;
            btnNew.OnIdleState.IconRightImage = null;
            btnNew.OnPressedState.BorderColor = Color.FromArgb(40, 96, 144);
            btnNew.OnPressedState.BorderRadius = 35;
            btnNew.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnNew.OnPressedState.BorderThickness = 1;
            btnNew.OnPressedState.FillColor = Color.FromArgb(40, 96, 144);
            btnNew.OnPressedState.ForeColor = Color.White;
            btnNew.OnPressedState.IconLeftImage = null;
            btnNew.OnPressedState.IconRightImage = null;
            btnNew.Size = new Size(80, 39);
            btnNew.TabIndex = 113;
            btnNew.TextAlign = ContentAlignment.MiddleCenter;
            btnNew.TextAlignment = HorizontalAlignment.Center;
            btnNew.TextMarginLeft = 0;
            btnNew.TextPadding = new Padding(0);
            btnNew.UseDefaultRadiusAndThickness = true;
            // 
            // dgvConsumable
            // 
            dgvConsumable.AllowCustomTheming = false;
            dataGridViewCellStyle1.BackColor = Color.FromArgb(255, 232, 191);
            dataGridViewCellStyle1.Font = new Font("Microsoft Sans Serif", 8.25F, FontStyle.Bold, GraphicsUnit.Point, 0);
            dataGridViewCellStyle1.ForeColor = Color.Black;
            dgvConsumable.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle1;
            dgvConsumable.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
            dgvConsumable.BackgroundColor = Color.White;
            dgvConsumable.BorderStyle = BorderStyle.None;
            dgvConsumable.CellBorderStyle = DataGridViewCellBorderStyle.SingleHorizontal;
            dgvConsumable.ColumnHeadersBorderStyle = DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle2.Alignment = DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle2.BackColor = Color.Orange;
            dataGridViewCellStyle2.Font = new Font("Segoe UI Semibold", 11.75F, FontStyle.Bold);
            dataGridViewCellStyle2.ForeColor = Color.White;
            dataGridViewCellStyle2.SelectionBackColor = Color.FromArgb(204, 132, 0);
            dataGridViewCellStyle2.SelectionForeColor = Color.White;
            dataGridViewCellStyle2.WrapMode = DataGridViewTriState.True;
            dgvConsumable.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2;
            dgvConsumable.ColumnHeadersHeight = 40;
            dgvConsumable.CurrentTheme.AlternatingRowsStyle.BackColor = Color.FromArgb(255, 232, 191);
            dgvConsumable.CurrentTheme.AlternatingRowsStyle.Font = new Font("Segoe UI Semibold", 9.75F, FontStyle.Bold);
            dgvConsumable.CurrentTheme.AlternatingRowsStyle.ForeColor = Color.Black;
            dgvConsumable.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = Color.FromArgb(255, 201, 102);
            dgvConsumable.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = Color.Black;
            dgvConsumable.CurrentTheme.BackColor = Color.Orange;
            dgvConsumable.CurrentTheme.GridColor = Color.FromArgb(255, 226, 173);
            dgvConsumable.CurrentTheme.HeaderStyle.BackColor = Color.Orange;
            dgvConsumable.CurrentTheme.HeaderStyle.Font = new Font("Segoe UI Semibold", 11.75F, FontStyle.Bold);
            dgvConsumable.CurrentTheme.HeaderStyle.ForeColor = Color.White;
            dgvConsumable.CurrentTheme.HeaderStyle.SelectionBackColor = Color.FromArgb(204, 132, 0);
            dgvConsumable.CurrentTheme.HeaderStyle.SelectionForeColor = Color.White;
            dgvConsumable.CurrentTheme.Name = null;
            dgvConsumable.CurrentTheme.RowsStyle.BackColor = Color.FromArgb(255, 237, 204);
            dgvConsumable.CurrentTheme.RowsStyle.Font = new Font("Segoe UI Semibold", 9.75F, FontStyle.Bold);
            dgvConsumable.CurrentTheme.RowsStyle.ForeColor = Color.Black;
            dgvConsumable.CurrentTheme.RowsStyle.SelectionBackColor = Color.FromArgb(255, 201, 102);
            dgvConsumable.CurrentTheme.RowsStyle.SelectionForeColor = Color.Black;
            dataGridViewCellStyle3.Alignment = DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle3.BackColor = Color.FromArgb(255, 237, 204);
            dataGridViewCellStyle3.Font = new Font("Segoe UI Semibold", 9.75F, FontStyle.Bold);
            dataGridViewCellStyle3.ForeColor = Color.Black;
            dataGridViewCellStyle3.SelectionBackColor = Color.FromArgb(255, 201, 102);
            dataGridViewCellStyle3.SelectionForeColor = Color.Black;
            dataGridViewCellStyle3.WrapMode = DataGridViewTriState.False;
            dgvConsumable.DefaultCellStyle = dataGridViewCellStyle3;
            dgvConsumable.EnableHeadersVisualStyles = false;
            dgvConsumable.GridColor = Color.FromArgb(255, 226, 173);
            dgvConsumable.HeaderBackColor = Color.Orange;
            dgvConsumable.HeaderBgColor = Color.Empty;
            dgvConsumable.HeaderForeColor = Color.White;
            dgvConsumable.Location = new Point(487, 142);
            dgvConsumable.Name = "dgvConsumable";
            dgvConsumable.RowHeadersVisible = false;
            dgvConsumable.RowTemplate.Height = 40;
            dgvConsumable.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
            dgvConsumable.Size = new Size(665, 553);
            dgvConsumable.TabIndex = 118;
            dgvConsumable.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.Orange;
            // 
            // txtID
            // 
            txtID.AcceptsReturn = false;
            txtID.AcceptsTab = false;
            txtID.AnimationSpeed = 200;
            txtID.AutoCompleteMode = AutoCompleteMode.None;
            txtID.AutoCompleteSource = AutoCompleteSource.None;
            txtID.AutoSizeHeight = true;
            txtID.BackColor = Color.Transparent;
            txtID.BackgroundImage = (Image)resources.GetObject("txtID.BackgroundImage");
            txtID.BorderColorActive = Color.DarkGoldenrod;
            txtID.BorderColorDisabled = Color.FromArgb(204, 204, 204);
            txtID.BorderColorHover = Color.DarkGoldenrod;
            txtID.BorderColorIdle = Color.Silver;
            txtID.BorderRadius = 35;
            txtID.BorderThickness = 1;
            txtID.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            txtID.CharacterCasing = CharacterCasing.Normal;
            txtID.DefaultFont = new Font("Microsoft Sans Serif", 9F, FontStyle.Bold);
            txtID.DefaultText = "";
            txtID.Enabled = false;
            txtID.FillColor = Color.White;
            txtID.HideSelection = true;
            txtID.IconLeft = null;
            txtID.IconLeftCursor = Cursors.IBeam;
            txtID.IconPadding = 10;
            txtID.IconRight = null;
            txtID.IconRightCursor = Cursors.IBeam;
            txtID.Location = new Point(165, 145);
            txtID.MaxLength = 32767;
            txtID.MinimumSize = new Size(1, 1);
            txtID.Modified = false;
            txtID.Multiline = false;
            txtID.Name = "txtID";
            stateProperties5.BorderColor = Color.DarkGoldenrod;
            stateProperties5.FillColor = Color.Empty;
            stateProperties5.ForeColor = Color.Empty;
            stateProperties5.PlaceholderForeColor = Color.Empty;
            txtID.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = Color.FromArgb(204, 204, 204);
            stateProperties6.FillColor = Color.FromArgb(240, 240, 240);
            stateProperties6.ForeColor = Color.FromArgb(109, 109, 109);
            stateProperties6.PlaceholderForeColor = Color.DarkGray;
            txtID.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = Color.DarkGoldenrod;
            stateProperties7.FillColor = Color.Empty;
            stateProperties7.ForeColor = Color.Empty;
            stateProperties7.PlaceholderForeColor = Color.Empty;
            txtID.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = Color.Silver;
            stateProperties8.FillColor = Color.White;
            stateProperties8.ForeColor = Color.Empty;
            stateProperties8.PlaceholderForeColor = Color.Empty;
            txtID.OnIdleState = stateProperties8;
            txtID.Padding = new Padding(3);
            txtID.PasswordChar = '\0';
            txtID.PlaceholderForeColor = Color.Silver;
            txtID.PlaceholderText = "Enter text";
            txtID.ReadOnly = true;
            txtID.ScrollBars = ScrollBars.None;
            txtID.SelectedText = "";
            txtID.SelectionLength = 0;
            txtID.SelectionStart = 0;
            txtID.ShortcutsEnabled = true;
            txtID.Size = new Size(271, 36);
            txtID.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            txtID.TabIndex = 120;
            txtID.TextAlign = HorizontalAlignment.Left;
            txtID.TextMarginBottom = 0;
            txtID.TextMarginLeft = 3;
            txtID.TextMarginTop = 1;
            txtID.TextPlaceholder = "Enter text";
            txtID.UseSystemPasswordChar = false;
            txtID.WordWrap = true;
            // 
            // label1
            // 
            label1.AutoSize = true;
            label1.Font = new Font("Sitka Text", 14.2499981F);
            label1.Location = new Point(12, 145);
            label1.Name = "label1";
            label1.Size = new Size(32, 28);
            label1.TabIndex = 119;
            label1.Text = "ID";
            // 
            // cboCategory
            // 
            cboCategory.BackColor = Color.Transparent;
            cboCategory.BackgroundColor = Color.White;
            cboCategory.BorderColor = Color.Silver;
            cboCategory.BorderRadius = 15;
            cboCategory.Color = Color.Silver;
            cboCategory.Direction = Bunifu.UI.WinForms.BunifuDropdown.Directions.Down;
            cboCategory.DisabledBackColor = Color.FromArgb(240, 240, 240);
            cboCategory.DisabledBorderColor = Color.FromArgb(204, 204, 204);
            cboCategory.DisabledColor = Color.FromArgb(240, 240, 240);
            cboCategory.DisabledForeColor = Color.FromArgb(109, 109, 109);
            cboCategory.DisabledIndicatorColor = Color.DarkGray;
            cboCategory.DrawMode = DrawMode.OwnerDrawFixed;
            cboCategory.DropdownBorderThickness = Bunifu.UI.WinForms.BunifuDropdown.BorderThickness.Thin;
            cboCategory.DropDownStyle = ComboBoxStyle.DropDownList;
            cboCategory.DropDownTextAlign = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            cboCategory.FillDropDown = true;
            cboCategory.FillIndicator = false;
            cboCategory.FlatStyle = FlatStyle.Flat;
            cboCategory.Font = new Font("Microsoft Sans Serif", 12F);
            cboCategory.ForeColor = Color.Silver;
            cboCategory.FormattingEnabled = true;
            cboCategory.Icon = null;
            cboCategory.IndicatorAlignment = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            cboCategory.IndicatorColor = Color.DarkGray;
            cboCategory.IndicatorLocation = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            cboCategory.IndicatorThickness = 2;
            cboCategory.IsDropdownOpened = false;
            cboCategory.ItemBackColor = Color.White;
            cboCategory.ItemBorderColor = Color.White;
            cboCategory.ItemForeColor = Color.Black;
            cboCategory.ItemHeight = 26;
            cboCategory.ItemHighLightColor = Color.DodgerBlue;
            cboCategory.ItemHighLightForeColor = Color.White;
            cboCategory.Items.AddRange(new object[] { "Foods", "Drinks" });
            cboCategory.ItemTopMargin = 3;
            cboCategory.Location = new Point(165, 199);
            cboCategory.Name = "cboCategory";
            cboCategory.Size = new Size(271, 32);
            cboCategory.TabIndex = 3;
            cboCategory.Text = "Select Category";
            cboCategory.TextAlignment = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            cboCategory.TextLeftMargin = 5;
            // 
            // label4
            // 
            label4.AutoSize = true;
            label4.Font = new Font("Sitka Text", 14.2499981F);
            label4.Location = new Point(12, 195);
            label4.Name = "label4";
            label4.Size = new Size(91, 28);
            label4.TabIndex = 121;
            label4.Text = "Category";
            // 
            // txtName
            // 
            txtName.AcceptsReturn = false;
            txtName.AcceptsTab = false;
            txtName.AnimationSpeed = 200;
            txtName.AutoCompleteMode = AutoCompleteMode.None;
            txtName.AutoCompleteSource = AutoCompleteSource.None;
            txtName.AutoSizeHeight = true;
            txtName.BackColor = Color.Transparent;
            txtName.BackgroundImage = (Image)resources.GetObject("txtName.BackgroundImage");
            txtName.BorderColorActive = Color.DarkGoldenrod;
            txtName.BorderColorDisabled = Color.FromArgb(204, 204, 204);
            txtName.BorderColorHover = Color.DarkGoldenrod;
            txtName.BorderColorIdle = Color.Silver;
            txtName.BorderRadius = 35;
            txtName.BorderThickness = 1;
            txtName.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            txtName.CharacterCasing = CharacterCasing.Normal;
            txtName.DefaultFont = new Font("Microsoft Sans Serif", 9F, FontStyle.Bold);
            txtName.DefaultText = "";
            txtName.FillColor = Color.White;
            txtName.HideSelection = true;
            txtName.IconLeft = null;
            txtName.IconLeftCursor = Cursors.IBeam;
            txtName.IconPadding = 10;
            txtName.IconRight = null;
            txtName.IconRightCursor = Cursors.IBeam;
            txtName.Location = new Point(165, 245);
            txtName.MaxLength = 32767;
            txtName.MinimumSize = new Size(1, 1);
            txtName.Modified = false;
            txtName.Multiline = false;
            txtName.Name = "txtName";
            stateProperties9.BorderColor = Color.DarkGoldenrod;
            stateProperties9.FillColor = Color.Empty;
            stateProperties9.ForeColor = Color.Empty;
            stateProperties9.PlaceholderForeColor = Color.Empty;
            txtName.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = Color.FromArgb(204, 204, 204);
            stateProperties10.FillColor = Color.FromArgb(240, 240, 240);
            stateProperties10.ForeColor = Color.FromArgb(109, 109, 109);
            stateProperties10.PlaceholderForeColor = Color.DarkGray;
            txtName.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = Color.DarkGoldenrod;
            stateProperties11.FillColor = Color.Empty;
            stateProperties11.ForeColor = Color.Empty;
            stateProperties11.PlaceholderForeColor = Color.Empty;
            txtName.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = Color.Silver;
            stateProperties12.FillColor = Color.White;
            stateProperties12.ForeColor = Color.Empty;
            stateProperties12.PlaceholderForeColor = Color.Empty;
            txtName.OnIdleState = stateProperties12;
            txtName.Padding = new Padding(3);
            txtName.PasswordChar = '\0';
            txtName.PlaceholderForeColor = Color.Silver;
            txtName.PlaceholderText = "Enter text";
            txtName.ReadOnly = false;
            txtName.ScrollBars = ScrollBars.None;
            txtName.SelectedText = "";
            txtName.SelectionLength = 0;
            txtName.SelectionStart = 0;
            txtName.ShortcutsEnabled = true;
            txtName.Size = new Size(271, 36);
            txtName.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            txtName.TabIndex = 124;
            txtName.TextAlign = HorizontalAlignment.Left;
            txtName.TextMarginBottom = 0;
            txtName.TextMarginLeft = 3;
            txtName.TextMarginTop = 1;
            txtName.TextPlaceholder = "Enter text";
            txtName.UseSystemPasswordChar = false;
            txtName.WordWrap = true;
            // 
            // label2
            // 
            label2.AutoSize = true;
            label2.Font = new Font("Sitka Text", 14.2499981F);
            label2.Location = new Point(12, 245);
            label2.Name = "label2";
            label2.Size = new Size(64, 28);
            label2.TabIndex = 123;
            label2.Text = "Name";
            // 
            // txtPrice
            // 
            txtPrice.AcceptsReturn = false;
            txtPrice.AcceptsTab = false;
            txtPrice.AnimationSpeed = 200;
            txtPrice.AutoCompleteMode = AutoCompleteMode.None;
            txtPrice.AutoCompleteSource = AutoCompleteSource.None;
            txtPrice.AutoSizeHeight = true;
            txtPrice.BackColor = Color.Transparent;
            txtPrice.BackgroundImage = (Image)resources.GetObject("txtPrice.BackgroundImage");
            txtPrice.BorderColorActive = Color.DarkGoldenrod;
            txtPrice.BorderColorDisabled = Color.FromArgb(204, 204, 204);
            txtPrice.BorderColorHover = Color.DarkGoldenrod;
            txtPrice.BorderColorIdle = Color.Silver;
            txtPrice.BorderRadius = 35;
            txtPrice.BorderThickness = 1;
            txtPrice.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            txtPrice.CharacterCasing = CharacterCasing.Normal;
            txtPrice.DefaultFont = new Font("Microsoft Sans Serif", 9F, FontStyle.Bold);
            txtPrice.DefaultText = "";
            txtPrice.FillColor = Color.White;
            txtPrice.HideSelection = true;
            txtPrice.IconLeft = null;
            txtPrice.IconLeftCursor = Cursors.IBeam;
            txtPrice.IconPadding = 10;
            txtPrice.IconRight = null;
            txtPrice.IconRightCursor = Cursors.IBeam;
            txtPrice.Location = new Point(165, 295);
            txtPrice.MaxLength = 32767;
            txtPrice.MinimumSize = new Size(1, 1);
            txtPrice.Modified = false;
            txtPrice.Multiline = false;
            txtPrice.Name = "txtPrice";
            stateProperties13.BorderColor = Color.DarkGoldenrod;
            stateProperties13.FillColor = Color.Empty;
            stateProperties13.ForeColor = Color.Empty;
            stateProperties13.PlaceholderForeColor = Color.Empty;
            txtPrice.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = Color.FromArgb(204, 204, 204);
            stateProperties14.FillColor = Color.FromArgb(240, 240, 240);
            stateProperties14.ForeColor = Color.FromArgb(109, 109, 109);
            stateProperties14.PlaceholderForeColor = Color.DarkGray;
            txtPrice.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = Color.DarkGoldenrod;
            stateProperties15.FillColor = Color.Empty;
            stateProperties15.ForeColor = Color.Empty;
            stateProperties15.PlaceholderForeColor = Color.Empty;
            txtPrice.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = Color.Silver;
            stateProperties16.FillColor = Color.White;
            stateProperties16.ForeColor = Color.Empty;
            stateProperties16.PlaceholderForeColor = Color.Empty;
            txtPrice.OnIdleState = stateProperties16;
            txtPrice.Padding = new Padding(3);
            txtPrice.PasswordChar = '\0';
            txtPrice.PlaceholderForeColor = Color.Silver;
            txtPrice.PlaceholderText = "Enter text";
            txtPrice.ReadOnly = false;
            txtPrice.ScrollBars = ScrollBars.None;
            txtPrice.SelectedText = "";
            txtPrice.SelectionLength = 0;
            txtPrice.SelectionStart = 0;
            txtPrice.ShortcutsEnabled = true;
            txtPrice.Size = new Size(271, 36);
            txtPrice.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            txtPrice.TabIndex = 126;
            txtPrice.TextAlign = HorizontalAlignment.Left;
            txtPrice.TextMarginBottom = 0;
            txtPrice.TextMarginLeft = 3;
            txtPrice.TextMarginTop = 1;
            txtPrice.TextPlaceholder = "Enter text";
            txtPrice.UseSystemPasswordChar = false;
            txtPrice.WordWrap = true;
            // 
            // label3
            // 
            label3.AutoSize = true;
            label3.Font = new Font("Sitka Text", 14.2499981F);
            label3.Location = new Point(12, 295);
            label3.Name = "label3";
            label3.Size = new Size(57, 28);
            label3.TabIndex = 125;
            label3.Text = "Price";
            // 
            // txtQuantity
            // 
            txtQuantity.AcceptsReturn = false;
            txtQuantity.AcceptsTab = false;
            txtQuantity.AnimationSpeed = 200;
            txtQuantity.AutoCompleteMode = AutoCompleteMode.None;
            txtQuantity.AutoCompleteSource = AutoCompleteSource.None;
            txtQuantity.AutoSizeHeight = true;
            txtQuantity.BackColor = Color.Transparent;
            txtQuantity.BackgroundImage = (Image)resources.GetObject("txtQuantity.BackgroundImage");
            txtQuantity.BorderColorActive = Color.DarkGoldenrod;
            txtQuantity.BorderColorDisabled = Color.FromArgb(204, 204, 204);
            txtQuantity.BorderColorHover = Color.DarkGoldenrod;
            txtQuantity.BorderColorIdle = Color.Silver;
            txtQuantity.BorderRadius = 35;
            txtQuantity.BorderThickness = 1;
            txtQuantity.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            txtQuantity.CharacterCasing = CharacterCasing.Normal;
            txtQuantity.DefaultFont = new Font("Microsoft Sans Serif", 9F, FontStyle.Bold);
            txtQuantity.DefaultText = "";
            txtQuantity.FillColor = Color.White;
            txtQuantity.HideSelection = true;
            txtQuantity.IconLeft = null;
            txtQuantity.IconLeftCursor = Cursors.IBeam;
            txtQuantity.IconPadding = 10;
            txtQuantity.IconRight = null;
            txtQuantity.IconRightCursor = Cursors.IBeam;
            txtQuantity.Location = new Point(165, 345);
            txtQuantity.MaxLength = 32767;
            txtQuantity.MinimumSize = new Size(1, 1);
            txtQuantity.Modified = false;
            txtQuantity.Multiline = false;
            txtQuantity.Name = "txtQuantity";
            stateProperties17.BorderColor = Color.DarkGoldenrod;
            stateProperties17.FillColor = Color.Empty;
            stateProperties17.ForeColor = Color.Empty;
            stateProperties17.PlaceholderForeColor = Color.Empty;
            txtQuantity.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = Color.FromArgb(204, 204, 204);
            stateProperties18.FillColor = Color.FromArgb(240, 240, 240);
            stateProperties18.ForeColor = Color.FromArgb(109, 109, 109);
            stateProperties18.PlaceholderForeColor = Color.DarkGray;
            txtQuantity.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = Color.DarkGoldenrod;
            stateProperties19.FillColor = Color.Empty;
            stateProperties19.ForeColor = Color.Empty;
            stateProperties19.PlaceholderForeColor = Color.Empty;
            txtQuantity.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = Color.Silver;
            stateProperties20.FillColor = Color.White;
            stateProperties20.ForeColor = Color.Empty;
            stateProperties20.PlaceholderForeColor = Color.Empty;
            txtQuantity.OnIdleState = stateProperties20;
            txtQuantity.Padding = new Padding(3);
            txtQuantity.PasswordChar = '\0';
            txtQuantity.PlaceholderForeColor = Color.Silver;
            txtQuantity.PlaceholderText = "Enter text";
            txtQuantity.ReadOnly = false;
            txtQuantity.ScrollBars = ScrollBars.None;
            txtQuantity.SelectedText = "";
            txtQuantity.SelectionLength = 0;
            txtQuantity.SelectionStart = 0;
            txtQuantity.ShortcutsEnabled = true;
            txtQuantity.Size = new Size(271, 36);
            txtQuantity.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            txtQuantity.TabIndex = 128;
            txtQuantity.TextAlign = HorizontalAlignment.Left;
            txtQuantity.TextMarginBottom = 0;
            txtQuantity.TextMarginLeft = 3;
            txtQuantity.TextMarginTop = 1;
            txtQuantity.TextPlaceholder = "Enter text";
            txtQuantity.UseSystemPasswordChar = false;
            txtQuantity.WordWrap = true;
            // 
            // label5
            // 
            label5.AutoSize = true;
            label5.Font = new Font("Sitka Text", 14.2499981F);
            label5.Location = new Point(12, 345);
            label5.Name = "label5";
            label5.Size = new Size(89, 28);
            label5.TabIndex = 127;
            label5.Text = "Quantity";
            // 
            // txtDescription
            // 
            txtDescription.AcceptsReturn = false;
            txtDescription.AcceptsTab = false;
            txtDescription.AnimationSpeed = 200;
            txtDescription.AutoCompleteMode = AutoCompleteMode.None;
            txtDescription.AutoCompleteSource = AutoCompleteSource.None;
            txtDescription.AutoSizeHeight = true;
            txtDescription.BackColor = Color.Transparent;
            txtDescription.BackgroundImage = (Image)resources.GetObject("txtDescription.BackgroundImage");
            txtDescription.BorderColorActive = Color.DarkGoldenrod;
            txtDescription.BorderColorDisabled = Color.FromArgb(204, 204, 204);
            txtDescription.BorderColorHover = Color.DarkGoldenrod;
            txtDescription.BorderColorIdle = Color.Silver;
            txtDescription.BorderRadius = 35;
            txtDescription.BorderThickness = 1;
            txtDescription.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            txtDescription.CharacterCasing = CharacterCasing.Normal;
            txtDescription.DefaultFont = new Font("Microsoft Sans Serif", 9F, FontStyle.Bold);
            txtDescription.DefaultText = "";
            txtDescription.FillColor = Color.White;
            txtDescription.HideSelection = true;
            txtDescription.IconLeft = null;
            txtDescription.IconLeftCursor = Cursors.IBeam;
            txtDescription.IconPadding = 10;
            txtDescription.IconRight = null;
            txtDescription.IconRightCursor = Cursors.IBeam;
            txtDescription.Location = new Point(165, 395);
            txtDescription.MaxLength = 32767;
            txtDescription.MinimumSize = new Size(1, 1);
            txtDescription.Modified = false;
            txtDescription.Multiline = false;
            txtDescription.Name = "txtDescription";
            stateProperties21.BorderColor = Color.DarkGoldenrod;
            stateProperties21.FillColor = Color.Empty;
            stateProperties21.ForeColor = Color.Empty;
            stateProperties21.PlaceholderForeColor = Color.Empty;
            txtDescription.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = Color.FromArgb(204, 204, 204);
            stateProperties22.FillColor = Color.FromArgb(240, 240, 240);
            stateProperties22.ForeColor = Color.FromArgb(109, 109, 109);
            stateProperties22.PlaceholderForeColor = Color.DarkGray;
            txtDescription.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = Color.DarkGoldenrod;
            stateProperties23.FillColor = Color.Empty;
            stateProperties23.ForeColor = Color.Empty;
            stateProperties23.PlaceholderForeColor = Color.Empty;
            txtDescription.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = Color.Silver;
            stateProperties24.FillColor = Color.White;
            stateProperties24.ForeColor = Color.Empty;
            stateProperties24.PlaceholderForeColor = Color.Empty;
            txtDescription.OnIdleState = stateProperties24;
            txtDescription.Padding = new Padding(3);
            txtDescription.PasswordChar = '\0';
            txtDescription.PlaceholderForeColor = Color.Silver;
            txtDescription.PlaceholderText = "Enter text";
            txtDescription.ReadOnly = false;
            txtDescription.ScrollBars = ScrollBars.None;
            txtDescription.SelectedText = "";
            txtDescription.SelectionLength = 0;
            txtDescription.SelectionStart = 0;
            txtDescription.ShortcutsEnabled = true;
            txtDescription.Size = new Size(271, 36);
            txtDescription.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            txtDescription.TabIndex = 130;
            txtDescription.TextAlign = HorizontalAlignment.Left;
            txtDescription.TextMarginBottom = 0;
            txtDescription.TextMarginLeft = 3;
            txtDescription.TextMarginTop = 1;
            txtDescription.TextPlaceholder = "Enter text";
            txtDescription.UseSystemPasswordChar = false;
            txtDescription.WordWrap = true;
            // 
            // label6
            // 
            label6.AutoSize = true;
            label6.Font = new Font("Sitka Text", 14.2499981F);
            label6.Location = new Point(12, 395);
            label6.Name = "label6";
            label6.Size = new Size(115, 28);
            label6.TabIndex = 129;
            label6.Text = "Description";
            // 
            // txtCreatedAt
            // 
            txtCreatedAt.AcceptsReturn = false;
            txtCreatedAt.AcceptsTab = false;
            txtCreatedAt.AnimationSpeed = 200;
            txtCreatedAt.AutoCompleteMode = AutoCompleteMode.None;
            txtCreatedAt.AutoCompleteSource = AutoCompleteSource.None;
            txtCreatedAt.AutoSizeHeight = true;
            txtCreatedAt.BackColor = Color.Transparent;
            txtCreatedAt.BackgroundImage = (Image)resources.GetObject("txtCreatedAt.BackgroundImage");
            txtCreatedAt.BorderColorActive = Color.DarkGoldenrod;
            txtCreatedAt.BorderColorDisabled = Color.FromArgb(204, 204, 204);
            txtCreatedAt.BorderColorHover = Color.DarkGoldenrod;
            txtCreatedAt.BorderColorIdle = Color.Silver;
            txtCreatedAt.BorderRadius = 35;
            txtCreatedAt.BorderThickness = 1;
            txtCreatedAt.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            txtCreatedAt.CharacterCasing = CharacterCasing.Normal;
            txtCreatedAt.DefaultFont = new Font("Microsoft Sans Serif", 9F, FontStyle.Bold);
            txtCreatedAt.DefaultText = "";
            txtCreatedAt.Enabled = false;
            txtCreatedAt.FillColor = Color.White;
            txtCreatedAt.HideSelection = true;
            txtCreatedAt.IconLeft = null;
            txtCreatedAt.IconLeftCursor = Cursors.IBeam;
            txtCreatedAt.IconPadding = 10;
            txtCreatedAt.IconRight = null;
            txtCreatedAt.IconRightCursor = Cursors.IBeam;
            txtCreatedAt.Location = new Point(165, 445);
            txtCreatedAt.MaxLength = 32767;
            txtCreatedAt.MinimumSize = new Size(1, 1);
            txtCreatedAt.Modified = false;
            txtCreatedAt.Multiline = false;
            txtCreatedAt.Name = "txtCreatedAt";
            stateProperties25.BorderColor = Color.DarkGoldenrod;
            stateProperties25.FillColor = Color.Empty;
            stateProperties25.ForeColor = Color.Empty;
            stateProperties25.PlaceholderForeColor = Color.Empty;
            txtCreatedAt.OnActiveState = stateProperties25;
            stateProperties26.BorderColor = Color.FromArgb(204, 204, 204);
            stateProperties26.FillColor = Color.FromArgb(240, 240, 240);
            stateProperties26.ForeColor = Color.FromArgb(109, 109, 109);
            stateProperties26.PlaceholderForeColor = Color.DarkGray;
            txtCreatedAt.OnDisabledState = stateProperties26;
            stateProperties27.BorderColor = Color.DarkGoldenrod;
            stateProperties27.FillColor = Color.Empty;
            stateProperties27.ForeColor = Color.Empty;
            stateProperties27.PlaceholderForeColor = Color.Empty;
            txtCreatedAt.OnHoverState = stateProperties27;
            stateProperties28.BorderColor = Color.Silver;
            stateProperties28.FillColor = Color.White;
            stateProperties28.ForeColor = Color.Empty;
            stateProperties28.PlaceholderForeColor = Color.Empty;
            txtCreatedAt.OnIdleState = stateProperties28;
            txtCreatedAt.Padding = new Padding(3);
            txtCreatedAt.PasswordChar = '\0';
            txtCreatedAt.PlaceholderForeColor = Color.Silver;
            txtCreatedAt.PlaceholderText = "Enter text";
            txtCreatedAt.ReadOnly = true;
            txtCreatedAt.ScrollBars = ScrollBars.None;
            txtCreatedAt.SelectedText = "";
            txtCreatedAt.SelectionLength = 0;
            txtCreatedAt.SelectionStart = 0;
            txtCreatedAt.ShortcutsEnabled = true;
            txtCreatedAt.Size = new Size(271, 36);
            txtCreatedAt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            txtCreatedAt.TabIndex = 132;
            txtCreatedAt.TextAlign = HorizontalAlignment.Left;
            txtCreatedAt.TextMarginBottom = 0;
            txtCreatedAt.TextMarginLeft = 3;
            txtCreatedAt.TextMarginTop = 1;
            txtCreatedAt.TextPlaceholder = "Enter text";
            txtCreatedAt.UseSystemPasswordChar = false;
            txtCreatedAt.WordWrap = true;
            // 
            // label7
            // 
            label7.AutoSize = true;
            label7.Font = new Font("Sitka Text", 14.2499981F);
            label7.Location = new Point(12, 445);
            label7.Name = "label7";
            label7.Size = new Size(81, 28);
            label7.TabIndex = 131;
            label7.Text = "Created";
            // 
            // txtModifiedAt
            // 
            txtModifiedAt.AcceptsReturn = false;
            txtModifiedAt.AcceptsTab = false;
            txtModifiedAt.AnimationSpeed = 200;
            txtModifiedAt.AutoCompleteMode = AutoCompleteMode.None;
            txtModifiedAt.AutoCompleteSource = AutoCompleteSource.None;
            txtModifiedAt.AutoSizeHeight = true;
            txtModifiedAt.BackColor = Color.Transparent;
            txtModifiedAt.BackgroundImage = (Image)resources.GetObject("txtModifiedAt.BackgroundImage");
            txtModifiedAt.BorderColorActive = Color.DarkGoldenrod;
            txtModifiedAt.BorderColorDisabled = Color.FromArgb(204, 204, 204);
            txtModifiedAt.BorderColorHover = Color.DarkGoldenrod;
            txtModifiedAt.BorderColorIdle = Color.Silver;
            txtModifiedAt.BorderRadius = 35;
            txtModifiedAt.BorderThickness = 1;
            txtModifiedAt.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            txtModifiedAt.CharacterCasing = CharacterCasing.Normal;
            txtModifiedAt.DefaultFont = new Font("Microsoft Sans Serif", 9F, FontStyle.Bold);
            txtModifiedAt.DefaultText = "";
            txtModifiedAt.Enabled = false;
            txtModifiedAt.FillColor = Color.White;
            txtModifiedAt.HideSelection = true;
            txtModifiedAt.IconLeft = null;
            txtModifiedAt.IconLeftCursor = Cursors.IBeam;
            txtModifiedAt.IconPadding = 10;
            txtModifiedAt.IconRight = null;
            txtModifiedAt.IconRightCursor = Cursors.IBeam;
            txtModifiedAt.Location = new Point(165, 495);
            txtModifiedAt.MaxLength = 32767;
            txtModifiedAt.MinimumSize = new Size(1, 1);
            txtModifiedAt.Modified = false;
            txtModifiedAt.Multiline = false;
            txtModifiedAt.Name = "txtModifiedAt";
            stateProperties29.BorderColor = Color.DarkGoldenrod;
            stateProperties29.FillColor = Color.Empty;
            stateProperties29.ForeColor = Color.Empty;
            stateProperties29.PlaceholderForeColor = Color.Empty;
            txtModifiedAt.OnActiveState = stateProperties29;
            stateProperties30.BorderColor = Color.FromArgb(204, 204, 204);
            stateProperties30.FillColor = Color.FromArgb(240, 240, 240);
            stateProperties30.ForeColor = Color.FromArgb(109, 109, 109);
            stateProperties30.PlaceholderForeColor = Color.DarkGray;
            txtModifiedAt.OnDisabledState = stateProperties30;
            stateProperties31.BorderColor = Color.DarkGoldenrod;
            stateProperties31.FillColor = Color.Empty;
            stateProperties31.ForeColor = Color.Empty;
            stateProperties31.PlaceholderForeColor = Color.Empty;
            txtModifiedAt.OnHoverState = stateProperties31;
            stateProperties32.BorderColor = Color.Silver;
            stateProperties32.FillColor = Color.White;
            stateProperties32.ForeColor = Color.Empty;
            stateProperties32.PlaceholderForeColor = Color.Empty;
            txtModifiedAt.OnIdleState = stateProperties32;
            txtModifiedAt.Padding = new Padding(3);
            txtModifiedAt.PasswordChar = '\0';
            txtModifiedAt.PlaceholderForeColor = Color.Silver;
            txtModifiedAt.PlaceholderText = "Enter text";
            txtModifiedAt.ReadOnly = true;
            txtModifiedAt.ScrollBars = ScrollBars.None;
            txtModifiedAt.SelectedText = "";
            txtModifiedAt.SelectionLength = 0;
            txtModifiedAt.SelectionStart = 0;
            txtModifiedAt.ShortcutsEnabled = true;
            txtModifiedAt.Size = new Size(271, 36);
            txtModifiedAt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            txtModifiedAt.TabIndex = 134;
            txtModifiedAt.TextAlign = HorizontalAlignment.Left;
            txtModifiedAt.TextMarginBottom = 0;
            txtModifiedAt.TextMarginLeft = 3;
            txtModifiedAt.TextMarginTop = 1;
            txtModifiedAt.TextPlaceholder = "Enter text";
            txtModifiedAt.UseSystemPasswordChar = false;
            txtModifiedAt.WordWrap = true;
            // 
            // label8
            // 
            label8.AutoSize = true;
            label8.Font = new Font("Sitka Text", 14.2499981F);
            label8.Location = new Point(12, 495);
            label8.Name = "label8";
            label8.Size = new Size(91, 28);
            label8.TabIndex = 133;
            label8.Text = "Modified";
            // 
            // btnSelectPicture
            // 
            btnSelectPicture.AllowAnimations = true;
            btnSelectPicture.AllowMouseEffects = true;
            btnSelectPicture.AllowToggling = false;
            btnSelectPicture.AnimationSpeed = 200;
            btnSelectPicture.AutoGenerateColors = false;
            btnSelectPicture.AutoRoundBorders = true;
            btnSelectPicture.AutoSizeLeftIcon = true;
            btnSelectPicture.AutoSizeRightIcon = true;
            btnSelectPicture.BackColor = Color.Transparent;
            btnSelectPicture.BackColor1 = Color.FromArgb(51, 122, 183);
            btnSelectPicture.BackgroundImage = (Image)resources.GetObject("btnSelectPicture.BackgroundImage");
            btnSelectPicture.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            btnSelectPicture.ButtonText = "Input Image";
            btnSelectPicture.ButtonTextMarginLeft = 0;
            btnSelectPicture.ColorContrastOnClick = 45;
            btnSelectPicture.ColorContrastOnHover = 45;
            borderEdges7.BottomLeft = true;
            borderEdges7.BottomRight = true;
            borderEdges7.TopLeft = true;
            borderEdges7.TopRight = true;
            btnSelectPicture.CustomizableEdges = borderEdges7;
            btnSelectPicture.DialogResult = DialogResult.None;
            btnSelectPicture.DisabledBorderColor = Color.FromArgb(191, 191, 191);
            btnSelectPicture.DisabledFillColor = Color.Empty;
            btnSelectPicture.DisabledForecolor = Color.Empty;
            btnSelectPicture.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            btnSelectPicture.Font = new Font("Sitka Text", 9F, FontStyle.Regular, GraphicsUnit.Point, 0);
            btnSelectPicture.ForeColor = SystemColors.ActiveCaptionText;
            btnSelectPicture.IconLeft = null;
            btnSelectPicture.IconLeftAlign = ContentAlignment.MiddleLeft;
            btnSelectPicture.IconLeftCursor = Cursors.Default;
            btnSelectPicture.IconLeftPadding = new Padding(11, 3, 3, 3);
            btnSelectPicture.IconMarginLeft = 11;
            btnSelectPicture.IconPadding = 10;
            btnSelectPicture.IconRight = null;
            btnSelectPicture.IconRightAlign = ContentAlignment.MiddleRight;
            btnSelectPicture.IconRightCursor = Cursors.Default;
            btnSelectPicture.IconRightPadding = new Padding(3, 3, 7, 3);
            btnSelectPicture.IconSize = 25;
            btnSelectPicture.IdleBorderColor = Color.Empty;
            btnSelectPicture.IdleBorderRadius = 0;
            btnSelectPicture.IdleBorderThickness = 0;
            btnSelectPicture.IdleFillColor = Color.Empty;
            btnSelectPicture.IdleIconLeftImage = null;
            btnSelectPicture.IdleIconRightImage = null;
            btnSelectPicture.IndicateFocus = false;
            btnSelectPicture.Location = new Point(12, 601);
            btnSelectPicture.Name = "btnSelectPicture";
            btnSelectPicture.OnDisabledState.BorderColor = Color.FromArgb(191, 191, 191);
            btnSelectPicture.OnDisabledState.BorderRadius = 34;
            btnSelectPicture.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            btnSelectPicture.OnDisabledState.BorderThickness = 1;
            btnSelectPicture.OnDisabledState.FillColor = Color.FromArgb(204, 204, 204);
            btnSelectPicture.OnDisabledState.ForeColor = Color.FromArgb(168, 160, 168);
            btnSelectPicture.OnDisabledState.IconLeftImage = null;
            btnSelectPicture.OnDisabledState.IconRightImage = null;
            btnSelectPicture.onHoverState.BorderColor = Color.FromArgb(30, 150, 255);
            btnSelectPicture.onHoverState.BorderRadius = 34;
            btnSelectPicture.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            btnSelectPicture.onHoverState.BorderThickness = 1;
            btnSelectPicture.onHoverState.FillColor = Color.Gray;
            btnSelectPicture.onHoverState.ForeColor = Color.White;
            btnSelectPicture.onHoverState.IconLeftImage = null;
            btnSelectPicture.onHoverState.IconRightImage = null;
            btnSelectPicture.OnIdleState.BorderColor = SystemColors.ActiveCaptionText;
            btnSelectPicture.OnIdleState.BorderRadius = 34;
            btnSelectPicture.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            btnSelectPicture.OnIdleState.BorderThickness = 1;
            btnSelectPicture.OnIdleState.FillColor = SystemColors.AppWorkspace;
            btnSelectPicture.OnIdleState.ForeColor = SystemColors.ActiveCaptionText;
            btnSelectPicture.OnIdleState.IconLeftImage = null;
            btnSelectPicture.OnIdleState.IconRightImage = null;
            btnSelectPicture.OnPressedState.BorderColor = Color.FromArgb(40, 96, 144);
            btnSelectPicture.OnPressedState.BorderRadius = 34;
            btnSelectPicture.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            btnSelectPicture.OnPressedState.BorderThickness = 1;
            btnSelectPicture.OnPressedState.FillColor = Color.FromArgb(40, 96, 144);
            btnSelectPicture.OnPressedState.ForeColor = Color.White;
            btnSelectPicture.OnPressedState.IconLeftImage = null;
            btnSelectPicture.OnPressedState.IconRightImage = null;
            btnSelectPicture.Size = new Size(115, 34);
            btnSelectPicture.TabIndex = 135;
            btnSelectPicture.TextAlign = ContentAlignment.MiddleCenter;
            btnSelectPicture.TextAlignment = HorizontalAlignment.Center;
            btnSelectPicture.TextMarginLeft = 0;
            btnSelectPicture.TextPadding = new Padding(0);
            btnSelectPicture.UseDefaultRadiusAndThickness = true;
            // 
            // picConsumable
            // 
            picConsumable.BorderStyle = BorderStyle.FixedSingle;
            picConsumable.Location = new Point(165, 554);
            picConsumable.Name = "picConsumable";
            picConsumable.Size = new Size(271, 141);
            picConsumable.TabIndex = 136;
            picConsumable.TabStop = false;
            // 
            // bunifuFormDock1
            // 
            bunifuFormDock1.AllowFormDragging = true;
            bunifuFormDock1.AllowFormDropShadow = true;
            bunifuFormDock1.AllowFormResizing = true;
            bunifuFormDock1.AllowHidingBottomRegion = true;
            bunifuFormDock1.AllowOpacityChangesWhileDragging = true;
            bunifuFormDock1.BorderOptions.BottomBorder.BorderColor = Color.Silver;
            bunifuFormDock1.BorderOptions.BottomBorder.BorderThickness = 1;
            bunifuFormDock1.BorderOptions.BottomBorder.ShowBorder = true;
            bunifuFormDock1.BorderOptions.LeftBorder.BorderColor = Color.Silver;
            bunifuFormDock1.BorderOptions.LeftBorder.BorderThickness = 1;
            bunifuFormDock1.BorderOptions.LeftBorder.ShowBorder = true;
            bunifuFormDock1.BorderOptions.RightBorder.BorderColor = Color.Silver;
            bunifuFormDock1.BorderOptions.RightBorder.BorderThickness = 1;
            bunifuFormDock1.BorderOptions.RightBorder.ShowBorder = true;
            bunifuFormDock1.BorderOptions.TopBorder.BorderColor = Color.Silver;
            bunifuFormDock1.BorderOptions.TopBorder.BorderThickness = 1;
            bunifuFormDock1.BorderOptions.TopBorder.ShowBorder = true;
            bunifuFormDock1.ContainerControl = this;
            bunifuFormDock1.DockingIndicatorsColor = Color.FromArgb(202, 215, 233);
            bunifuFormDock1.DockingIndicatorsOpacity = 0.5D;
            bunifuFormDock1.DockingOptions.DockAll = true;
            bunifuFormDock1.DockingOptions.DockBottomLeft = true;
            bunifuFormDock1.DockingOptions.DockBottomRight = true;
            bunifuFormDock1.DockingOptions.DockFullScreen = true;
            bunifuFormDock1.DockingOptions.DockLeft = true;
            bunifuFormDock1.DockingOptions.DockRight = true;
            bunifuFormDock1.DockingOptions.DockTopLeft = true;
            bunifuFormDock1.DockingOptions.DockTopRight = true;
            bunifuFormDock1.FormDraggingOpacity = 0.9D;
            bunifuFormDock1.ParentForm = this;
            bunifuFormDock1.ShowCursorChanges = true;
            bunifuFormDock1.ShowDockingIndicators = true;
            bunifuFormDock1.TitleBarOptions.AllowFormDragging = true;
            bunifuFormDock1.TitleBarOptions.BunifuFormDock = bunifuFormDock1;
            bunifuFormDock1.TitleBarOptions.DoubleClickToExpandWindow = true;
            bunifuFormDock1.TitleBarOptions.TitleBarControl = null;
            bunifuFormDock1.TitleBarOptions.UseBackColorOnDockingIndicators = false;
            // 
            // Consumable
            // 
            AutoScaleDimensions = new SizeF(7F, 15F);
            AutoScaleMode = AutoScaleMode.Font;
            ClientSize = new Size(1176, 700);
            Controls.Add(picConsumable);
            Controls.Add(btnSelectPicture);
            Controls.Add(txtModifiedAt);
            Controls.Add(label8);
            Controls.Add(txtCreatedAt);
            Controls.Add(label7);
            Controls.Add(txtDescription);
            Controls.Add(label6);
            Controls.Add(txtQuantity);
            Controls.Add(label5);
            Controls.Add(txtPrice);
            Controls.Add(label3);
            Controls.Add(txtName);
            Controls.Add(label2);
            Controls.Add(cboCategory);
            Controls.Add(label4);
            Controls.Add(txtID);
            Controls.Add(label1);
            Controls.Add(dgvConsumable);
            Controls.Add(btnClear);
            Controls.Add(btnDelete);
            Controls.Add(btnUpdate);
            Controls.Add(btnInsert);
            Controls.Add(btnNew);
            Controls.Add(txtSearch);
            Controls.Add(bunifuPanel2);
            FormBorderStyle = FormBorderStyle.None;
            Name = "Consumable";
            StartPosition = FormStartPosition.CenterScreen;
            Text = "Consumable Management";
            Load += Consumable_Load;
            bunifuPanel2.ResumeLayout(false);
            bunifuPanel2.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)dgvConsumable).EndInit();
            ((System.ComponentModel.ISupportInitialize)picConsumable).EndInit();
            ResumeLayout(false);
            PerformLayout();
        }

        #endregion
        //private TextBox txtID;
        //private TextBox txtName;
        //private TextBox txtPrice;
        //private TextBox txtCategory;
        //private TextBox txtQuantity;
        //private TextBox txtDescription;
        //private TextBox txtCreatedAt;
        private Label label9;
        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel2;
        private Label label11;
        private Bunifu.UI.WinForms.BunifuButton.BunifuIconButton btnExitProgram;
        private Bunifu.UI.WinForms.BunifuTextBox txtSearch;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnClear;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnDelete;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnUpdate;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnInsert;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnNew;
        private Bunifu.UI.WinForms.BunifuDataGridView dgvConsumable;
        private Bunifu.UI.WinForms.BunifuTextBox txtID;
        private Label label1;
        private Bunifu.UI.WinForms.BunifuDropdown cboCategory;
        private Label label4;
        private Bunifu.UI.WinForms.BunifuTextBox txtName;
        private Label label2;
        private Bunifu.UI.WinForms.BunifuTextBox txtPrice;
        private Label label3;
        private Bunifu.UI.WinForms.BunifuTextBox txtQuantity;
        private Label label5;
        private Bunifu.UI.WinForms.BunifuTextBox txtDescription;
        private Label label6;
        private Bunifu.UI.WinForms.BunifuTextBox txtCreatedAt;
        private Label label7;
        private Bunifu.UI.WinForms.BunifuTextBox txtModifiedAt;
        private Label label8;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnSelectPicture;
        private PictureBox picConsumable;
        private Bunifu.UI.WinForms.BunifuFormDock bunifuFormDock1;
    }
}
