namespace Spa_Management_System
{
    partial class Customer
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Customer));
            Bunifu.UI.WinForms.BunifuButton.BunifuIconButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuIconButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            DataGridViewCellStyle dataGridViewCellStyle1 = new DataGridViewCellStyle();
            DataGridViewCellStyle dataGridViewCellStyle2 = new DataGridViewCellStyle();
            DataGridViewCellStyle dataGridViewCellStyle3 = new DataGridViewCellStyle();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            bunifuPanel2 = new Bunifu.UI.WinForms.BunifuPanel();
            label11 = new Label();
            btnExitProgram = new Bunifu.UI.WinForms.BunifuButton.BunifuIconButton();
            txtSearch = new Bunifu.UI.WinForms.BunifuTextBox();
            btnClear = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            btnUpdate = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            btnInsert = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            btnNew = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            dgvCustomer = new Bunifu.UI.WinForms.BunifuDataGridView();
            txtID = new Bunifu.UI.WinForms.BunifuTextBox();
            label1 = new Label();
            txtCustomerID = new Bunifu.UI.WinForms.BunifuTextBox();
            label2 = new Label();
            txtIssuedTime = new Bunifu.UI.WinForms.BunifuTextBox();
            label3 = new Label();
            txtNote = new Bunifu.UI.WinForms.BunifuTextBox();
            label4 = new Label();
            bunifuFormDock1 = new Bunifu.UI.WinForms.BunifuFormDock();
            btnSetDamaged = new Button();
            bunifuPanel2.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)dgvCustomer).BeginInit();
            SuspendLayout();
            // 
            // bunifuPanel2
            // 
            bunifuPanel2.BackgroundColor = Color.White;
            bunifuPanel2.BackgroundImage = (Image)resources.GetObject("bunifuPanel2.BackgroundImage");
            bunifuPanel2.BackgroundImageLayout = ImageLayout.Stretch;
            bunifuPanel2.BorderColor = Color.Transparent;
            bunifuPanel2.BorderRadius = 3;
            bunifuPanel2.BorderThickness = 1;
            bunifuPanel2.Controls.Add(label11);
            bunifuPanel2.Controls.Add(btnExitProgram);
            bunifuPanel2.Dock = DockStyle.Top;
            bunifuPanel2.Location = new Point(0, 0);
            bunifuPanel2.Name = "bunifuPanel2";
            bunifuPanel2.ShowBorders = true;
            bunifuPanel2.Size = new Size(1148, 65);
            bunifuPanel2.TabIndex = 92;
            // 
            // label11
            // 
            label11.AutoSize = true;
            label11.BackColor = Color.Transparent;
            label11.Font = new Font("Microsoft Sans Serif", 14.25F, FontStyle.Bold, GraphicsUnit.Point, 0);
            label11.Location = new Point(474, 15);
            label11.Name = "label11";
            label11.Size = new Size(181, 24);
            label11.TabIndex = 74;
            label11.Text = "Card Management";
            // 
            // btnExitProgram
            // 
            btnExitProgram.AllowAnimations = true;
            btnExitProgram.AllowBorderColorChanges = true;
            btnExitProgram.AllowMouseEffects = true;
            btnExitProgram.AnimationSpeed = 200;
            btnExitProgram.BackColor = Color.Transparent;
            btnExitProgram.BackgroundColor = Color.Transparent;
            btnExitProgram.BorderColor = Color.Transparent;
            btnExitProgram.BorderRadius = 1;
            btnExitProgram.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuIconButton.BorderStyles.Solid;
            btnExitProgram.BorderThickness = 1;
            btnExitProgram.ColorContrastOnClick = 30;
            btnExitProgram.ColorContrastOnHover = -30;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            btnExitProgram.CustomizableEdges = borderEdges1;
            btnExitProgram.DialogResult = DialogResult.None;
            btnExitProgram.Image = (Image)resources.GetObject("btnExitProgram.Image");
            btnExitProgram.ImageMargin = new Padding(0);
            btnExitProgram.Location = new Point(1113, 13);
            btnExitProgram.Name = "btnExitProgram";
            btnExitProgram.RoundBorders = true;
            btnExitProgram.ShowBorders = true;
            btnExitProgram.Size = new Size(26, 26);
            btnExitProgram.Style = Bunifu.UI.WinForms.BunifuButton.BunifuIconButton.ButtonStyles.Round;
            btnExitProgram.TabIndex = 69;
            // 
            // txtSearch
            // 
            txtSearch.AcceptsReturn = false;
            txtSearch.AcceptsTab = false;
            txtSearch.AnimationSpeed = 200;
            txtSearch.AutoCompleteMode = AutoCompleteMode.None;
            txtSearch.AutoCompleteSource = AutoCompleteSource.None;
            txtSearch.AutoSizeHeight = true;
            txtSearch.BackColor = Color.Transparent;
            txtSearch.BackgroundImage = (Image)resources.GetObject("txtSearch.BackgroundImage");
            txtSearch.BorderColorActive = Color.DarkGoldenrod;
            txtSearch.BorderColorDisabled = Color.FromArgb(204, 204, 204);
            txtSearch.BorderColorHover = Color.DarkGoldenrod;
            txtSearch.BorderColorIdle = Color.Silver;
            txtSearch.BorderRadius = 35;
            txtSearch.BorderThickness = 1;
            txtSearch.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            txtSearch.CharacterCasing = CharacterCasing.Normal;
            txtSearch.DefaultFont = new Font("Microsoft Sans Serif", 9F, FontStyle.Regular, GraphicsUnit.Point, 0);
            txtSearch.DefaultText = "";
            txtSearch.FillColor = Color.White;
            txtSearch.HideSelection = true;
            txtSearch.IconLeft = null;
            txtSearch.IconLeftCursor = Cursors.IBeam;
            txtSearch.IconPadding = 10;
            txtSearch.IconRight = null;
            txtSearch.IconRightCursor = Cursors.IBeam;
            txtSearch.Location = new Point(474, 81);
            txtSearch.MaxLength = 32767;
            txtSearch.MinimumSize = new Size(1, 1);
            txtSearch.Modified = false;
            txtSearch.Multiline = false;
            txtSearch.Name = "txtSearch";
            stateProperties1.BorderColor = Color.DarkGoldenrod;
            stateProperties1.FillColor = Color.Empty;
            stateProperties1.ForeColor = Color.Empty;
            stateProperties1.PlaceholderForeColor = Color.Empty;
            txtSearch.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = Color.FromArgb(204, 204, 204);
            stateProperties2.FillColor = Color.FromArgb(240, 240, 240);
            stateProperties2.ForeColor = Color.FromArgb(109, 109, 109);
            stateProperties2.PlaceholderForeColor = Color.DarkGray;
            txtSearch.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = Color.DarkGoldenrod;
            stateProperties3.FillColor = Color.Empty;
            stateProperties3.ForeColor = Color.Empty;
            stateProperties3.PlaceholderForeColor = Color.Empty;
            txtSearch.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = Color.Silver;
            stateProperties4.FillColor = Color.White;
            stateProperties4.ForeColor = Color.Empty;
            stateProperties4.PlaceholderForeColor = Color.Empty;
            txtSearch.OnIdleState = stateProperties4;
            txtSearch.Padding = new Padding(3);
            txtSearch.PasswordChar = '\0';
            txtSearch.PlaceholderForeColor = Color.Silver;
            txtSearch.PlaceholderText = "Search ...";
            txtSearch.ReadOnly = false;
            txtSearch.ScrollBars = ScrollBars.None;
            txtSearch.SelectedText = "";
            txtSearch.SelectionLength = 0;
            txtSearch.SelectionStart = 0;
            txtSearch.ShortcutsEnabled = true;
            txtSearch.Size = new Size(661, 44);
            txtSearch.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            txtSearch.TabIndex = 113;
            txtSearch.TextAlign = HorizontalAlignment.Left;
            txtSearch.TextMarginBottom = 0;
            txtSearch.TextMarginLeft = 3;
            txtSearch.TextMarginTop = 1;
            txtSearch.TextPlaceholder = "Search ...";
            txtSearch.UseSystemPasswordChar = false;
            txtSearch.WordWrap = true;
            // 
            // btnClear
            // 
            btnClear.AllowAnimations = true;
            btnClear.AllowMouseEffects = true;
            btnClear.AllowToggling = false;
            btnClear.AnimationSpeed = 200;
            btnClear.AutoGenerateColors = false;
            btnClear.AutoRoundBorders = false;
            btnClear.AutoSizeLeftIcon = true;
            btnClear.AutoSizeRightIcon = true;
            btnClear.BackColor = Color.Transparent;
            btnClear.BackColor1 = Color.White;
            btnClear.BackgroundImage = (Image)resources.GetObject("btnClear.BackgroundImage");
            btnClear.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnClear.ButtonText = "Clear";
            btnClear.ButtonTextMarginLeft = 0;
            btnClear.ColorContrastOnClick = 45;
            btnClear.ColorContrastOnHover = 45;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            btnClear.CustomizableEdges = borderEdges2;
            btnClear.DialogResult = DialogResult.None;
            btnClear.DisabledBorderColor = Color.FromArgb(191, 191, 191);
            btnClear.DisabledFillColor = Color.FromArgb(204, 204, 204);
            btnClear.DisabledForecolor = Color.FromArgb(168, 160, 168);
            btnClear.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            btnClear.Font = new Font("Sitka Text", 9F);
            btnClear.ForeColor = Color.Black;
            btnClear.IconLeftAlign = ContentAlignment.MiddleLeft;
            btnClear.IconLeftCursor = Cursors.Default;
            btnClear.IconLeftPadding = new Padding(11, 3, 3, 3);
            btnClear.IconMarginLeft = 11;
            btnClear.IconPadding = 10;
            btnClear.IconRightAlign = ContentAlignment.MiddleRight;
            btnClear.IconRightCursor = Cursors.Default;
            btnClear.IconRightPadding = new Padding(3, 3, 7, 3);
            btnClear.IconSize = 25;
            btnClear.IdleBorderColor = Color.White;
            btnClear.IdleBorderRadius = 35;
            btnClear.IdleBorderThickness = 1;
            btnClear.IdleFillColor = Color.White;
            btnClear.IdleIconLeftImage = null;
            btnClear.IdleIconRightImage = null;
            btnClear.IndicateFocus = false;
            btnClear.Location = new Point(271, 77);
            btnClear.Name = "btnClear";
            btnClear.OnDisabledState.BorderColor = Color.FromArgb(191, 191, 191);
            btnClear.OnDisabledState.BorderRadius = 35;
            btnClear.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnClear.OnDisabledState.BorderThickness = 1;
            btnClear.OnDisabledState.FillColor = Color.FromArgb(204, 204, 204);
            btnClear.OnDisabledState.ForeColor = Color.FromArgb(168, 160, 168);
            btnClear.OnDisabledState.IconLeftImage = null;
            btnClear.OnDisabledState.IconRightImage = null;
            btnClear.onHoverState.BorderColor = Color.DarkGoldenrod;
            btnClear.onHoverState.BorderRadius = 35;
            btnClear.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnClear.onHoverState.BorderThickness = 1;
            btnClear.onHoverState.FillColor = Color.White;
            btnClear.onHoverState.ForeColor = Color.Black;
            btnClear.onHoverState.IconLeftImage = null;
            btnClear.onHoverState.IconRightImage = null;
            btnClear.OnIdleState.BorderColor = Color.White;
            btnClear.OnIdleState.BorderRadius = 35;
            btnClear.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnClear.OnIdleState.BorderThickness = 1;
            btnClear.OnIdleState.FillColor = Color.White;
            btnClear.OnIdleState.ForeColor = Color.Black;
            btnClear.OnIdleState.IconLeftImage = null;
            btnClear.OnIdleState.IconRightImage = null;
            btnClear.OnPressedState.BorderColor = Color.FromArgb(40, 96, 144);
            btnClear.OnPressedState.BorderRadius = 35;
            btnClear.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnClear.OnPressedState.BorderThickness = 1;
            btnClear.OnPressedState.FillColor = Color.FromArgb(40, 96, 144);
            btnClear.OnPressedState.ForeColor = Color.White;
            btnClear.OnPressedState.IconLeftImage = null;
            btnClear.OnPressedState.IconRightImage = null;
            btnClear.Size = new Size(80, 39);
            btnClear.TabIndex = 122;
            btnClear.TextAlign = ContentAlignment.MiddleCenter;
            btnClear.TextAlignment = HorizontalAlignment.Center;
            btnClear.TextMarginLeft = 0;
            btnClear.TextPadding = new Padding(0);
            btnClear.UseDefaultRadiusAndThickness = true;
            // 
            // btnUpdate
            // 
            btnUpdate.AllowAnimations = true;
            btnUpdate.AllowMouseEffects = true;
            btnUpdate.AllowToggling = false;
            btnUpdate.AnimationSpeed = 200;
            btnUpdate.AutoGenerateColors = false;
            btnUpdate.AutoRoundBorders = false;
            btnUpdate.AutoSizeLeftIcon = true;
            btnUpdate.AutoSizeRightIcon = true;
            btnUpdate.BackColor = Color.Transparent;
            btnUpdate.BackColor1 = Color.White;
            btnUpdate.BackgroundImage = (Image)resources.GetObject("btnUpdate.BackgroundImage");
            btnUpdate.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnUpdate.ButtonText = "Update";
            btnUpdate.ButtonTextMarginLeft = 0;
            btnUpdate.ColorContrastOnClick = 45;
            btnUpdate.ColorContrastOnHover = 45;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            btnUpdate.CustomizableEdges = borderEdges3;
            btnUpdate.DialogResult = DialogResult.None;
            btnUpdate.DisabledBorderColor = Color.FromArgb(191, 191, 191);
            btnUpdate.DisabledFillColor = Color.FromArgb(204, 204, 204);
            btnUpdate.DisabledForecolor = Color.FromArgb(168, 160, 168);
            btnUpdate.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            btnUpdate.Font = new Font("Sitka Text", 9F);
            btnUpdate.ForeColor = Color.Black;
            btnUpdate.IconLeftAlign = ContentAlignment.MiddleLeft;
            btnUpdate.IconLeftCursor = Cursors.Default;
            btnUpdate.IconLeftPadding = new Padding(11, 3, 3, 3);
            btnUpdate.IconMarginLeft = 11;
            btnUpdate.IconPadding = 10;
            btnUpdate.IconRightAlign = ContentAlignment.MiddleRight;
            btnUpdate.IconRightCursor = Cursors.Default;
            btnUpdate.IconRightPadding = new Padding(3, 3, 7, 3);
            btnUpdate.IconSize = 25;
            btnUpdate.IdleBorderColor = Color.White;
            btnUpdate.IdleBorderRadius = 35;
            btnUpdate.IdleBorderThickness = 1;
            btnUpdate.IdleFillColor = Color.White;
            btnUpdate.IdleIconLeftImage = null;
            btnUpdate.IdleIconRightImage = null;
            btnUpdate.IndicateFocus = false;
            btnUpdate.Location = new Point(185, 77);
            btnUpdate.Name = "btnUpdate";
            btnUpdate.OnDisabledState.BorderColor = Color.FromArgb(191, 191, 191);
            btnUpdate.OnDisabledState.BorderRadius = 35;
            btnUpdate.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnUpdate.OnDisabledState.BorderThickness = 1;
            btnUpdate.OnDisabledState.FillColor = Color.FromArgb(204, 204, 204);
            btnUpdate.OnDisabledState.ForeColor = Color.FromArgb(168, 160, 168);
            btnUpdate.OnDisabledState.IconLeftImage = null;
            btnUpdate.OnDisabledState.IconRightImage = null;
            btnUpdate.onHoverState.BorderColor = Color.DarkGoldenrod;
            btnUpdate.onHoverState.BorderRadius = 35;
            btnUpdate.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnUpdate.onHoverState.BorderThickness = 1;
            btnUpdate.onHoverState.FillColor = Color.White;
            btnUpdate.onHoverState.ForeColor = Color.Black;
            btnUpdate.onHoverState.IconLeftImage = null;
            btnUpdate.onHoverState.IconRightImage = null;
            btnUpdate.OnIdleState.BorderColor = Color.White;
            btnUpdate.OnIdleState.BorderRadius = 35;
            btnUpdate.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnUpdate.OnIdleState.BorderThickness = 1;
            btnUpdate.OnIdleState.FillColor = Color.White;
            btnUpdate.OnIdleState.ForeColor = Color.Black;
            btnUpdate.OnIdleState.IconLeftImage = null;
            btnUpdate.OnIdleState.IconRightImage = null;
            btnUpdate.OnPressedState.BorderColor = Color.FromArgb(40, 96, 144);
            btnUpdate.OnPressedState.BorderRadius = 35;
            btnUpdate.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnUpdate.OnPressedState.BorderThickness = 1;
            btnUpdate.OnPressedState.FillColor = Color.FromArgb(40, 96, 144);
            btnUpdate.OnPressedState.ForeColor = Color.White;
            btnUpdate.OnPressedState.IconLeftImage = null;
            btnUpdate.OnPressedState.IconRightImage = null;
            btnUpdate.Size = new Size(80, 39);
            btnUpdate.TabIndex = 120;
            btnUpdate.TextAlign = ContentAlignment.MiddleCenter;
            btnUpdate.TextAlignment = HorizontalAlignment.Center;
            btnUpdate.TextMarginLeft = 0;
            btnUpdate.TextPadding = new Padding(0);
            btnUpdate.UseDefaultRadiusAndThickness = true;
            // 
            // btnInsert
            // 
            btnInsert.AllowAnimations = true;
            btnInsert.AllowMouseEffects = true;
            btnInsert.AllowToggling = false;
            btnInsert.AnimationSpeed = 200;
            btnInsert.AutoGenerateColors = false;
            btnInsert.AutoRoundBorders = false;
            btnInsert.AutoSizeLeftIcon = true;
            btnInsert.AutoSizeRightIcon = true;
            btnInsert.BackColor = Color.Transparent;
            btnInsert.BackColor1 = Color.White;
            btnInsert.BackgroundImage = (Image)resources.GetObject("btnInsert.BackgroundImage");
            btnInsert.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnInsert.ButtonText = "Insert";
            btnInsert.ButtonTextMarginLeft = 0;
            btnInsert.ColorContrastOnClick = 45;
            btnInsert.ColorContrastOnHover = 45;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            btnInsert.CustomizableEdges = borderEdges4;
            btnInsert.DialogResult = DialogResult.None;
            btnInsert.DisabledBorderColor = Color.FromArgb(191, 191, 191);
            btnInsert.DisabledFillColor = Color.FromArgb(204, 204, 204);
            btnInsert.DisabledForecolor = Color.FromArgb(168, 160, 168);
            btnInsert.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            btnInsert.Font = new Font("Sitka Text", 9F);
            btnInsert.ForeColor = Color.Black;
            btnInsert.IconLeftAlign = ContentAlignment.MiddleLeft;
            btnInsert.IconLeftCursor = Cursors.Default;
            btnInsert.IconLeftPadding = new Padding(11, 3, 3, 3);
            btnInsert.IconMarginLeft = 11;
            btnInsert.IconPadding = 10;
            btnInsert.IconRightAlign = ContentAlignment.MiddleRight;
            btnInsert.IconRightCursor = Cursors.Default;
            btnInsert.IconRightPadding = new Padding(3, 3, 7, 3);
            btnInsert.IconSize = 25;
            btnInsert.IdleBorderColor = Color.White;
            btnInsert.IdleBorderRadius = 35;
            btnInsert.IdleBorderThickness = 1;
            btnInsert.IdleFillColor = Color.White;
            btnInsert.IdleIconLeftImage = null;
            btnInsert.IdleIconRightImage = null;
            btnInsert.IndicateFocus = false;
            btnInsert.Location = new Point(99, 77);
            btnInsert.Name = "btnInsert";
            btnInsert.OnDisabledState.BorderColor = Color.FromArgb(191, 191, 191);
            btnInsert.OnDisabledState.BorderRadius = 35;
            btnInsert.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnInsert.OnDisabledState.BorderThickness = 1;
            btnInsert.OnDisabledState.FillColor = Color.FromArgb(204, 204, 204);
            btnInsert.OnDisabledState.ForeColor = Color.FromArgb(168, 160, 168);
            btnInsert.OnDisabledState.IconLeftImage = null;
            btnInsert.OnDisabledState.IconRightImage = null;
            btnInsert.onHoverState.BorderColor = Color.DarkGoldenrod;
            btnInsert.onHoverState.BorderRadius = 35;
            btnInsert.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnInsert.onHoverState.BorderThickness = 1;
            btnInsert.onHoverState.FillColor = Color.White;
            btnInsert.onHoverState.ForeColor = Color.Black;
            btnInsert.onHoverState.IconLeftImage = null;
            btnInsert.onHoverState.IconRightImage = null;
            btnInsert.OnIdleState.BorderColor = Color.White;
            btnInsert.OnIdleState.BorderRadius = 35;
            btnInsert.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnInsert.OnIdleState.BorderThickness = 1;
            btnInsert.OnIdleState.FillColor = Color.White;
            btnInsert.OnIdleState.ForeColor = Color.Black;
            btnInsert.OnIdleState.IconLeftImage = null;
            btnInsert.OnIdleState.IconRightImage = null;
            btnInsert.OnPressedState.BorderColor = Color.FromArgb(40, 96, 144);
            btnInsert.OnPressedState.BorderRadius = 35;
            btnInsert.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnInsert.OnPressedState.BorderThickness = 1;
            btnInsert.OnPressedState.FillColor = Color.FromArgb(40, 96, 144);
            btnInsert.OnPressedState.ForeColor = Color.White;
            btnInsert.OnPressedState.IconLeftImage = null;
            btnInsert.OnPressedState.IconRightImage = null;
            btnInsert.Size = new Size(80, 39);
            btnInsert.TabIndex = 119;
            btnInsert.TextAlign = ContentAlignment.MiddleCenter;
            btnInsert.TextAlignment = HorizontalAlignment.Center;
            btnInsert.TextMarginLeft = 0;
            btnInsert.TextPadding = new Padding(0);
            btnInsert.UseDefaultRadiusAndThickness = true;
            // 
            // btnNew
            // 
            btnNew.AllowAnimations = true;
            btnNew.AllowMouseEffects = true;
            btnNew.AllowToggling = false;
            btnNew.AnimationSpeed = 200;
            btnNew.AutoGenerateColors = false;
            btnNew.AutoRoundBorders = false;
            btnNew.AutoSizeLeftIcon = true;
            btnNew.AutoSizeRightIcon = true;
            btnNew.BackColor = Color.Transparent;
            btnNew.BackColor1 = Color.White;
            btnNew.BackgroundImage = (Image)resources.GetObject("btnNew.BackgroundImage");
            btnNew.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnNew.ButtonText = "New";
            btnNew.ButtonTextMarginLeft = 0;
            btnNew.ColorContrastOnClick = 45;
            btnNew.ColorContrastOnHover = 45;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            btnNew.CustomizableEdges = borderEdges5;
            btnNew.DialogResult = DialogResult.None;
            btnNew.DisabledBorderColor = Color.FromArgb(191, 191, 191);
            btnNew.DisabledFillColor = Color.FromArgb(204, 204, 204);
            btnNew.DisabledForecolor = Color.FromArgb(168, 160, 168);
            btnNew.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            btnNew.Font = new Font("Sitka Text", 9F);
            btnNew.ForeColor = Color.Black;
            btnNew.IconLeftAlign = ContentAlignment.MiddleLeft;
            btnNew.IconLeftCursor = Cursors.Default;
            btnNew.IconLeftPadding = new Padding(11, 3, 3, 3);
            btnNew.IconMarginLeft = 11;
            btnNew.IconPadding = 10;
            btnNew.IconRightAlign = ContentAlignment.MiddleRight;
            btnNew.IconRightCursor = Cursors.Default;
            btnNew.IconRightPadding = new Padding(3, 3, 7, 3);
            btnNew.IconSize = 25;
            btnNew.IdleBorderColor = Color.White;
            btnNew.IdleBorderRadius = 35;
            btnNew.IdleBorderThickness = 1;
            btnNew.IdleFillColor = Color.White;
            btnNew.IdleIconLeftImage = null;
            btnNew.IdleIconRightImage = null;
            btnNew.IndicateFocus = false;
            btnNew.Location = new Point(13, 77);
            btnNew.Name = "btnNew";
            btnNew.OnDisabledState.BorderColor = Color.FromArgb(191, 191, 191);
            btnNew.OnDisabledState.BorderRadius = 35;
            btnNew.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnNew.OnDisabledState.BorderThickness = 1;
            btnNew.OnDisabledState.FillColor = Color.FromArgb(204, 204, 204);
            btnNew.OnDisabledState.ForeColor = Color.FromArgb(168, 160, 168);
            btnNew.OnDisabledState.IconLeftImage = null;
            btnNew.OnDisabledState.IconRightImage = null;
            btnNew.onHoverState.BorderColor = Color.DarkGoldenrod;
            btnNew.onHoverState.BorderRadius = 35;
            btnNew.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnNew.onHoverState.BorderThickness = 1;
            btnNew.onHoverState.FillColor = Color.White;
            btnNew.onHoverState.ForeColor = Color.Black;
            btnNew.onHoverState.IconLeftImage = null;
            btnNew.onHoverState.IconRightImage = null;
            btnNew.OnIdleState.BorderColor = Color.White;
            btnNew.OnIdleState.BorderRadius = 35;
            btnNew.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnNew.OnIdleState.BorderThickness = 1;
            btnNew.OnIdleState.FillColor = Color.White;
            btnNew.OnIdleState.ForeColor = Color.Black;
            btnNew.OnIdleState.IconLeftImage = null;
            btnNew.OnIdleState.IconRightImage = null;
            btnNew.OnPressedState.BorderColor = Color.FromArgb(40, 96, 144);
            btnNew.OnPressedState.BorderRadius = 35;
            btnNew.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnNew.OnPressedState.BorderThickness = 1;
            btnNew.OnPressedState.FillColor = Color.FromArgb(40, 96, 144);
            btnNew.OnPressedState.ForeColor = Color.White;
            btnNew.OnPressedState.IconLeftImage = null;
            btnNew.OnPressedState.IconRightImage = null;
            btnNew.Size = new Size(80, 39);
            btnNew.TabIndex = 118;
            btnNew.TextAlign = ContentAlignment.MiddleCenter;
            btnNew.TextAlignment = HorizontalAlignment.Center;
            btnNew.TextMarginLeft = 0;
            btnNew.TextPadding = new Padding(0);
            btnNew.UseDefaultRadiusAndThickness = true;
            // 
            // dgvCustomer
            // 
            dgvCustomer.AllowCustomTheming = false;
            dataGridViewCellStyle1.BackColor = Color.FromArgb(255, 232, 191);
            dataGridViewCellStyle1.Font = new Font("Microsoft Sans Serif", 8.25F, FontStyle.Bold, GraphicsUnit.Point, 0);
            dataGridViewCellStyle1.ForeColor = Color.Black;
            dgvCustomer.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle1;
            dgvCustomer.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
            dgvCustomer.BackgroundColor = Color.White;
            dgvCustomer.BorderStyle = BorderStyle.None;
            dgvCustomer.CellBorderStyle = DataGridViewCellBorderStyle.SingleHorizontal;
            dgvCustomer.ColumnHeadersBorderStyle = DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle2.Alignment = DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle2.BackColor = Color.Orange;
            dataGridViewCellStyle2.Font = new Font("Segoe UI Semibold", 11.75F, FontStyle.Bold);
            dataGridViewCellStyle2.ForeColor = Color.White;
            dataGridViewCellStyle2.SelectionBackColor = Color.FromArgb(204, 132, 0);
            dataGridViewCellStyle2.SelectionForeColor = Color.White;
            dataGridViewCellStyle2.WrapMode = DataGridViewTriState.True;
            dgvCustomer.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2;
            dgvCustomer.ColumnHeadersHeight = 40;
            dgvCustomer.CurrentTheme.AlternatingRowsStyle.BackColor = Color.FromArgb(255, 232, 191);
            dgvCustomer.CurrentTheme.AlternatingRowsStyle.Font = new Font("Segoe UI Semibold", 9.75F, FontStyle.Bold);
            dgvCustomer.CurrentTheme.AlternatingRowsStyle.ForeColor = Color.Black;
            dgvCustomer.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = Color.FromArgb(255, 201, 102);
            dgvCustomer.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = Color.Black;
            dgvCustomer.CurrentTheme.BackColor = Color.Orange;
            dgvCustomer.CurrentTheme.GridColor = Color.FromArgb(255, 226, 173);
            dgvCustomer.CurrentTheme.HeaderStyle.BackColor = Color.Orange;
            dgvCustomer.CurrentTheme.HeaderStyle.Font = new Font("Segoe UI Semibold", 11.75F, FontStyle.Bold);
            dgvCustomer.CurrentTheme.HeaderStyle.ForeColor = Color.White;
            dgvCustomer.CurrentTheme.HeaderStyle.SelectionBackColor = Color.FromArgb(204, 132, 0);
            dgvCustomer.CurrentTheme.HeaderStyle.SelectionForeColor = Color.White;
            dgvCustomer.CurrentTheme.Name = null;
            dgvCustomer.CurrentTheme.RowsStyle.BackColor = Color.FromArgb(255, 237, 204);
            dgvCustomer.CurrentTheme.RowsStyle.Font = new Font("Segoe UI Semibold", 9.75F, FontStyle.Bold);
            dgvCustomer.CurrentTheme.RowsStyle.ForeColor = Color.Black;
            dgvCustomer.CurrentTheme.RowsStyle.SelectionBackColor = Color.FromArgb(255, 201, 102);
            dgvCustomer.CurrentTheme.RowsStyle.SelectionForeColor = Color.Black;
            dataGridViewCellStyle3.Alignment = DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle3.BackColor = Color.FromArgb(255, 237, 204);
            dataGridViewCellStyle3.Font = new Font("Segoe UI Semibold", 9.75F, FontStyle.Bold);
            dataGridViewCellStyle3.ForeColor = Color.Black;
            dataGridViewCellStyle3.SelectionBackColor = Color.FromArgb(255, 201, 102);
            dataGridViewCellStyle3.SelectionForeColor = Color.Black;
            dataGridViewCellStyle3.WrapMode = DataGridViewTriState.False;
            dgvCustomer.DefaultCellStyle = dataGridViewCellStyle3;
            dgvCustomer.EnableHeadersVisualStyles = false;
            dgvCustomer.GridColor = Color.FromArgb(255, 226, 173);
            dgvCustomer.HeaderBackColor = Color.Orange;
            dgvCustomer.HeaderBgColor = Color.Empty;
            dgvCustomer.HeaderForeColor = Color.White;
            dgvCustomer.Location = new Point(474, 151);
            dgvCustomer.Name = "dgvCustomer";
            dgvCustomer.RowHeadersVisible = false;
            dgvCustomer.RowTemplate.Height = 40;
            dgvCustomer.ScrollBars = ScrollBars.Vertical;
            dgvCustomer.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
            dgvCustomer.Size = new Size(665, 506);
            dgvCustomer.TabIndex = 123;
            dgvCustomer.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.Orange;
            // 
            // txtID
            // 
            txtID.AcceptsReturn = false;
            txtID.AcceptsTab = false;
            txtID.AnimationSpeed = 200;
            txtID.AutoCompleteMode = AutoCompleteMode.None;
            txtID.AutoCompleteSource = AutoCompleteSource.None;
            txtID.AutoSizeHeight = true;
            txtID.BackColor = Color.Transparent;
            txtID.BackgroundImage = (Image)resources.GetObject("txtID.BackgroundImage");
            txtID.BorderColorActive = Color.DarkGoldenrod;
            txtID.BorderColorDisabled = Color.FromArgb(204, 204, 204);
            txtID.BorderColorHover = Color.DarkGoldenrod;
            txtID.BorderColorIdle = Color.Silver;
            txtID.BorderRadius = 35;
            txtID.BorderThickness = 1;
            txtID.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            txtID.CharacterCasing = CharacterCasing.Normal;
            txtID.DefaultFont = new Font("Microsoft Sans Serif", 9F, FontStyle.Bold);
            txtID.DefaultText = "";
            txtID.Enabled = false;
            txtID.FillColor = Color.White;
            txtID.HideSelection = true;
            txtID.IconLeft = null;
            txtID.IconLeftCursor = Cursors.IBeam;
            txtID.IconPadding = 10;
            txtID.IconRight = null;
            txtID.IconRightCursor = Cursors.IBeam;
            txtID.Location = new Point(166, 151);
            txtID.MaxLength = 32767;
            txtID.MinimumSize = new Size(1, 1);
            txtID.Modified = false;
            txtID.Multiline = false;
            txtID.Name = "txtID";
            stateProperties5.BorderColor = Color.DarkGoldenrod;
            stateProperties5.FillColor = Color.Empty;
            stateProperties5.ForeColor = Color.Empty;
            stateProperties5.PlaceholderForeColor = Color.Empty;
            txtID.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = Color.FromArgb(204, 204, 204);
            stateProperties6.FillColor = Color.FromArgb(240, 240, 240);
            stateProperties6.ForeColor = Color.FromArgb(109, 109, 109);
            stateProperties6.PlaceholderForeColor = Color.DarkGray;
            txtID.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = Color.DarkGoldenrod;
            stateProperties7.FillColor = Color.Empty;
            stateProperties7.ForeColor = Color.Empty;
            stateProperties7.PlaceholderForeColor = Color.Empty;
            txtID.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = Color.Silver;
            stateProperties8.FillColor = Color.White;
            stateProperties8.ForeColor = Color.Empty;
            stateProperties8.PlaceholderForeColor = Color.Empty;
            txtID.OnIdleState = stateProperties8;
            txtID.Padding = new Padding(3);
            txtID.PasswordChar = '\0';
            txtID.PlaceholderForeColor = Color.Silver;
            txtID.PlaceholderText = "Enter text";
            txtID.ReadOnly = true;
            txtID.ScrollBars = ScrollBars.None;
            txtID.SelectedText = "";
            txtID.SelectionLength = 0;
            txtID.SelectionStart = 0;
            txtID.ShortcutsEnabled = true;
            txtID.Size = new Size(271, 44);
            txtID.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            txtID.TabIndex = 125;
            txtID.TextAlign = HorizontalAlignment.Left;
            txtID.TextMarginBottom = 0;
            txtID.TextMarginLeft = 3;
            txtID.TextMarginTop = 1;
            txtID.TextPlaceholder = "Enter text";
            txtID.UseSystemPasswordChar = false;
            txtID.WordWrap = true;
            // 
            // label1
            // 
            label1.AutoSize = true;
            label1.Font = new Font("Sitka Text", 14.2499981F);
            label1.Location = new Point(13, 151);
            label1.Name = "label1";
            label1.Size = new Size(32, 28);
            label1.TabIndex = 124;
            label1.Text = "ID";
            // 
            // txtCustomerID
            // 
            txtCustomerID.AcceptsReturn = false;
            txtCustomerID.AcceptsTab = false;
            txtCustomerID.AnimationSpeed = 200;
            txtCustomerID.AutoCompleteMode = AutoCompleteMode.None;
            txtCustomerID.AutoCompleteSource = AutoCompleteSource.None;
            txtCustomerID.AutoSizeHeight = true;
            txtCustomerID.BackColor = Color.Transparent;
            txtCustomerID.BackgroundImage = (Image)resources.GetObject("txtCustomerID.BackgroundImage");
            txtCustomerID.BorderColorActive = Color.DarkGoldenrod;
            txtCustomerID.BorderColorDisabled = Color.FromArgb(204, 204, 204);
            txtCustomerID.BorderColorHover = Color.DarkGoldenrod;
            txtCustomerID.BorderColorIdle = Color.Silver;
            txtCustomerID.BorderRadius = 35;
            txtCustomerID.BorderThickness = 1;
            txtCustomerID.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            txtCustomerID.CharacterCasing = CharacterCasing.Normal;
            txtCustomerID.DefaultFont = new Font("Microsoft Sans Serif", 9F, FontStyle.Bold);
            txtCustomerID.DefaultText = "";
            txtCustomerID.FillColor = Color.White;
            txtCustomerID.HideSelection = false;
            txtCustomerID.IconLeft = null;
            txtCustomerID.IconLeftCursor = Cursors.IBeam;
            txtCustomerID.IconPadding = 10;
            txtCustomerID.IconRight = null;
            txtCustomerID.IconRightCursor = Cursors.IBeam;
            txtCustomerID.Location = new Point(166, 201);
            txtCustomerID.MaxLength = 32767;
            txtCustomerID.MinimumSize = new Size(1, 1);
            txtCustomerID.Modified = false;
            txtCustomerID.Multiline = false;
            txtCustomerID.Name = "txtCustomerID";
            stateProperties9.BorderColor = Color.DarkGoldenrod;
            stateProperties9.FillColor = Color.Empty;
            stateProperties9.ForeColor = Color.Empty;
            stateProperties9.PlaceholderForeColor = Color.Empty;
            txtCustomerID.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = Color.FromArgb(204, 204, 204);
            stateProperties10.FillColor = Color.FromArgb(240, 240, 240);
            stateProperties10.ForeColor = Color.FromArgb(109, 109, 109);
            stateProperties10.PlaceholderForeColor = Color.DarkGray;
            txtCustomerID.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = Color.DarkGoldenrod;
            stateProperties11.FillColor = Color.Empty;
            stateProperties11.ForeColor = Color.Empty;
            stateProperties11.PlaceholderForeColor = Color.Empty;
            txtCustomerID.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = Color.Silver;
            stateProperties12.FillColor = Color.White;
            stateProperties12.ForeColor = Color.Empty;
            stateProperties12.PlaceholderForeColor = Color.Empty;
            txtCustomerID.OnIdleState = stateProperties12;
            txtCustomerID.Padding = new Padding(3);
            txtCustomerID.PasswordChar = '\0';
            txtCustomerID.PlaceholderForeColor = Color.Silver;
            txtCustomerID.PlaceholderText = "Enter text";
            txtCustomerID.ReadOnly = false;
            txtCustomerID.ScrollBars = ScrollBars.None;
            txtCustomerID.SelectedText = "";
            txtCustomerID.SelectionLength = 0;
            txtCustomerID.SelectionStart = 0;
            txtCustomerID.ShortcutsEnabled = true;
            txtCustomerID.Size = new Size(271, 44);
            txtCustomerID.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            txtCustomerID.TabIndex = 127;
            txtCustomerID.TextAlign = HorizontalAlignment.Left;
            txtCustomerID.TextMarginBottom = 0;
            txtCustomerID.TextMarginLeft = 3;
            txtCustomerID.TextMarginTop = 1;
            txtCustomerID.TextPlaceholder = "Enter text";
            txtCustomerID.UseSystemPasswordChar = false;
            txtCustomerID.WordWrap = true;
            // 
            // label2
            // 
            label2.AutoSize = true;
            label2.Font = new Font("Sitka Text", 14.2499981F);
            label2.Location = new Point(13, 201);
            label2.Name = "label2";
            label2.Size = new Size(132, 28);
            label2.TabIndex = 126;
            label2.Text = "Card Number";
            // 
            // txtIssuedTime
            // 
            txtIssuedTime.AcceptsReturn = false;
            txtIssuedTime.AcceptsTab = false;
            txtIssuedTime.AnimationSpeed = 200;
            txtIssuedTime.AutoCompleteMode = AutoCompleteMode.None;
            txtIssuedTime.AutoCompleteSource = AutoCompleteSource.None;
            txtIssuedTime.AutoSizeHeight = true;
            txtIssuedTime.BackColor = Color.Transparent;
            txtIssuedTime.BackgroundImage = (Image)resources.GetObject("txtIssuedTime.BackgroundImage");
            txtIssuedTime.BorderColorActive = Color.DarkGoldenrod;
            txtIssuedTime.BorderColorDisabled = Color.FromArgb(204, 204, 204);
            txtIssuedTime.BorderColorHover = Color.DarkGoldenrod;
            txtIssuedTime.BorderColorIdle = Color.Silver;
            txtIssuedTime.BorderRadius = 35;
            txtIssuedTime.BorderThickness = 1;
            txtIssuedTime.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            txtIssuedTime.CharacterCasing = CharacterCasing.Normal;
            txtIssuedTime.DefaultFont = new Font("Microsoft Sans Serif", 9F, FontStyle.Bold);
            txtIssuedTime.DefaultText = "";
            txtIssuedTime.Enabled = false;
            txtIssuedTime.FillColor = Color.White;
            txtIssuedTime.HideSelection = true;
            txtIssuedTime.IconLeft = null;
            txtIssuedTime.IconLeftCursor = Cursors.IBeam;
            txtIssuedTime.IconPadding = 10;
            txtIssuedTime.IconRight = null;
            txtIssuedTime.IconRightCursor = Cursors.IBeam;
            txtIssuedTime.Location = new Point(166, 251);
            txtIssuedTime.MaxLength = 32767;
            txtIssuedTime.MinimumSize = new Size(1, 1);
            txtIssuedTime.Modified = false;
            txtIssuedTime.Multiline = false;
            txtIssuedTime.Name = "txtIssuedTime";
            stateProperties13.BorderColor = Color.DarkGoldenrod;
            stateProperties13.FillColor = Color.Empty;
            stateProperties13.ForeColor = Color.Empty;
            stateProperties13.PlaceholderForeColor = Color.Empty;
            txtIssuedTime.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = Color.FromArgb(204, 204, 204);
            stateProperties14.FillColor = Color.FromArgb(240, 240, 240);
            stateProperties14.ForeColor = Color.FromArgb(109, 109, 109);
            stateProperties14.PlaceholderForeColor = Color.DarkGray;
            txtIssuedTime.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = Color.DarkGoldenrod;
            stateProperties15.FillColor = Color.Empty;
            stateProperties15.ForeColor = Color.Empty;
            stateProperties15.PlaceholderForeColor = Color.Empty;
            txtIssuedTime.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = Color.Silver;
            stateProperties16.FillColor = Color.White;
            stateProperties16.ForeColor = Color.Empty;
            stateProperties16.PlaceholderForeColor = Color.Empty;
            txtIssuedTime.OnIdleState = stateProperties16;
            txtIssuedTime.Padding = new Padding(3);
            txtIssuedTime.PasswordChar = '\0';
            txtIssuedTime.PlaceholderForeColor = Color.Silver;
            txtIssuedTime.PlaceholderText = "Enter text";
            txtIssuedTime.ReadOnly = true;
            txtIssuedTime.ScrollBars = ScrollBars.None;
            txtIssuedTime.SelectedText = "";
            txtIssuedTime.SelectionLength = 0;
            txtIssuedTime.SelectionStart = 0;
            txtIssuedTime.ShortcutsEnabled = true;
            txtIssuedTime.Size = new Size(271, 44);
            txtIssuedTime.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            txtIssuedTime.TabIndex = 129;
            txtIssuedTime.TextAlign = HorizontalAlignment.Left;
            txtIssuedTime.TextMarginBottom = 0;
            txtIssuedTime.TextMarginLeft = 3;
            txtIssuedTime.TextMarginTop = 1;
            txtIssuedTime.TextPlaceholder = "Enter text";
            txtIssuedTime.UseSystemPasswordChar = false;
            txtIssuedTime.WordWrap = true;
            // 
            // label3
            // 
            label3.AutoSize = true;
            label3.Font = new Font("Sitka Text", 14.2499981F);
            label3.Location = new Point(13, 251);
            label3.Name = "label3";
            label3.Size = new Size(119, 28);
            label3.TabIndex = 128;
            label3.Text = "Issued Time";
            // 
            // txtNote
            // 
            txtNote.AcceptsReturn = false;
            txtNote.AcceptsTab = false;
            txtNote.AnimationSpeed = 200;
            txtNote.AutoCompleteMode = AutoCompleteMode.None;
            txtNote.AutoCompleteSource = AutoCompleteSource.None;
            txtNote.AutoSizeHeight = true;
            txtNote.BackColor = Color.Transparent;
            txtNote.BackgroundImage = (Image)resources.GetObject("txtNote.BackgroundImage");
            txtNote.BorderColorActive = Color.DarkGoldenrod;
            txtNote.BorderColorDisabled = Color.FromArgb(204, 204, 204);
            txtNote.BorderColorHover = Color.DarkGoldenrod;
            txtNote.BorderColorIdle = Color.Silver;
            txtNote.BorderRadius = 35;
            txtNote.BorderThickness = 1;
            txtNote.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            txtNote.CharacterCasing = CharacterCasing.Normal;
            txtNote.DefaultFont = new Font("Microsoft Sans Serif", 9F, FontStyle.Bold);
            txtNote.DefaultText = "";
            txtNote.FillColor = Color.White;
            txtNote.HideSelection = true;
            txtNote.IconLeft = null;
            txtNote.IconLeftCursor = Cursors.IBeam;
            txtNote.IconPadding = 10;
            txtNote.IconRight = null;
            txtNote.IconRightCursor = Cursors.IBeam;
            txtNote.Location = new Point(166, 301);
            txtNote.MaxLength = 32767;
            txtNote.MinimumSize = new Size(1, 1);
            txtNote.Modified = false;
            txtNote.Multiline = false;
            txtNote.Name = "txtNote";
            stateProperties17.BorderColor = Color.DarkGoldenrod;
            stateProperties17.FillColor = Color.Empty;
            stateProperties17.ForeColor = Color.Empty;
            stateProperties17.PlaceholderForeColor = Color.Empty;
            txtNote.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = Color.FromArgb(204, 204, 204);
            stateProperties18.FillColor = Color.FromArgb(240, 240, 240);
            stateProperties18.ForeColor = Color.FromArgb(109, 109, 109);
            stateProperties18.PlaceholderForeColor = Color.DarkGray;
            txtNote.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = Color.DarkGoldenrod;
            stateProperties19.FillColor = Color.Empty;
            stateProperties19.ForeColor = Color.Empty;
            stateProperties19.PlaceholderForeColor = Color.Empty;
            txtNote.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = Color.Silver;
            stateProperties20.FillColor = Color.White;
            stateProperties20.ForeColor = Color.Empty;
            stateProperties20.PlaceholderForeColor = Color.Empty;
            txtNote.OnIdleState = stateProperties20;
            txtNote.Padding = new Padding(3);
            txtNote.PasswordChar = '\0';
            txtNote.PlaceholderForeColor = Color.Silver;
            txtNote.PlaceholderText = "Enter text";
            txtNote.ReadOnly = false;
            txtNote.ScrollBars = ScrollBars.None;
            txtNote.SelectedText = "";
            txtNote.SelectionLength = 0;
            txtNote.SelectionStart = 0;
            txtNote.ShortcutsEnabled = true;
            txtNote.Size = new Size(271, 44);
            txtNote.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            txtNote.TabIndex = 131;
            txtNote.TextAlign = HorizontalAlignment.Left;
            txtNote.TextMarginBottom = 0;
            txtNote.TextMarginLeft = 3;
            txtNote.TextMarginTop = 1;
            txtNote.TextPlaceholder = "Enter text";
            txtNote.UseSystemPasswordChar = false;
            txtNote.WordWrap = true;
            // 
            // label4
            // 
            label4.AutoSize = true;
            label4.Font = new Font("Sitka Text", 14.2499981F);
            label4.Location = new Point(13, 301);
            label4.Name = "label4";
            label4.Size = new Size(55, 28);
            label4.TabIndex = 130;
            label4.Text = "Note";
            // 
            // bunifuFormDock1
            // 
            bunifuFormDock1.AllowFormDragging = true;
            bunifuFormDock1.AllowFormDropShadow = true;
            bunifuFormDock1.AllowFormResizing = true;
            bunifuFormDock1.AllowHidingBottomRegion = true;
            bunifuFormDock1.AllowOpacityChangesWhileDragging = false;
            bunifuFormDock1.BorderOptions.BottomBorder.BorderColor = Color.Silver;
            bunifuFormDock1.BorderOptions.BottomBorder.BorderThickness = 1;
            bunifuFormDock1.BorderOptions.BottomBorder.ShowBorder = true;
            bunifuFormDock1.BorderOptions.LeftBorder.BorderColor = Color.Silver;
            bunifuFormDock1.BorderOptions.LeftBorder.BorderThickness = 1;
            bunifuFormDock1.BorderOptions.LeftBorder.ShowBorder = true;
            bunifuFormDock1.BorderOptions.RightBorder.BorderColor = Color.Silver;
            bunifuFormDock1.BorderOptions.RightBorder.BorderThickness = 1;
            bunifuFormDock1.BorderOptions.RightBorder.ShowBorder = true;
            bunifuFormDock1.BorderOptions.TopBorder.BorderColor = Color.Silver;
            bunifuFormDock1.BorderOptions.TopBorder.BorderThickness = 1;
            bunifuFormDock1.BorderOptions.TopBorder.ShowBorder = true;
            bunifuFormDock1.ContainerControl = this;
            bunifuFormDock1.DockingIndicatorsColor = Color.FromArgb(202, 215, 233);
            bunifuFormDock1.DockingIndicatorsOpacity = 0.5D;
            bunifuFormDock1.DockingOptions.DockAll = true;
            bunifuFormDock1.DockingOptions.DockBottomLeft = true;
            bunifuFormDock1.DockingOptions.DockBottomRight = true;
            bunifuFormDock1.DockingOptions.DockFullScreen = true;
            bunifuFormDock1.DockingOptions.DockLeft = true;
            bunifuFormDock1.DockingOptions.DockRight = true;
            bunifuFormDock1.DockingOptions.DockTopLeft = true;
            bunifuFormDock1.DockingOptions.DockTopRight = true;
            bunifuFormDock1.FormDraggingOpacity = 0.9D;
            bunifuFormDock1.ParentForm = this;
            bunifuFormDock1.ShowCursorChanges = true;
            bunifuFormDock1.ShowDockingIndicators = true;
            bunifuFormDock1.TitleBarOptions.AllowFormDragging = true;
            bunifuFormDock1.TitleBarOptions.BunifuFormDock = bunifuFormDock1;
            bunifuFormDock1.TitleBarOptions.DoubleClickToExpandWindow = true;
            bunifuFormDock1.TitleBarOptions.TitleBarControl = null;
            bunifuFormDock1.TitleBarOptions.UseBackColorOnDockingIndicators = false;
            // 
            // btnSetDamaged
            // 
            btnSetDamaged.BackColor = Color.FromArgb(229, 57, 53);
            btnSetDamaged.FlatAppearance.BorderSize = 0;
            btnSetDamaged.FlatStyle = FlatStyle.Flat;
            btnSetDamaged.Font = new Font("Sitka Text", 12F, FontStyle.Regular, GraphicsUnit.Point, 0);
            btnSetDamaged.ForeColor = Color.White;
            btnSetDamaged.Location = new Point(13, 367);
            btnSetDamaged.Name = "btnSetDamaged";
            btnSetDamaged.Size = new Size(424, 40);
            btnSetDamaged.TabIndex = 132;
            btnSetDamaged.Text = "Set as Damaged";
            btnSetDamaged.UseVisualStyleBackColor = false;
            btnSetDamaged.Click += btnSetDamaged_Click;
            // 
            // Customer
            // 
            AutoScaleDimensions = new SizeF(7F, 15F);
            AutoScaleMode = AutoScaleMode.Font;
            ClientSize = new Size(1148, 670);
            Controls.Add(btnSetDamaged);
            Controls.Add(txtNote);
            Controls.Add(label4);
            Controls.Add(txtIssuedTime);
            Controls.Add(label3);
            Controls.Add(txtCustomerID);
            Controls.Add(label2);
            Controls.Add(txtID);
            Controls.Add(label1);
            Controls.Add(dgvCustomer);
            Controls.Add(btnClear);
            Controls.Add(btnUpdate);
            Controls.Add(btnInsert);
            Controls.Add(btnNew);
            Controls.Add(txtSearch);
            Controls.Add(bunifuPanel2);
            FormBorderStyle = FormBorderStyle.None;
            Name = "Customer";
            StartPosition = FormStartPosition.CenterScreen;
            Text = "Customer";
            bunifuPanel2.ResumeLayout(false);
            bunifuPanel2.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)dgvCustomer).EndInit();
            ResumeLayout(false);
            PerformLayout();
        }

        #endregion
        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel2;
        private Label label11;
        private Bunifu.UI.WinForms.BunifuButton.BunifuIconButton btnExitProgram;
        private Bunifu.UI.WinForms.BunifuTextBox txtSearch;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnClear;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnUpdate;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnInsert;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnNew;
        private Bunifu.UI.WinForms.BunifuDataGridView dgvCustomer;
        private Bunifu.UI.WinForms.BunifuTextBox txtID;
        private Label label1;
        private Bunifu.UI.WinForms.BunifuTextBox txtCustomerID;
        private Label label2;
        private Bunifu.UI.WinForms.BunifuTextBox txtIssuedTime;
        private Label label3;
        private Bunifu.UI.WinForms.BunifuTextBox txtNote;
        private Label label4;
        private Bunifu.UI.WinForms.BunifuFormDock bunifuFormDock1;
        private Button btnSetDamaged;
    }
}