namespace Spa_Management_System
{
    partial class Dashboard
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Dashboard));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges8 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuIconButton.BorderEdges borderEdges9 = new Bunifu.UI.WinForms.BunifuButton.BunifuIconButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges10 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges11 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges12 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            bunifuPanel1 = new Bunifu.UI.WinForms.BunifuPanel();
            btnRefresh = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            btnLogout = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            btnSetting = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            btnPayment = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            btnInvoice = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            btnStatistic = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            btnAllForm = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            LogoImage = new Bunifu.UI.WinForms.BunifuPictureBox();
            bunifuPanel2 = new Bunifu.UI.WinForms.BunifuPanel();
            panOrderDetailOuter = new Bunifu.UI.WinForms.BunifuPanel();
            txtCardStatus = new Bunifu.UI.WinForms.BunifuLabel();
            txtCustomerID = new Bunifu.UI.WinForms.BunifuTextBox();
            btnCheckout = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            bunifuPanel9 = new Bunifu.UI.WinForms.BunifuPanel();
            bunifuLabel40 = new Bunifu.UI.WinForms.BunifuLabel();
            bunifuSeparator1 = new Bunifu.UI.WinForms.BunifuSeparator();
            bunifuLabel38 = new Bunifu.UI.WinForms.BunifuLabel();
            bunifuLabel36 = new Bunifu.UI.WinForms.BunifuLabel();
            bunifuLabel37 = new Bunifu.UI.WinForms.BunifuLabel();
            bunifuLabel35 = new Bunifu.UI.WinForms.BunifuLabel();
            bunifuLabel34 = new Bunifu.UI.WinForms.BunifuLabel();
            bunifuLabel27 = new Bunifu.UI.WinForms.BunifuLabel();
            btnExitProgram = new Bunifu.UI.WinForms.BunifuButton.BunifuIconButton();
            bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            bunifuLabel2 = new Bunifu.UI.WinForms.BunifuLabel();
            txtSearch = new Bunifu.UI.WinForms.BunifuTextBox();
            btnServices = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            btnFoods = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            btnDrinks = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            panDisplayItem = new Bunifu.UI.WinForms.BunifuPanel();
            sliderPriceFilter = new Bunifu.UI.WinForms.BunifuHSlider();
            lblPriceRange = new Bunifu.UI.WinForms.BunifuLabel();
            bunifuFormDock1 = new Bunifu.UI.WinForms.BunifuFormDock();
            bunifuPanel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)LogoImage).BeginInit();
            bunifuPanel2.SuspendLayout();
            bunifuPanel9.SuspendLayout();
            SuspendLayout();
            // 
            // bunifuPanel1
            // 
            bunifuPanel1.BackgroundColor = Color.White;
            bunifuPanel1.BackgroundImage = (Image)resources.GetObject("bunifuPanel1.BackgroundImage");
            bunifuPanel1.BackgroundImageLayout = ImageLayout.Stretch;
            bunifuPanel1.BorderColor = Color.White;
            bunifuPanel1.BorderRadius = 3;
            bunifuPanel1.BorderThickness = 1;
            bunifuPanel1.Controls.Add(btnRefresh);
            bunifuPanel1.Controls.Add(btnLogout);
            bunifuPanel1.Controls.Add(btnSetting);
            bunifuPanel1.Controls.Add(btnPayment);
            bunifuPanel1.Controls.Add(btnInvoice);
            bunifuPanel1.Controls.Add(btnStatistic);
            bunifuPanel1.Controls.Add(btnAllForm);
            bunifuPanel1.Controls.Add(LogoImage);
            bunifuPanel1.Dock = DockStyle.Left;
            bunifuPanel1.Location = new Point(0, 0);
            bunifuPanel1.Name = "bunifuPanel1";
            bunifuPanel1.ShowBorders = true;
            bunifuPanel1.Size = new Size(87, 788);
            bunifuPanel1.TabIndex = 0;
            // 
            // btnRefresh
            // 
            btnRefresh.AllowAnimations = true;
            btnRefresh.AllowMouseEffects = true;
            btnRefresh.AllowToggling = false;
            btnRefresh.AnimationSpeed = 200;
            btnRefresh.AutoGenerateColors = false;
            btnRefresh.AutoRoundBorders = false;
            btnRefresh.AutoSizeLeftIcon = true;
            btnRefresh.AutoSizeRightIcon = true;
            btnRefresh.BackColor = Color.Transparent;
            btnRefresh.BackColor1 = Color.White;
            btnRefresh.BackgroundImage = (Image)resources.GetObject("btnRefresh.BackgroundImage");
            btnRefresh.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnRefresh.ButtonText = "";
            btnRefresh.ButtonTextMarginLeft = 0;
            btnRefresh.ColorContrastOnClick = 45;
            btnRefresh.ColorContrastOnHover = 45;
            btnRefresh.Cursor = Cursors.Hand;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            btnRefresh.CustomizableEdges = borderEdges1;
            btnRefresh.DialogResult = DialogResult.None;
            btnRefresh.DisabledBorderColor = Color.FromArgb(191, 191, 191);
            btnRefresh.DisabledFillColor = Color.FromArgb(204, 204, 204);
            btnRefresh.DisabledForecolor = Color.FromArgb(168, 160, 168);
            btnRefresh.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            btnRefresh.Font = new Font("Microsoft Sans Serif", 9F, FontStyle.Bold, GraphicsUnit.Point, 0);
            btnRefresh.ForeColor = Color.White;
            btnRefresh.IconLeftAlign = ContentAlignment.MiddleLeft;
            btnRefresh.IconLeftCursor = Cursors.Default;
            btnRefresh.IconLeftPadding = new Padding(11, 3, 3, 3);
            btnRefresh.IconMarginLeft = 11;
            btnRefresh.IconPadding = 10;
            btnRefresh.IconRightAlign = ContentAlignment.MiddleRight;
            btnRefresh.IconRightCursor = Cursors.Default;
            btnRefresh.IconRightPadding = new Padding(3, 3, 7, 3);
            btnRefresh.IconSize = 25;
            btnRefresh.IdleBorderColor = Color.White;
            btnRefresh.IdleBorderRadius = 1;
            btnRefresh.IdleBorderThickness = 1;
            btnRefresh.IdleFillColor = Color.White;
            btnRefresh.IdleIconLeftImage = Properties.Resources.transfer;
            btnRefresh.IdleIconRightImage = null;
            btnRefresh.IndicateFocus = false;
            btnRefresh.Location = new Point(15, 389);
            btnRefresh.Name = "btnRefresh";
            btnRefresh.OnDisabledState.BorderColor = Color.FromArgb(191, 191, 191);
            btnRefresh.OnDisabledState.BorderRadius = 1;
            btnRefresh.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnRefresh.OnDisabledState.BorderThickness = 1;
            btnRefresh.OnDisabledState.FillColor = Color.FromArgb(204, 204, 204);
            btnRefresh.OnDisabledState.ForeColor = Color.FromArgb(168, 160, 168);
            btnRefresh.OnDisabledState.IconLeftImage = null;
            btnRefresh.OnDisabledState.IconRightImage = null;
            btnRefresh.onHoverState.BorderColor = Color.DarkGoldenrod;
            btnRefresh.onHoverState.BorderRadius = 1;
            btnRefresh.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnRefresh.onHoverState.BorderThickness = 1;
            btnRefresh.onHoverState.FillColor = Color.White;
            btnRefresh.onHoverState.ForeColor = Color.White;
            btnRefresh.onHoverState.IconLeftImage = null;
            btnRefresh.onHoverState.IconRightImage = null;
            btnRefresh.OnIdleState.BorderColor = Color.White;
            btnRefresh.OnIdleState.BorderRadius = 1;
            btnRefresh.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnRefresh.OnIdleState.BorderThickness = 1;
            btnRefresh.OnIdleState.FillColor = Color.White;
            btnRefresh.OnIdleState.ForeColor = Color.White;
            btnRefresh.OnIdleState.IconLeftImage = Properties.Resources.transfer;
            btnRefresh.OnIdleState.IconRightImage = null;
            btnRefresh.OnPressedState.BorderColor = Color.DarkGoldenrod;
            btnRefresh.OnPressedState.BorderRadius = 1;
            btnRefresh.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnRefresh.OnPressedState.BorderThickness = 1;
            btnRefresh.OnPressedState.FillColor = Color.White;
            btnRefresh.OnPressedState.ForeColor = Color.White;
            btnRefresh.OnPressedState.IconLeftImage = null;
            btnRefresh.OnPressedState.IconRightImage = null;
            btnRefresh.Size = new Size(61, 58);
            btnRefresh.TabIndex = 22;
            btnRefresh.TextAlign = ContentAlignment.MiddleCenter;
            btnRefresh.TextAlignment = HorizontalAlignment.Center;
            btnRefresh.TextMarginLeft = 0;
            btnRefresh.TextPadding = new Padding(0);
            btnRefresh.UseDefaultRadiusAndThickness = true;
            // 
            // btnLogout
            // 
            btnLogout.AllowAnimations = true;
            btnLogout.AllowMouseEffects = true;
            btnLogout.AllowToggling = false;
            btnLogout.AnimationSpeed = 200;
            btnLogout.AutoGenerateColors = false;
            btnLogout.AutoRoundBorders = false;
            btnLogout.AutoSizeLeftIcon = true;
            btnLogout.AutoSizeRightIcon = true;
            btnLogout.BackColor = Color.Transparent;
            btnLogout.BackColor1 = Color.White;
            btnLogout.BackgroundImage = (Image)resources.GetObject("btnLogout.BackgroundImage");
            btnLogout.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnLogout.ButtonText = "";
            btnLogout.ButtonTextMarginLeft = 0;
            btnLogout.ColorContrastOnClick = 45;
            btnLogout.ColorContrastOnHover = 45;
            btnLogout.Cursor = Cursors.Hand;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            btnLogout.CustomizableEdges = borderEdges2;
            btnLogout.DialogResult = DialogResult.None;
            btnLogout.DisabledBorderColor = Color.FromArgb(191, 191, 191);
            btnLogout.DisabledFillColor = Color.FromArgb(204, 204, 204);
            btnLogout.DisabledForecolor = Color.FromArgb(168, 160, 168);
            btnLogout.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            btnLogout.Font = new Font("Segoe UI", 9F);
            btnLogout.ForeColor = Color.White;
            btnLogout.IconLeftAlign = ContentAlignment.MiddleLeft;
            btnLogout.IconLeftCursor = Cursors.Default;
            btnLogout.IconLeftPadding = new Padding(11, 3, 3, 3);
            btnLogout.IconMarginLeft = 11;
            btnLogout.IconPadding = 10;
            btnLogout.IconRightAlign = ContentAlignment.MiddleRight;
            btnLogout.IconRightCursor = Cursors.Default;
            btnLogout.IconRightPadding = new Padding(3, 3, 7, 3);
            btnLogout.IconSize = 25;
            btnLogout.IdleBorderColor = Color.White;
            btnLogout.IdleBorderRadius = 1;
            btnLogout.IdleBorderThickness = 1;
            btnLogout.IdleFillColor = Color.White;
            btnLogout.IdleIconLeftImage = Properties.Resources.log_out;
            btnLogout.IdleIconRightImage = null;
            btnLogout.IndicateFocus = false;
            btnLogout.Location = new Point(15, 705);
            btnLogout.Name = "btnLogout";
            btnLogout.OnDisabledState.BorderColor = Color.FromArgb(191, 191, 191);
            btnLogout.OnDisabledState.BorderRadius = 1;
            btnLogout.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnLogout.OnDisabledState.BorderThickness = 1;
            btnLogout.OnDisabledState.FillColor = Color.FromArgb(204, 204, 204);
            btnLogout.OnDisabledState.ForeColor = Color.FromArgb(168, 160, 168);
            btnLogout.OnDisabledState.IconLeftImage = null;
            btnLogout.OnDisabledState.IconRightImage = null;
            btnLogout.onHoverState.BorderColor = Color.DarkGoldenrod;
            btnLogout.onHoverState.BorderRadius = 1;
            btnLogout.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnLogout.onHoverState.BorderThickness = 1;
            btnLogout.onHoverState.FillColor = Color.White;
            btnLogout.onHoverState.ForeColor = Color.White;
            btnLogout.onHoverState.IconLeftImage = null;
            btnLogout.onHoverState.IconRightImage = null;
            btnLogout.OnIdleState.BorderColor = Color.White;
            btnLogout.OnIdleState.BorderRadius = 1;
            btnLogout.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnLogout.OnIdleState.BorderThickness = 1;
            btnLogout.OnIdleState.FillColor = Color.White;
            btnLogout.OnIdleState.ForeColor = Color.White;
            btnLogout.OnIdleState.IconLeftImage = Properties.Resources.log_out;
            btnLogout.OnIdleState.IconRightImage = null;
            btnLogout.OnPressedState.BorderColor = Color.DarkGoldenrod;
            btnLogout.OnPressedState.BorderRadius = 1;
            btnLogout.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnLogout.OnPressedState.BorderThickness = 1;
            btnLogout.OnPressedState.FillColor = Color.White;
            btnLogout.OnPressedState.ForeColor = Color.White;
            btnLogout.OnPressedState.IconLeftImage = null;
            btnLogout.OnPressedState.IconRightImage = null;
            btnLogout.Size = new Size(61, 58);
            btnLogout.TabIndex = 8;
            btnLogout.TextAlign = ContentAlignment.MiddleCenter;
            btnLogout.TextAlignment = HorizontalAlignment.Center;
            btnLogout.TextMarginLeft = 0;
            btnLogout.TextPadding = new Padding(0);
            btnLogout.UseDefaultRadiusAndThickness = true;
            // 
            // btnSetting
            // 
            btnSetting.AllowAnimations = true;
            btnSetting.AllowMouseEffects = true;
            btnSetting.AllowToggling = false;
            btnSetting.AnimationSpeed = 200;
            btnSetting.AutoGenerateColors = false;
            btnSetting.AutoRoundBorders = false;
            btnSetting.AutoSizeLeftIcon = true;
            btnSetting.AutoSizeRightIcon = true;
            btnSetting.BackColor = Color.Transparent;
            btnSetting.BackColor1 = Color.White;
            btnSetting.BackgroundImage = (Image)resources.GetObject("btnSetting.BackgroundImage");
            btnSetting.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnSetting.ButtonText = "";
            btnSetting.ButtonTextMarginLeft = 0;
            btnSetting.ColorContrastOnClick = 45;
            btnSetting.ColorContrastOnHover = 45;
            btnSetting.Cursor = Cursors.Hand;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            btnSetting.CustomizableEdges = borderEdges3;
            btnSetting.DialogResult = DialogResult.None;
            btnSetting.DisabledBorderColor = Color.FromArgb(191, 191, 191);
            btnSetting.DisabledFillColor = Color.FromArgb(204, 204, 204);
            btnSetting.DisabledForecolor = Color.FromArgb(168, 160, 168);
            btnSetting.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            btnSetting.Font = new Font("Segoe UI", 9F);
            btnSetting.ForeColor = Color.White;
            btnSetting.IconLeftAlign = ContentAlignment.MiddleLeft;
            btnSetting.IconLeftCursor = Cursors.Default;
            btnSetting.IconLeftPadding = new Padding(11, 3, 3, 3);
            btnSetting.IconMarginLeft = 11;
            btnSetting.IconPadding = 10;
            btnSetting.IconRightAlign = ContentAlignment.MiddleRight;
            btnSetting.IconRightCursor = Cursors.Default;
            btnSetting.IconRightPadding = new Padding(3, 3, 7, 3);
            btnSetting.IconSize = 25;
            btnSetting.IdleBorderColor = Color.White;
            btnSetting.IdleBorderRadius = 1;
            btnSetting.IdleBorderThickness = 1;
            btnSetting.IdleFillColor = Color.White;
            btnSetting.IdleIconLeftImage = Properties.Resources._3d_setting;
            btnSetting.IdleIconRightImage = null;
            btnSetting.IndicateFocus = false;
            btnSetting.Location = new Point(15, 641);
            btnSetting.Name = "btnSetting";
            btnSetting.OnDisabledState.BorderColor = Color.FromArgb(191, 191, 191);
            btnSetting.OnDisabledState.BorderRadius = 1;
            btnSetting.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnSetting.OnDisabledState.BorderThickness = 1;
            btnSetting.OnDisabledState.FillColor = Color.FromArgb(204, 204, 204);
            btnSetting.OnDisabledState.ForeColor = Color.FromArgb(168, 160, 168);
            btnSetting.OnDisabledState.IconLeftImage = null;
            btnSetting.OnDisabledState.IconRightImage = null;
            btnSetting.onHoverState.BorderColor = Color.DarkGoldenrod;
            btnSetting.onHoverState.BorderRadius = 1;
            btnSetting.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnSetting.onHoverState.BorderThickness = 1;
            btnSetting.onHoverState.FillColor = Color.White;
            btnSetting.onHoverState.ForeColor = Color.White;
            btnSetting.onHoverState.IconLeftImage = null;
            btnSetting.onHoverState.IconRightImage = null;
            btnSetting.OnIdleState.BorderColor = Color.White;
            btnSetting.OnIdleState.BorderRadius = 1;
            btnSetting.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnSetting.OnIdleState.BorderThickness = 1;
            btnSetting.OnIdleState.FillColor = Color.White;
            btnSetting.OnIdleState.ForeColor = Color.White;
            btnSetting.OnIdleState.IconLeftImage = Properties.Resources._3d_setting;
            btnSetting.OnIdleState.IconRightImage = null;
            btnSetting.OnPressedState.BorderColor = Color.DarkGoldenrod;
            btnSetting.OnPressedState.BorderRadius = 1;
            btnSetting.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnSetting.OnPressedState.BorderThickness = 1;
            btnSetting.OnPressedState.FillColor = Color.White;
            btnSetting.OnPressedState.ForeColor = Color.White;
            btnSetting.OnPressedState.IconLeftImage = null;
            btnSetting.OnPressedState.IconRightImage = null;
            btnSetting.Size = new Size(61, 58);
            btnSetting.TabIndex = 7;
            btnSetting.TextAlign = ContentAlignment.MiddleCenter;
            btnSetting.TextAlignment = HorizontalAlignment.Center;
            btnSetting.TextMarginLeft = 0;
            btnSetting.TextPadding = new Padding(0);
            btnSetting.UseDefaultRadiusAndThickness = true;
            // 
            // btnPayment
            // 
            btnPayment.AllowAnimations = true;
            btnPayment.AllowMouseEffects = true;
            btnPayment.AllowToggling = false;
            btnPayment.AnimationSpeed = 200;
            btnPayment.AutoGenerateColors = false;
            btnPayment.AutoRoundBorders = false;
            btnPayment.AutoSizeLeftIcon = true;
            btnPayment.AutoSizeRightIcon = true;
            btnPayment.BackColor = Color.Transparent;
            btnPayment.BackColor1 = Color.White;
            btnPayment.BackgroundImage = (Image)resources.GetObject("btnPayment.BackgroundImage");
            btnPayment.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnPayment.ButtonText = "";
            btnPayment.ButtonTextMarginLeft = 0;
            btnPayment.ColorContrastOnClick = 45;
            btnPayment.ColorContrastOnHover = 45;
            btnPayment.Cursor = Cursors.Hand;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            btnPayment.CustomizableEdges = borderEdges4;
            btnPayment.DialogResult = DialogResult.None;
            btnPayment.DisabledBorderColor = Color.FromArgb(191, 191, 191);
            btnPayment.DisabledFillColor = Color.FromArgb(204, 204, 204);
            btnPayment.DisabledForecolor = Color.FromArgb(168, 160, 168);
            btnPayment.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            btnPayment.Font = new Font("Segoe UI", 9F);
            btnPayment.ForeColor = Color.White;
            btnPayment.IconLeftAlign = ContentAlignment.MiddleLeft;
            btnPayment.IconLeftCursor = Cursors.Default;
            btnPayment.IconLeftPadding = new Padding(11, 3, 3, 3);
            btnPayment.IconMarginLeft = 11;
            btnPayment.IconPadding = 12;
            btnPayment.IconRightAlign = ContentAlignment.MiddleRight;
            btnPayment.IconRightCursor = Cursors.Default;
            btnPayment.IconRightPadding = new Padding(3, 3, 7, 3);
            btnPayment.IconSize = 25;
            btnPayment.IdleBorderColor = Color.White;
            btnPayment.IdleBorderRadius = 1;
            btnPayment.IdleBorderThickness = 1;
            btnPayment.IdleFillColor = Color.White;
            btnPayment.IdleIconLeftImage = Properties.Resources.shopping_bag;
            btnPayment.IdleIconRightImage = null;
            btnPayment.IndicateFocus = false;
            btnPayment.Location = new Point(15, 326);
            btnPayment.Name = "btnPayment";
            btnPayment.OnDisabledState.BorderColor = Color.FromArgb(191, 191, 191);
            btnPayment.OnDisabledState.BorderRadius = 1;
            btnPayment.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnPayment.OnDisabledState.BorderThickness = 1;
            btnPayment.OnDisabledState.FillColor = Color.FromArgb(204, 204, 204);
            btnPayment.OnDisabledState.ForeColor = Color.FromArgb(168, 160, 168);
            btnPayment.OnDisabledState.IconLeftImage = null;
            btnPayment.OnDisabledState.IconRightImage = null;
            btnPayment.onHoverState.BorderColor = Color.DarkGoldenrod;
            btnPayment.onHoverState.BorderRadius = 1;
            btnPayment.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnPayment.onHoverState.BorderThickness = 1;
            btnPayment.onHoverState.FillColor = Color.White;
            btnPayment.onHoverState.ForeColor = Color.White;
            btnPayment.onHoverState.IconLeftImage = null;
            btnPayment.onHoverState.IconRightImage = null;
            btnPayment.OnIdleState.BorderColor = Color.White;
            btnPayment.OnIdleState.BorderRadius = 1;
            btnPayment.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnPayment.OnIdleState.BorderThickness = 1;
            btnPayment.OnIdleState.FillColor = Color.White;
            btnPayment.OnIdleState.ForeColor = Color.White;
            btnPayment.OnIdleState.IconLeftImage = Properties.Resources.shopping_bag;
            btnPayment.OnIdleState.IconRightImage = null;
            btnPayment.OnPressedState.BorderColor = Color.DarkGoldenrod;
            btnPayment.OnPressedState.BorderRadius = 1;
            btnPayment.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnPayment.OnPressedState.BorderThickness = 1;
            btnPayment.OnPressedState.FillColor = Color.White;
            btnPayment.OnPressedState.ForeColor = Color.White;
            btnPayment.OnPressedState.IconLeftImage = null;
            btnPayment.OnPressedState.IconRightImage = null;
            btnPayment.Size = new Size(61, 58);
            btnPayment.TabIndex = 6;
            btnPayment.TextAlign = ContentAlignment.MiddleCenter;
            btnPayment.TextAlignment = HorizontalAlignment.Center;
            btnPayment.TextMarginLeft = 0;
            btnPayment.TextPadding = new Padding(0);
            btnPayment.UseDefaultRadiusAndThickness = true;
            btnPayment.Click += btnPayment_Click;
            // 
            // btnInvoice
            // 
            btnInvoice.AllowAnimations = true;
            btnInvoice.AllowMouseEffects = true;
            btnInvoice.AllowToggling = false;
            btnInvoice.AnimationSpeed = 200;
            btnInvoice.AutoGenerateColors = false;
            btnInvoice.AutoRoundBorders = false;
            btnInvoice.AutoSizeLeftIcon = true;
            btnInvoice.AutoSizeRightIcon = true;
            btnInvoice.BackColor = Color.Transparent;
            btnInvoice.BackColor1 = Color.White;
            btnInvoice.BackgroundImage = (Image)resources.GetObject("btnInvoice.BackgroundImage");
            btnInvoice.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnInvoice.ButtonText = "";
            btnInvoice.ButtonTextMarginLeft = 0;
            btnInvoice.ColorContrastOnClick = 45;
            btnInvoice.ColorContrastOnHover = 45;
            btnInvoice.Cursor = Cursors.Hand;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            btnInvoice.CustomizableEdges = borderEdges5;
            btnInvoice.DialogResult = DialogResult.None;
            btnInvoice.DisabledBorderColor = Color.FromArgb(191, 191, 191);
            btnInvoice.DisabledFillColor = Color.FromArgb(204, 204, 204);
            btnInvoice.DisabledForecolor = Color.FromArgb(168, 160, 168);
            btnInvoice.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            btnInvoice.Font = new Font("Segoe UI", 9F);
            btnInvoice.ForeColor = Color.White;
            btnInvoice.IconLeftAlign = ContentAlignment.MiddleLeft;
            btnInvoice.IconLeftCursor = Cursors.Default;
            btnInvoice.IconLeftPadding = new Padding(11, 3, 3, 3);
            btnInvoice.IconMarginLeft = 11;
            btnInvoice.IconPadding = 12;
            btnInvoice.IconRightAlign = ContentAlignment.MiddleRight;
            btnInvoice.IconRightCursor = Cursors.Default;
            btnInvoice.IconRightPadding = new Padding(3, 3, 7, 3);
            btnInvoice.IconSize = 25;
            btnInvoice.IdleBorderColor = Color.White;
            btnInvoice.IdleBorderRadius = 1;
            btnInvoice.IdleBorderThickness = 1;
            btnInvoice.IdleFillColor = Color.White;
            btnInvoice.IdleIconLeftImage = Properties.Resources.report;
            btnInvoice.IdleIconRightImage = null;
            btnInvoice.IndicateFocus = false;
            btnInvoice.Location = new Point(15, 263);
            btnInvoice.Name = "btnInvoice";
            btnInvoice.OnDisabledState.BorderColor = Color.FromArgb(191, 191, 191);
            btnInvoice.OnDisabledState.BorderRadius = 1;
            btnInvoice.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnInvoice.OnDisabledState.BorderThickness = 1;
            btnInvoice.OnDisabledState.FillColor = Color.FromArgb(204, 204, 204);
            btnInvoice.OnDisabledState.ForeColor = Color.FromArgb(168, 160, 168);
            btnInvoice.OnDisabledState.IconLeftImage = null;
            btnInvoice.OnDisabledState.IconRightImage = null;
            btnInvoice.onHoverState.BorderColor = Color.DarkGoldenrod;
            btnInvoice.onHoverState.BorderRadius = 1;
            btnInvoice.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnInvoice.onHoverState.BorderThickness = 1;
            btnInvoice.onHoverState.FillColor = Color.White;
            btnInvoice.onHoverState.ForeColor = Color.White;
            btnInvoice.onHoverState.IconLeftImage = null;
            btnInvoice.onHoverState.IconRightImage = null;
            btnInvoice.OnIdleState.BorderColor = Color.White;
            btnInvoice.OnIdleState.BorderRadius = 1;
            btnInvoice.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnInvoice.OnIdleState.BorderThickness = 1;
            btnInvoice.OnIdleState.FillColor = Color.White;
            btnInvoice.OnIdleState.ForeColor = Color.White;
            btnInvoice.OnIdleState.IconLeftImage = Properties.Resources.report;
            btnInvoice.OnIdleState.IconRightImage = null;
            btnInvoice.OnPressedState.BorderColor = Color.DarkGoldenrod;
            btnInvoice.OnPressedState.BorderRadius = 1;
            btnInvoice.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnInvoice.OnPressedState.BorderThickness = 1;
            btnInvoice.OnPressedState.FillColor = Color.White;
            btnInvoice.OnPressedState.ForeColor = Color.White;
            btnInvoice.OnPressedState.IconLeftImage = null;
            btnInvoice.OnPressedState.IconRightImage = null;
            btnInvoice.Size = new Size(61, 58);
            btnInvoice.TabIndex = 5;
            btnInvoice.TextAlign = ContentAlignment.MiddleCenter;
            btnInvoice.TextAlignment = HorizontalAlignment.Center;
            btnInvoice.TextMarginLeft = 0;
            btnInvoice.TextPadding = new Padding(0);
            btnInvoice.UseDefaultRadiusAndThickness = true;
            // 
            // btnStatistic
            // 
            btnStatistic.AllowAnimations = true;
            btnStatistic.AllowMouseEffects = true;
            btnStatistic.AllowToggling = false;
            btnStatistic.AnimationSpeed = 200;
            btnStatistic.AutoGenerateColors = false;
            btnStatistic.AutoRoundBorders = false;
            btnStatistic.AutoSizeLeftIcon = true;
            btnStatistic.AutoSizeRightIcon = true;
            btnStatistic.BackColor = Color.Transparent;
            btnStatistic.BackColor1 = Color.White;
            btnStatistic.BackgroundImage = (Image)resources.GetObject("btnStatistic.BackgroundImage");
            btnStatistic.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnStatistic.ButtonText = "";
            btnStatistic.ButtonTextMarginLeft = 0;
            btnStatistic.ColorContrastOnClick = 45;
            btnStatistic.ColorContrastOnHover = 45;
            btnStatistic.Cursor = Cursors.Hand;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            btnStatistic.CustomizableEdges = borderEdges6;
            btnStatistic.DialogResult = DialogResult.None;
            btnStatistic.DisabledBorderColor = Color.FromArgb(191, 191, 191);
            btnStatistic.DisabledFillColor = Color.FromArgb(204, 204, 204);
            btnStatistic.DisabledForecolor = Color.FromArgb(168, 160, 168);
            btnStatistic.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            btnStatistic.Font = new Font("Segoe UI", 9F);
            btnStatistic.ForeColor = Color.White;
            btnStatistic.IconLeftAlign = ContentAlignment.MiddleLeft;
            btnStatistic.IconLeftCursor = Cursors.Default;
            btnStatistic.IconLeftPadding = new Padding(11, 3, 3, 3);
            btnStatistic.IconMarginLeft = 11;
            btnStatistic.IconPadding = 12;
            btnStatistic.IconRightAlign = ContentAlignment.MiddleRight;
            btnStatistic.IconRightCursor = Cursors.Default;
            btnStatistic.IconRightPadding = new Padding(3, 3, 7, 3);
            btnStatistic.IconSize = 25;
            btnStatistic.IdleBorderColor = Color.White;
            btnStatistic.IdleBorderRadius = 1;
            btnStatistic.IdleBorderThickness = 1;
            btnStatistic.IdleFillColor = Color.White;
            btnStatistic.IdleIconLeftImage = Properties.Resources._3d;
            btnStatistic.IdleIconRightImage = null;
            btnStatistic.IndicateFocus = false;
            btnStatistic.Location = new Point(15, 200);
            btnStatistic.Name = "btnStatistic";
            btnStatistic.OnDisabledState.BorderColor = Color.FromArgb(191, 191, 191);
            btnStatistic.OnDisabledState.BorderRadius = 1;
            btnStatistic.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnStatistic.OnDisabledState.BorderThickness = 1;
            btnStatistic.OnDisabledState.FillColor = Color.FromArgb(204, 204, 204);
            btnStatistic.OnDisabledState.ForeColor = Color.FromArgb(168, 160, 168);
            btnStatistic.OnDisabledState.IconLeftImage = null;
            btnStatistic.OnDisabledState.IconRightImage = null;
            btnStatistic.onHoverState.BorderColor = Color.DarkGoldenrod;
            btnStatistic.onHoverState.BorderRadius = 1;
            btnStatistic.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnStatistic.onHoverState.BorderThickness = 1;
            btnStatistic.onHoverState.FillColor = Color.White;
            btnStatistic.onHoverState.ForeColor = Color.White;
            btnStatistic.onHoverState.IconLeftImage = null;
            btnStatistic.onHoverState.IconRightImage = null;
            btnStatistic.OnIdleState.BorderColor = Color.White;
            btnStatistic.OnIdleState.BorderRadius = 1;
            btnStatistic.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnStatistic.OnIdleState.BorderThickness = 1;
            btnStatistic.OnIdleState.FillColor = Color.White;
            btnStatistic.OnIdleState.ForeColor = Color.White;
            btnStatistic.OnIdleState.IconLeftImage = Properties.Resources._3d;
            btnStatistic.OnIdleState.IconRightImage = null;
            btnStatistic.OnPressedState.BorderColor = Color.DarkGoldenrod;
            btnStatistic.OnPressedState.BorderRadius = 1;
            btnStatistic.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnStatistic.OnPressedState.BorderThickness = 1;
            btnStatistic.OnPressedState.FillColor = Color.White;
            btnStatistic.OnPressedState.ForeColor = Color.White;
            btnStatistic.OnPressedState.IconLeftImage = null;
            btnStatistic.OnPressedState.IconRightImage = null;
            btnStatistic.Size = new Size(61, 58);
            btnStatistic.TabIndex = 4;
            btnStatistic.TextAlign = ContentAlignment.MiddleCenter;
            btnStatistic.TextAlignment = HorizontalAlignment.Center;
            btnStatistic.TextMarginLeft = 0;
            btnStatistic.TextPadding = new Padding(0);
            btnStatistic.UseDefaultRadiusAndThickness = true;
            btnStatistic.Click += btnStatistic_Click;
            // 
            // btnAllForm
            // 
            btnAllForm.AllowAnimations = true;
            btnAllForm.AllowMouseEffects = true;
            btnAllForm.AllowToggling = false;
            btnAllForm.AnimationSpeed = 200;
            btnAllForm.AutoGenerateColors = false;
            btnAllForm.AutoRoundBorders = false;
            btnAllForm.AutoSizeLeftIcon = true;
            btnAllForm.AutoSizeRightIcon = true;
            btnAllForm.BackColor = Color.Transparent;
            btnAllForm.BackColor1 = Color.White;
            btnAllForm.BackgroundImage = (Image)resources.GetObject("btnAllForm.BackgroundImage");
            btnAllForm.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnAllForm.ButtonText = "";
            btnAllForm.ButtonTextMarginLeft = 0;
            btnAllForm.ColorContrastOnClick = 45;
            btnAllForm.ColorContrastOnHover = 45;
            btnAllForm.Cursor = Cursors.Hand;
            borderEdges7.BottomLeft = true;
            borderEdges7.BottomRight = true;
            borderEdges7.TopLeft = true;
            borderEdges7.TopRight = true;
            btnAllForm.CustomizableEdges = borderEdges7;
            btnAllForm.DialogResult = DialogResult.None;
            btnAllForm.DisabledBorderColor = Color.FromArgb(191, 191, 191);
            btnAllForm.DisabledFillColor = Color.FromArgb(204, 204, 204);
            btnAllForm.DisabledForecolor = Color.FromArgb(168, 160, 168);
            btnAllForm.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            btnAllForm.Font = new Font("Segoe UI", 9F);
            btnAllForm.ForeColor = Color.White;
            btnAllForm.IconLeftAlign = ContentAlignment.MiddleLeft;
            btnAllForm.IconLeftCursor = Cursors.Default;
            btnAllForm.IconLeftPadding = new Padding(11, 3, 3, 3);
            btnAllForm.IconMarginLeft = 11;
            btnAllForm.IconPadding = 12;
            btnAllForm.IconRightAlign = ContentAlignment.MiddleRight;
            btnAllForm.IconRightCursor = Cursors.Default;
            btnAllForm.IconRightPadding = new Padding(3, 3, 7, 3);
            btnAllForm.IconSize = 25;
            btnAllForm.IdleBorderColor = Color.White;
            btnAllForm.IdleBorderRadius = 1;
            btnAllForm.IdleBorderThickness = 1;
            btnAllForm.IdleFillColor = Color.White;
            btnAllForm.IdleIconLeftImage = Properties.Resources.dashboard;
            btnAllForm.IdleIconRightImage = null;
            btnAllForm.IndicateFocus = false;
            btnAllForm.Location = new Point(15, 137);
            btnAllForm.Name = "btnAllForm";
            btnAllForm.OnDisabledState.BorderColor = Color.FromArgb(191, 191, 191);
            btnAllForm.OnDisabledState.BorderRadius = 1;
            btnAllForm.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnAllForm.OnDisabledState.BorderThickness = 1;
            btnAllForm.OnDisabledState.FillColor = Color.FromArgb(204, 204, 204);
            btnAllForm.OnDisabledState.ForeColor = Color.FromArgb(168, 160, 168);
            btnAllForm.OnDisabledState.IconLeftImage = null;
            btnAllForm.OnDisabledState.IconRightImage = null;
            btnAllForm.onHoverState.BorderColor = Color.DarkGoldenrod;
            btnAllForm.onHoverState.BorderRadius = 1;
            btnAllForm.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnAllForm.onHoverState.BorderThickness = 1;
            btnAllForm.onHoverState.FillColor = Color.White;
            btnAllForm.onHoverState.ForeColor = Color.White;
            btnAllForm.onHoverState.IconLeftImage = null;
            btnAllForm.onHoverState.IconRightImage = null;
            btnAllForm.OnIdleState.BorderColor = Color.White;
            btnAllForm.OnIdleState.BorderRadius = 1;
            btnAllForm.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnAllForm.OnIdleState.BorderThickness = 1;
            btnAllForm.OnIdleState.FillColor = Color.White;
            btnAllForm.OnIdleState.ForeColor = Color.White;
            btnAllForm.OnIdleState.IconLeftImage = Properties.Resources.dashboard;
            btnAllForm.OnIdleState.IconRightImage = null;
            btnAllForm.OnPressedState.BorderColor = Color.DarkGoldenrod;
            btnAllForm.OnPressedState.BorderRadius = 1;
            btnAllForm.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnAllForm.OnPressedState.BorderThickness = 1;
            btnAllForm.OnPressedState.FillColor = Color.White;
            btnAllForm.OnPressedState.ForeColor = Color.White;
            btnAllForm.OnPressedState.IconLeftImage = null;
            btnAllForm.OnPressedState.IconRightImage = null;
            btnAllForm.Size = new Size(61, 58);
            btnAllForm.TabIndex = 3;
            btnAllForm.TextAlign = ContentAlignment.MiddleCenter;
            btnAllForm.TextAlignment = HorizontalAlignment.Center;
            btnAllForm.TextMarginLeft = 0;
            btnAllForm.TextPadding = new Padding(0);
            btnAllForm.UseDefaultRadiusAndThickness = true;
            // 
            // LogoImage
            // 
            LogoImage.AllowFocused = false;
            LogoImage.Anchor = AnchorStyles.None;
            LogoImage.AutoSizeHeight = true;
            LogoImage.BackColor = Color.White;
            LogoImage.BorderRadius = 35;
            LogoImage.Image = Properties.Resources.logo;
            LogoImage.InitialImage = null;
            LogoImage.IsCircle = true;
            LogoImage.Location = new Point(6, 11);
            LogoImage.Name = "LogoImage";
            LogoImage.Size = new Size(70, 70);
            LogoImage.SizeMode = PictureBoxSizeMode.Zoom;
            LogoImage.TabIndex = 2;
            LogoImage.TabStop = false;
            LogoImage.Type = Bunifu.UI.WinForms.BunifuPictureBox.Types.Circle;
            // 
            // bunifuPanel2
            // 
            bunifuPanel2.BackgroundColor = Color.White;
            bunifuPanel2.BackgroundImage = (Image)resources.GetObject("bunifuPanel2.BackgroundImage");
            bunifuPanel2.BackgroundImageLayout = ImageLayout.Stretch;
            bunifuPanel2.BorderColor = Color.White;
            bunifuPanel2.BorderRadius = 3;
            bunifuPanel2.BorderThickness = 1;
            bunifuPanel2.Controls.Add(panOrderDetailOuter);
            bunifuPanel2.Controls.Add(txtCardStatus);
            bunifuPanel2.Controls.Add(txtCustomerID);
            bunifuPanel2.Controls.Add(btnCheckout);
            bunifuPanel2.Controls.Add(bunifuPanel9);
            bunifuPanel2.Controls.Add(bunifuLabel27);
            bunifuPanel2.Controls.Add(btnExitProgram);
            bunifuPanel2.Dock = DockStyle.Right;
            bunifuPanel2.Location = new Point(1105, 0);
            bunifuPanel2.Name = "bunifuPanel2";
            bunifuPanel2.ShowBorders = true;
            bunifuPanel2.Size = new Size(281, 788);
            bunifuPanel2.TabIndex = 1;
            // 
            // panOrderDetailOuter
            // 
            panOrderDetailOuter.BackgroundColor = Color.White;
            panOrderDetailOuter.BackgroundImage = (Image)resources.GetObject("panOrderDetailOuter.BackgroundImage");
            panOrderDetailOuter.BackgroundImageLayout = ImageLayout.Stretch;
            panOrderDetailOuter.BorderColor = Color.White;
            panOrderDetailOuter.BorderRadius = 3;
            panOrderDetailOuter.BorderThickness = 1;
            panOrderDetailOuter.Location = new Point(13, 180);
            panOrderDetailOuter.Name = "panOrderDetailOuter";
            panOrderDetailOuter.ShowBorders = true;
            panOrderDetailOuter.Size = new Size(241, 268);
            panOrderDetailOuter.TabIndex = 20;
            // 
            // txtCardStatus
            // 
            txtCardStatus.AllowParentOverrides = false;
            txtCardStatus.AutoEllipsis = false;
            txtCardStatus.CursorType = Cursors.Default;
            txtCardStatus.Font = new Font("Verdana", 9F, FontStyle.Regular, GraphicsUnit.Point, 0);
            txtCardStatus.Location = new Point(136, 149);
            txtCardStatus.Name = "txtCardStatus";
            txtCardStatus.RightToLeft = RightToLeft.No;
            txtCardStatus.Size = new Size(50, 14);
            txtCardStatus.TabIndex = 28;
            txtCardStatus.Text = "Status :";
            txtCardStatus.TextAlignment = ContentAlignment.TopLeft;
            txtCardStatus.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // txtCustomerID
            // 
            txtCustomerID.AcceptsReturn = false;
            txtCustomerID.AcceptsTab = false;
            txtCustomerID.AnimationSpeed = 200;
            txtCustomerID.AutoCompleteMode = AutoCompleteMode.None;
            txtCustomerID.AutoCompleteSource = AutoCompleteSource.None;
            txtCustomerID.AutoSizeHeight = true;
            txtCustomerID.BackColor = Color.Transparent;
            txtCustomerID.BackgroundImage = (Image)resources.GetObject("txtCustomerID.BackgroundImage");
            txtCustomerID.BorderColorActive = Color.DarkGoldenrod;
            txtCustomerID.BorderColorDisabled = Color.FromArgb(204, 204, 204);
            txtCustomerID.BorderColorHover = Color.DarkGoldenrod;
            txtCustomerID.BorderColorIdle = Color.Silver;
            txtCustomerID.BorderRadius = 15;
            txtCustomerID.BorderThickness = 1;
            txtCustomerID.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            txtCustomerID.CharacterCasing = CharacterCasing.Normal;
            txtCustomerID.DefaultFont = new Font("Verdana", 9F, FontStyle.Regular, GraphicsUnit.Point, 0);
            txtCustomerID.DefaultText = "";
            txtCustomerID.FillColor = Color.White;
            txtCustomerID.HideSelection = true;
            txtCustomerID.IconLeft = null;
            txtCustomerID.IconLeftCursor = Cursors.IBeam;
            txtCustomerID.IconPadding = 10;
            txtCustomerID.IconRight = null;
            txtCustomerID.IconRightCursor = Cursors.IBeam;
            txtCustomerID.Location = new Point(13, 137);
            txtCustomerID.MaxLength = 32767;
            txtCustomerID.MinimumSize = new Size(1, 1);
            txtCustomerID.Modified = false;
            txtCustomerID.Multiline = false;
            txtCustomerID.Name = "txtCustomerID";
            stateProperties1.BorderColor = Color.DarkGoldenrod;
            stateProperties1.FillColor = Color.Empty;
            stateProperties1.ForeColor = Color.Empty;
            stateProperties1.PlaceholderForeColor = Color.Empty;
            txtCustomerID.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = Color.FromArgb(204, 204, 204);
            stateProperties2.FillColor = Color.FromArgb(240, 240, 240);
            stateProperties2.ForeColor = Color.FromArgb(109, 109, 109);
            stateProperties2.PlaceholderForeColor = Color.DarkGray;
            txtCustomerID.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = Color.DarkGoldenrod;
            stateProperties3.FillColor = Color.Empty;
            stateProperties3.ForeColor = Color.Empty;
            stateProperties3.PlaceholderForeColor = Color.Empty;
            txtCustomerID.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = Color.Silver;
            stateProperties4.FillColor = Color.White;
            stateProperties4.ForeColor = Color.Empty;
            stateProperties4.PlaceholderForeColor = Color.Empty;
            txtCustomerID.OnIdleState = stateProperties4;
            txtCustomerID.Padding = new Padding(3);
            txtCustomerID.PasswordChar = '\0';
            txtCustomerID.PlaceholderForeColor = Color.Silver;
            txtCustomerID.PlaceholderText = "Customer ID:";
            txtCustomerID.ReadOnly = false;
            txtCustomerID.ScrollBars = ScrollBars.None;
            txtCustomerID.SelectedText = "";
            txtCustomerID.SelectionLength = 0;
            txtCustomerID.SelectionStart = 0;
            txtCustomerID.ShortcutsEnabled = true;
            txtCustomerID.Size = new Size(108, 37);
            txtCustomerID.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            txtCustomerID.TabIndex = 27;
            txtCustomerID.TextAlign = HorizontalAlignment.Left;
            txtCustomerID.TextMarginBottom = 0;
            txtCustomerID.TextMarginLeft = 3;
            txtCustomerID.TextMarginTop = 1;
            txtCustomerID.TextPlaceholder = "Customer ID:";
            txtCustomerID.UseSystemPasswordChar = false;
            txtCustomerID.WordWrap = true;
            // 
            // btnCheckout
            // 
            btnCheckout.AllowAnimations = true;
            btnCheckout.AllowMouseEffects = true;
            btnCheckout.AllowToggling = false;
            btnCheckout.AnimationSpeed = 200;
            btnCheckout.AutoGenerateColors = false;
            btnCheckout.AutoRoundBorders = false;
            btnCheckout.AutoSizeLeftIcon = true;
            btnCheckout.AutoSizeRightIcon = true;
            btnCheckout.BackColor = Color.Transparent;
            btnCheckout.BackColor1 = Color.DarkGoldenrod;
            btnCheckout.BackgroundImage = (Image)resources.GetObject("btnCheckout.BackgroundImage");
            btnCheckout.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnCheckout.ButtonText = "Continue to Payment";
            btnCheckout.ButtonTextMarginLeft = 0;
            btnCheckout.ColorContrastOnClick = 45;
            btnCheckout.ColorContrastOnHover = 45;
            borderEdges8.BottomLeft = true;
            borderEdges8.BottomRight = true;
            borderEdges8.TopLeft = true;
            borderEdges8.TopRight = true;
            btnCheckout.CustomizableEdges = borderEdges8;
            btnCheckout.DialogResult = DialogResult.None;
            btnCheckout.DisabledBorderColor = Color.FromArgb(191, 191, 191);
            btnCheckout.DisabledFillColor = Color.FromArgb(204, 204, 204);
            btnCheckout.DisabledForecolor = Color.FromArgb(168, 160, 168);
            btnCheckout.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            btnCheckout.Font = new Font("Verdana", 9.75F, FontStyle.Bold, GraphicsUnit.Point, 0);
            btnCheckout.ForeColor = Color.White;
            btnCheckout.IconLeftAlign = ContentAlignment.MiddleLeft;
            btnCheckout.IconLeftCursor = Cursors.Default;
            btnCheckout.IconLeftPadding = new Padding(15, 3, 3, 3);
            btnCheckout.IconMarginLeft = 11;
            btnCheckout.IconPadding = 10;
            btnCheckout.IconRightAlign = ContentAlignment.MiddleRight;
            btnCheckout.IconRightCursor = Cursors.Default;
            btnCheckout.IconRightPadding = new Padding(3, 3, 7, 3);
            btnCheckout.IconSize = 25;
            btnCheckout.IdleBorderColor = Color.DarkGoldenrod;
            btnCheckout.IdleBorderRadius = 15;
            btnCheckout.IdleBorderThickness = 1;
            btnCheckout.IdleFillColor = Color.DarkGoldenrod;
            btnCheckout.IdleIconLeftImage = null;
            btnCheckout.IdleIconRightImage = null;
            btnCheckout.IndicateFocus = false;
            btnCheckout.Location = new Point(13, 724);
            btnCheckout.Name = "btnCheckout";
            btnCheckout.OnDisabledState.BorderColor = Color.FromArgb(191, 191, 191);
            btnCheckout.OnDisabledState.BorderRadius = 15;
            btnCheckout.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnCheckout.OnDisabledState.BorderThickness = 1;
            btnCheckout.OnDisabledState.FillColor = Color.FromArgb(204, 204, 204);
            btnCheckout.OnDisabledState.ForeColor = Color.FromArgb(168, 160, 168);
            btnCheckout.OnDisabledState.IconLeftImage = null;
            btnCheckout.OnDisabledState.IconRightImage = null;
            btnCheckout.onHoverState.BorderColor = Color.DarkGoldenrod;
            btnCheckout.onHoverState.BorderRadius = 15;
            btnCheckout.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnCheckout.onHoverState.BorderThickness = 1;
            btnCheckout.onHoverState.FillColor = Color.White;
            btnCheckout.onHoverState.ForeColor = Color.White;
            btnCheckout.onHoverState.IconLeftImage = null;
            btnCheckout.onHoverState.IconRightImage = null;
            btnCheckout.OnIdleState.BorderColor = Color.DarkGoldenrod;
            btnCheckout.OnIdleState.BorderRadius = 15;
            btnCheckout.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnCheckout.OnIdleState.BorderThickness = 1;
            btnCheckout.OnIdleState.FillColor = Color.DarkGoldenrod;
            btnCheckout.OnIdleState.ForeColor = Color.White;
            btnCheckout.OnIdleState.IconLeftImage = null;
            btnCheckout.OnIdleState.IconRightImage = null;
            btnCheckout.OnPressedState.BorderColor = Color.Lime;
            btnCheckout.OnPressedState.BorderRadius = 15;
            btnCheckout.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnCheckout.OnPressedState.BorderThickness = 1;
            btnCheckout.OnPressedState.FillColor = Color.White;
            btnCheckout.OnPressedState.ForeColor = Color.White;
            btnCheckout.OnPressedState.IconLeftImage = null;
            btnCheckout.OnPressedState.IconRightImage = null;
            btnCheckout.Size = new Size(241, 39);
            btnCheckout.TabIndex = 26;
            btnCheckout.TextAlign = ContentAlignment.MiddleCenter;
            btnCheckout.TextAlignment = HorizontalAlignment.Center;
            btnCheckout.TextMarginLeft = 0;
            btnCheckout.TextPadding = new Padding(0);
            btnCheckout.UseDefaultRadiusAndThickness = true;
            // 
            // bunifuPanel9
            // 
            bunifuPanel9.BackgroundColor = Color.Transparent;
            bunifuPanel9.BackgroundImage = (Image)resources.GetObject("bunifuPanel9.BackgroundImage");
            bunifuPanel9.BackgroundImageLayout = ImageLayout.Stretch;
            bunifuPanel9.BorderColor = Color.Transparent;
            bunifuPanel9.BorderRadius = 15;
            bunifuPanel9.BorderThickness = 1;
            bunifuPanel9.Controls.Add(bunifuLabel40);
            bunifuPanel9.Controls.Add(bunifuSeparator1);
            bunifuPanel9.Controls.Add(bunifuLabel38);
            bunifuPanel9.Controls.Add(bunifuLabel36);
            bunifuPanel9.Controls.Add(bunifuLabel37);
            bunifuPanel9.Controls.Add(bunifuLabel35);
            bunifuPanel9.Controls.Add(bunifuLabel34);
            bunifuPanel9.Cursor = Cursors.IBeam;
            bunifuPanel9.Location = new Point(13, 507);
            bunifuPanel9.Name = "bunifuPanel9";
            bunifuPanel9.ShowBorders = true;
            bunifuPanel9.Size = new Size(241, 189);
            bunifuPanel9.TabIndex = 25;
            // 
            // bunifuLabel40
            // 
            bunifuLabel40.AllowParentOverrides = false;
            bunifuLabel40.AutoEllipsis = false;
            bunifuLabel40.CursorType = Cursors.Default;
            bunifuLabel40.Font = new Font("Verdana", 14.25F, FontStyle.Bold, GraphicsUnit.Point, 0);
            bunifuLabel40.Location = new Point(15, 127);
            bunifuLabel40.Name = "bunifuLabel40";
            bunifuLabel40.RightToLeft = RightToLeft.No;
            bunifuLabel40.Size = new Size(55, 23);
            bunifuLabel40.TabIndex = 26;
            bunifuLabel40.Text = "Total";
            bunifuLabel40.TextAlignment = ContentAlignment.TopLeft;
            bunifuLabel40.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuSeparator1
            // 
            bunifuSeparator1.BackColor = Color.Transparent;
            bunifuSeparator1.BackgroundImage = (Image)resources.GetObject("bunifuSeparator1.BackgroundImage");
            bunifuSeparator1.BackgroundImageLayout = ImageLayout.Stretch;
            bunifuSeparator1.DashCap = Bunifu.UI.WinForms.BunifuSeparator.CapStyles.Flat;
            bunifuSeparator1.LineColor = Color.Silver;
            bunifuSeparator1.LineStyle = Bunifu.UI.WinForms.BunifuSeparator.LineStyles.Solid;
            bunifuSeparator1.LineThickness = 1;
            bunifuSeparator1.Location = new Point(15, 100);
            bunifuSeparator1.Margin = new Padding(4, 3, 4, 3);
            bunifuSeparator1.Name = "bunifuSeparator1";
            bunifuSeparator1.Orientation = Bunifu.UI.WinForms.BunifuSeparator.LineOrientation.Horizontal;
            bunifuSeparator1.Size = new Size(195, 12);
            bunifuSeparator1.TabIndex = 31;
            // 
            // bunifuLabel38
            // 
            bunifuLabel38.AllowParentOverrides = false;
            bunifuLabel38.AutoEllipsis = false;
            bunifuLabel38.CursorType = Cursors.Default;
            bunifuLabel38.Font = new Font("Verdana", 14.25F, FontStyle.Bold, GraphicsUnit.Point, 0);
            bunifuLabel38.ForeColor = SystemColors.ControlText;
            bunifuLabel38.Location = new Point(158, 127);
            bunifuLabel38.Name = "bunifuLabel38";
            bunifuLabel38.RightToLeft = RightToLeft.No;
            bunifuLabel38.Size = new Size(61, 23);
            bunifuLabel38.TabIndex = 30;
            bunifuLabel38.Text = "$Cost";
            bunifuLabel38.TextAlignment = ContentAlignment.TopLeft;
            bunifuLabel38.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel36
            // 
            bunifuLabel36.AllowParentOverrides = false;
            bunifuLabel36.AutoEllipsis = false;
            bunifuLabel36.CursorType = Cursors.Default;
            bunifuLabel36.Font = new Font("Verdana", 11.25F, FontStyle.Bold, GraphicsUnit.Point, 0);
            bunifuLabel36.ForeColor = SystemColors.ControlText;
            bunifuLabel36.Location = new Point(170, 66);
            bunifuLabel36.Name = "bunifuLabel36";
            bunifuLabel36.RightToLeft = RightToLeft.No;
            bunifuLabel36.Size = new Size(48, 18);
            bunifuLabel36.TabIndex = 28;
            bunifuLabel36.Text = "$Cost";
            bunifuLabel36.TextAlignment = ContentAlignment.TopLeft;
            bunifuLabel36.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel37
            // 
            bunifuLabel37.AllowParentOverrides = false;
            bunifuLabel37.AutoEllipsis = false;
            bunifuLabel37.CursorType = Cursors.Default;
            bunifuLabel37.Font = new Font("Verdana", 12F, FontStyle.Bold, GraphicsUnit.Point, 0);
            bunifuLabel37.ForeColor = SystemColors.ActiveBorder;
            bunifuLabel37.Location = new Point(15, 65);
            bunifuLabel37.Name = "bunifuLabel37";
            bunifuLabel37.RightToLeft = RightToLeft.No;
            bunifuLabel37.Size = new Size(75, 18);
            bunifuLabel37.TabIndex = 27;
            bunifuLabel37.Text = "Discount";
            bunifuLabel37.TextAlignment = ContentAlignment.TopLeft;
            bunifuLabel37.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel35
            // 
            bunifuLabel35.AllowParentOverrides = false;
            bunifuLabel35.AutoEllipsis = false;
            bunifuLabel35.CursorType = Cursors.Default;
            bunifuLabel35.Font = new Font("Verdana", 11.25F, FontStyle.Bold, GraphicsUnit.Point, 0);
            bunifuLabel35.ForeColor = SystemColors.ControlText;
            bunifuLabel35.Location = new Point(170, 28);
            bunifuLabel35.Name = "bunifuLabel35";
            bunifuLabel35.RightToLeft = RightToLeft.No;
            bunifuLabel35.Size = new Size(48, 18);
            bunifuLabel35.TabIndex = 26;
            bunifuLabel35.Text = "$Cost";
            bunifuLabel35.TextAlignment = ContentAlignment.TopLeft;
            bunifuLabel35.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel34
            // 
            bunifuLabel34.AllowParentOverrides = false;
            bunifuLabel34.AutoEllipsis = false;
            bunifuLabel34.CursorType = Cursors.Default;
            bunifuLabel34.Font = new Font("Verdana", 12F, FontStyle.Bold, GraphicsUnit.Point, 0);
            bunifuLabel34.ForeColor = SystemColors.ActiveBorder;
            bunifuLabel34.Location = new Point(15, 28);
            bunifuLabel34.Name = "bunifuLabel34";
            bunifuLabel34.RightToLeft = RightToLeft.No;
            bunifuLabel34.Size = new Size(73, 18);
            bunifuLabel34.TabIndex = 4;
            bunifuLabel34.Text = "Subtotal";
            bunifuLabel34.TextAlignment = ContentAlignment.TopLeft;
            bunifuLabel34.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel27
            // 
            bunifuLabel27.AllowParentOverrides = false;
            bunifuLabel27.AutoEllipsis = false;
            bunifuLabel27.CursorType = Cursors.Default;
            bunifuLabel27.Font = new Font("Verdana", 15.75F, FontStyle.Bold, GraphicsUnit.Point, 0);
            bunifuLabel27.Location = new Point(13, 43);
            bunifuLabel27.Name = "bunifuLabel27";
            bunifuLabel27.RightToLeft = RightToLeft.No;
            bunifuLabel27.Size = new Size(163, 25);
            bunifuLabel27.TabIndex = 3;
            bunifuLabel27.Text = "Current Order";
            bunifuLabel27.TextAlignment = ContentAlignment.TopLeft;
            bunifuLabel27.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // btnExitProgram
            // 
            btnExitProgram.AllowAnimations = true;
            btnExitProgram.AllowBorderColorChanges = true;
            btnExitProgram.AllowMouseEffects = true;
            btnExitProgram.AnimationSpeed = 200;
            btnExitProgram.BackColor = Color.Transparent;
            btnExitProgram.BackgroundColor = Color.White;
            btnExitProgram.BorderColor = Color.White;
            btnExitProgram.BorderRadius = 1;
            btnExitProgram.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuIconButton.BorderStyles.Solid;
            btnExitProgram.BorderThickness = 1;
            btnExitProgram.ColorContrastOnClick = 0;
            btnExitProgram.ColorContrastOnHover = 0;
            borderEdges9.BottomLeft = true;
            borderEdges9.BottomRight = true;
            borderEdges9.TopLeft = true;
            borderEdges9.TopRight = true;
            btnExitProgram.CustomizableEdges = borderEdges9;
            btnExitProgram.DialogResult = DialogResult.None;
            btnExitProgram.Image = (Image)resources.GetObject("btnExitProgram.Image");
            btnExitProgram.ImageMargin = new Padding(0);
            btnExitProgram.Location = new Point(218, 11);
            btnExitProgram.Name = "btnExitProgram";
            btnExitProgram.RoundBorders = true;
            btnExitProgram.ShowBorders = true;
            btnExitProgram.Size = new Size(26, 26);
            btnExitProgram.Style = Bunifu.UI.WinForms.BunifuButton.BunifuIconButton.ButtonStyles.Round;
            btnExitProgram.TabIndex = 0;
            // 
            // bunifuLabel1
            // 
            bunifuLabel1.AllowParentOverrides = false;
            bunifuLabel1.AutoEllipsis = false;
            bunifuLabel1.CursorType = Cursors.Default;
            bunifuLabel1.Font = new Font("Verdana", 15.75F, FontStyle.Regular, GraphicsUnit.Point, 0);
            bunifuLabel1.Location = new Point(123, 12);
            bunifuLabel1.Name = "bunifuLabel1";
            bunifuLabel1.RightToLeft = RightToLeft.No;
            bunifuLabel1.Size = new Size(169, 25);
            bunifuLabel1.TabIndex = 2;
            bunifuLabel1.Text = "Welcome, Menu";
            bunifuLabel1.TextAlignment = ContentAlignment.TopLeft;
            bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel2
            // 
            bunifuLabel2.AllowParentOverrides = false;
            bunifuLabel2.AutoEllipsis = false;
            bunifuLabel2.CursorType = Cursors.Default;
            bunifuLabel2.Font = new Font("Verdana", 12F, FontStyle.Regular, GraphicsUnit.Point, 0);
            bunifuLabel2.ForeColor = Color.DarkGoldenrod;
            bunifuLabel2.Location = new Point(123, 43);
            bunifuLabel2.Name = "bunifuLabel2";
            bunifuLabel2.RightToLeft = RightToLeft.No;
            bunifuLabel2.Size = new Size(285, 18);
            bunifuLabel2.TabIndex = 3;
            bunifuLabel2.Text = "Discover whatever you need easily";
            bunifuLabel2.TextAlignment = ContentAlignment.TopLeft;
            bunifuLabel2.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // txtSearch
            // 
            txtSearch.AcceptsReturn = false;
            txtSearch.AcceptsTab = false;
            txtSearch.AnimationSpeed = 200;
            txtSearch.AutoCompleteMode = AutoCompleteMode.None;
            txtSearch.AutoCompleteSource = AutoCompleteSource.None;
            txtSearch.AutoSizeHeight = true;
            txtSearch.BackColor = Color.Transparent;
            txtSearch.BackgroundImage = (Image)resources.GetObject("txtSearch.BackgroundImage");
            txtSearch.BorderColorActive = Color.DarkGoldenrod;
            txtSearch.BorderColorDisabled = Color.FromArgb(204, 204, 204);
            txtSearch.BorderColorHover = Color.DarkGoldenrod;
            txtSearch.BorderColorIdle = Color.Silver;
            txtSearch.BorderRadius = 15;
            txtSearch.BorderThickness = 1;
            txtSearch.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            txtSearch.CharacterCasing = CharacterCasing.Normal;
            txtSearch.DefaultFont = new Font("Verdana", 9.75F, FontStyle.Bold, GraphicsUnit.Point, 0);
            txtSearch.DefaultText = "";
            txtSearch.FillColor = Color.White;
            txtSearch.HideSelection = true;
            txtSearch.IconLeft = Properties.Resources._3d_magnifier;
            txtSearch.IconLeftCursor = Cursors.IBeam;
            txtSearch.IconPadding = 12;
            txtSearch.IconRight = null;
            txtSearch.IconRightCursor = Cursors.IBeam;
            txtSearch.Location = new Point(822, 58);
            txtSearch.MaxLength = 32767;
            txtSearch.MinimumSize = new Size(1, 1);
            txtSearch.Modified = false;
            txtSearch.Multiline = false;
            txtSearch.Name = "txtSearch";
            stateProperties5.BorderColor = Color.DarkGoldenrod;
            stateProperties5.FillColor = Color.Empty;
            stateProperties5.ForeColor = Color.Empty;
            stateProperties5.PlaceholderForeColor = Color.Empty;
            txtSearch.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = Color.FromArgb(204, 204, 204);
            stateProperties6.FillColor = Color.FromArgb(240, 240, 240);
            stateProperties6.ForeColor = Color.FromArgb(109, 109, 109);
            stateProperties6.PlaceholderForeColor = Color.DarkGray;
            txtSearch.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = Color.DarkGoldenrod;
            stateProperties7.FillColor = Color.Empty;
            stateProperties7.ForeColor = Color.Empty;
            stateProperties7.PlaceholderForeColor = Color.Empty;
            txtSearch.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = Color.Silver;
            stateProperties8.FillColor = Color.White;
            stateProperties8.ForeColor = Color.Empty;
            stateProperties8.PlaceholderForeColor = Color.Empty;
            txtSearch.OnIdleState = stateProperties8;
            txtSearch.Padding = new Padding(3);
            txtSearch.PasswordChar = '\0';
            txtSearch.PlaceholderForeColor = Color.Silver;
            txtSearch.PlaceholderText = "Search product ...";
            txtSearch.ReadOnly = false;
            txtSearch.ScrollBars = ScrollBars.None;
            txtSearch.SelectedText = "";
            txtSearch.SelectionLength = 0;
            txtSearch.SelectionStart = 0;
            txtSearch.ShortcutsEnabled = true;
            txtSearch.Size = new Size(260, 38);
            txtSearch.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            txtSearch.TabIndex = 4;
            txtSearch.TextAlign = HorizontalAlignment.Left;
            txtSearch.TextMarginBottom = 0;
            txtSearch.TextMarginLeft = 10;
            txtSearch.TextMarginTop = 1;
            txtSearch.TextPlaceholder = "Search product ...";
            txtSearch.UseSystemPasswordChar = false;
            txtSearch.WordWrap = true;
            // 
            // btnServices
            // 
            btnServices.AllowAnimations = true;
            btnServices.AllowMouseEffects = true;
            btnServices.AllowToggling = false;
            btnServices.AnimationSpeed = 200;
            btnServices.AutoGenerateColors = false;
            btnServices.AutoRoundBorders = false;
            btnServices.AutoSizeLeftIcon = true;
            btnServices.AutoSizeRightIcon = true;
            btnServices.BackColor = Color.Transparent;
            btnServices.BackColor1 = Color.White;
            btnServices.BackgroundImage = (Image)resources.GetObject("btnServices.BackgroundImage");
            btnServices.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnServices.ButtonText = "Services";
            btnServices.ButtonTextMarginLeft = 0;
            btnServices.ColorContrastOnClick = 45;
            btnServices.ColorContrastOnHover = 45;
            btnServices.Cursor = Cursors.Hand;
            borderEdges10.BottomLeft = true;
            borderEdges10.BottomRight = true;
            borderEdges10.TopLeft = true;
            borderEdges10.TopRight = true;
            btnServices.CustomizableEdges = borderEdges10;
            btnServices.DialogResult = DialogResult.None;
            btnServices.DisabledBorderColor = Color.FromArgb(191, 191, 191);
            btnServices.DisabledFillColor = Color.FromArgb(204, 204, 204);
            btnServices.DisabledForecolor = Color.FromArgb(168, 160, 168);
            btnServices.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            btnServices.Font = new Font("Verdana", 9.75F, FontStyle.Regular, GraphicsUnit.Point, 0);
            btnServices.ForeColor = Color.DarkGoldenrod;
            btnServices.IconLeftAlign = ContentAlignment.MiddleLeft;
            btnServices.IconLeftCursor = Cursors.Default;
            btnServices.IconLeftPadding = new Padding(15, 3, 3, 3);
            btnServices.IconMarginLeft = 11;
            btnServices.IconPadding = 10;
            btnServices.IconRightAlign = ContentAlignment.MiddleRight;
            btnServices.IconRightCursor = Cursors.Default;
            btnServices.IconRightPadding = new Padding(3, 3, 7, 3);
            btnServices.IconSize = 25;
            btnServices.IdleBorderColor = Color.DarkGoldenrod;
            btnServices.IdleBorderRadius = 15;
            btnServices.IdleBorderThickness = 1;
            btnServices.IdleFillColor = Color.White;
            btnServices.IdleIconLeftImage = Properties.Resources.convenience;
            btnServices.IdleIconRightImage = null;
            btnServices.IndicateFocus = false;
            btnServices.Location = new Point(123, 95);
            btnServices.Name = "btnServices";
            btnServices.OnDisabledState.BorderColor = Color.FromArgb(191, 191, 191);
            btnServices.OnDisabledState.BorderRadius = 15;
            btnServices.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnServices.OnDisabledState.BorderThickness = 1;
            btnServices.OnDisabledState.FillColor = Color.FromArgb(204, 204, 204);
            btnServices.OnDisabledState.ForeColor = Color.FromArgb(168, 160, 168);
            btnServices.OnDisabledState.IconLeftImage = null;
            btnServices.OnDisabledState.IconRightImage = null;
            btnServices.onHoverState.BorderColor = Color.DarkGoldenrod;
            btnServices.onHoverState.BorderRadius = 15;
            btnServices.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnServices.onHoverState.BorderThickness = 1;
            btnServices.onHoverState.FillColor = Color.DarkGoldenrod;
            btnServices.onHoverState.ForeColor = Color.White;
            btnServices.onHoverState.IconLeftImage = Properties.Resources.convenience;
            btnServices.onHoverState.IconRightImage = null;
            btnServices.OnIdleState.BorderColor = Color.DarkGoldenrod;
            btnServices.OnIdleState.BorderRadius = 15;
            btnServices.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnServices.OnIdleState.BorderThickness = 1;
            btnServices.OnIdleState.FillColor = Color.White;
            btnServices.OnIdleState.ForeColor = Color.DarkGoldenrod;
            btnServices.OnIdleState.IconLeftImage = Properties.Resources.convenience;
            btnServices.OnIdleState.IconRightImage = null;
            btnServices.OnPressedState.BorderColor = Color.Gray;
            btnServices.OnPressedState.BorderRadius = 15;
            btnServices.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnServices.OnPressedState.BorderThickness = 1;
            btnServices.OnPressedState.FillColor = Color.DarkGoldenrod;
            btnServices.OnPressedState.ForeColor = Color.White;
            btnServices.OnPressedState.IconLeftImage = null;
            btnServices.OnPressedState.IconRightImage = null;
            btnServices.Size = new Size(120, 39);
            btnServices.TabIndex = 17;
            btnServices.TextAlign = ContentAlignment.MiddleCenter;
            btnServices.TextAlignment = HorizontalAlignment.Center;
            btnServices.TextMarginLeft = 0;
            btnServices.TextPadding = new Padding(10, 0, 0, 0);
            btnServices.UseDefaultRadiusAndThickness = true;
            // 
            // btnFoods
            // 
            btnFoods.AllowAnimations = true;
            btnFoods.AllowMouseEffects = true;
            btnFoods.AllowToggling = false;
            btnFoods.AnimationSpeed = 200;
            btnFoods.AutoGenerateColors = false;
            btnFoods.AutoRoundBorders = false;
            btnFoods.AutoSizeLeftIcon = true;
            btnFoods.AutoSizeRightIcon = true;
            btnFoods.BackColor = Color.Transparent;
            btnFoods.BackColor1 = Color.White;
            btnFoods.BackgroundImage = (Image)resources.GetObject("btnFoods.BackgroundImage");
            btnFoods.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnFoods.ButtonText = "Foods";
            btnFoods.ButtonTextMarginLeft = 0;
            btnFoods.ColorContrastOnClick = 45;
            btnFoods.ColorContrastOnHover = 45;
            btnFoods.Cursor = Cursors.Hand;
            borderEdges11.BottomLeft = true;
            borderEdges11.BottomRight = true;
            borderEdges11.TopLeft = true;
            borderEdges11.TopRight = true;
            btnFoods.CustomizableEdges = borderEdges11;
            btnFoods.DialogResult = DialogResult.None;
            btnFoods.DisabledBorderColor = Color.FromArgb(191, 191, 191);
            btnFoods.DisabledFillColor = Color.FromArgb(204, 204, 204);
            btnFoods.DisabledForecolor = Color.FromArgb(168, 160, 168);
            btnFoods.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            btnFoods.Font = new Font("Verdana", 9.75F);
            btnFoods.ForeColor = Color.DarkGoldenrod;
            btnFoods.IconLeftAlign = ContentAlignment.MiddleLeft;
            btnFoods.IconLeftCursor = Cursors.Default;
            btnFoods.IconLeftPadding = new Padding(15, 3, 3, 3);
            btnFoods.IconMarginLeft = 11;
            btnFoods.IconPadding = 10;
            btnFoods.IconRightAlign = ContentAlignment.MiddleRight;
            btnFoods.IconRightCursor = Cursors.Default;
            btnFoods.IconRightPadding = new Padding(3, 3, 7, 3);
            btnFoods.IconSize = 25;
            btnFoods.IdleBorderColor = Color.DarkGoldenrod;
            btnFoods.IdleBorderRadius = 15;
            btnFoods.IdleBorderThickness = 1;
            btnFoods.IdleFillColor = Color.White;
            btnFoods.IdleIconLeftImage = Properties.Resources._3d_utensil;
            btnFoods.IdleIconRightImage = null;
            btnFoods.IndicateFocus = false;
            btnFoods.Location = new Point(249, 95);
            btnFoods.Name = "btnFoods";
            btnFoods.OnDisabledState.BorderColor = Color.FromArgb(191, 191, 191);
            btnFoods.OnDisabledState.BorderRadius = 15;
            btnFoods.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnFoods.OnDisabledState.BorderThickness = 1;
            btnFoods.OnDisabledState.FillColor = Color.FromArgb(204, 204, 204);
            btnFoods.OnDisabledState.ForeColor = Color.FromArgb(168, 160, 168);
            btnFoods.OnDisabledState.IconLeftImage = null;
            btnFoods.OnDisabledState.IconRightImage = null;
            btnFoods.onHoverState.BorderColor = Color.DarkGoldenrod;
            btnFoods.onHoverState.BorderRadius = 15;
            btnFoods.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnFoods.onHoverState.BorderThickness = 1;
            btnFoods.onHoverState.FillColor = Color.DarkGoldenrod;
            btnFoods.onHoverState.ForeColor = Color.White;
            btnFoods.onHoverState.IconLeftImage = Properties.Resources._3d_utensil;
            btnFoods.onHoverState.IconRightImage = null;
            btnFoods.OnIdleState.BorderColor = Color.DarkGoldenrod;
            btnFoods.OnIdleState.BorderRadius = 15;
            btnFoods.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnFoods.OnIdleState.BorderThickness = 1;
            btnFoods.OnIdleState.FillColor = Color.White;
            btnFoods.OnIdleState.ForeColor = Color.DarkGoldenrod;
            btnFoods.OnIdleState.IconLeftImage = Properties.Resources._3d_utensil;
            btnFoods.OnIdleState.IconRightImage = null;
            btnFoods.OnPressedState.BorderColor = Color.Gray;
            btnFoods.OnPressedState.BorderRadius = 15;
            btnFoods.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnFoods.OnPressedState.BorderThickness = 1;
            btnFoods.OnPressedState.FillColor = Color.DarkGoldenrod;
            btnFoods.OnPressedState.ForeColor = Color.White;
            btnFoods.OnPressedState.IconLeftImage = null;
            btnFoods.OnPressedState.IconRightImage = null;
            btnFoods.Size = new Size(120, 39);
            btnFoods.TabIndex = 18;
            btnFoods.TextAlign = ContentAlignment.MiddleCenter;
            btnFoods.TextAlignment = HorizontalAlignment.Center;
            btnFoods.TextMarginLeft = 0;
            btnFoods.TextPadding = new Padding(10, 0, 0, 0);
            btnFoods.UseDefaultRadiusAndThickness = true;
            // 
            // btnDrinks
            // 
            btnDrinks.AllowAnimations = true;
            btnDrinks.AllowMouseEffects = true;
            btnDrinks.AllowToggling = false;
            btnDrinks.AnimationSpeed = 200;
            btnDrinks.AutoGenerateColors = false;
            btnDrinks.AutoRoundBorders = false;
            btnDrinks.AutoSizeLeftIcon = true;
            btnDrinks.AutoSizeRightIcon = true;
            btnDrinks.BackColor = Color.Transparent;
            btnDrinks.BackColor1 = Color.White;
            btnDrinks.BackgroundImage = (Image)resources.GetObject("btnDrinks.BackgroundImage");
            btnDrinks.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnDrinks.ButtonText = "Drinks";
            btnDrinks.ButtonTextMarginLeft = 0;
            btnDrinks.ColorContrastOnClick = 45;
            btnDrinks.ColorContrastOnHover = 45;
            btnDrinks.Cursor = Cursors.Hand;
            borderEdges12.BottomLeft = true;
            borderEdges12.BottomRight = true;
            borderEdges12.TopLeft = true;
            borderEdges12.TopRight = true;
            btnDrinks.CustomizableEdges = borderEdges12;
            btnDrinks.DialogResult = DialogResult.None;
            btnDrinks.DisabledBorderColor = Color.FromArgb(191, 191, 191);
            btnDrinks.DisabledFillColor = Color.FromArgb(204, 204, 204);
            btnDrinks.DisabledForecolor = Color.FromArgb(168, 160, 168);
            btnDrinks.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            btnDrinks.Font = new Font("Verdana", 9.75F);
            btnDrinks.ForeColor = Color.DarkGoldenrod;
            btnDrinks.IconLeftAlign = ContentAlignment.MiddleLeft;
            btnDrinks.IconLeftCursor = Cursors.Default;
            btnDrinks.IconLeftPadding = new Padding(15, 3, 3, 3);
            btnDrinks.IconMarginLeft = 11;
            btnDrinks.IconPadding = 10;
            btnDrinks.IconRightAlign = ContentAlignment.MiddleRight;
            btnDrinks.IconRightCursor = Cursors.Default;
            btnDrinks.IconRightPadding = new Padding(3, 3, 7, 3);
            btnDrinks.IconSize = 25;
            btnDrinks.IdleBorderColor = Color.DarkGoldenrod;
            btnDrinks.IdleBorderRadius = 15;
            btnDrinks.IdleBorderThickness = 1;
            btnDrinks.IdleFillColor = Color.White;
            btnDrinks.IdleIconLeftImage = Properties.Resources.mezcal;
            btnDrinks.IdleIconRightImage = null;
            btnDrinks.IndicateFocus = false;
            btnDrinks.Location = new Point(375, 94);
            btnDrinks.Name = "btnDrinks";
            btnDrinks.OnDisabledState.BorderColor = Color.FromArgb(191, 191, 191);
            btnDrinks.OnDisabledState.BorderRadius = 15;
            btnDrinks.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnDrinks.OnDisabledState.BorderThickness = 1;
            btnDrinks.OnDisabledState.FillColor = Color.FromArgb(204, 204, 204);
            btnDrinks.OnDisabledState.ForeColor = Color.FromArgb(168, 160, 168);
            btnDrinks.OnDisabledState.IconLeftImage = null;
            btnDrinks.OnDisabledState.IconRightImage = null;
            btnDrinks.onHoverState.BorderColor = Color.DarkGoldenrod;
            btnDrinks.onHoverState.BorderRadius = 15;
            btnDrinks.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnDrinks.onHoverState.BorderThickness = 1;
            btnDrinks.onHoverState.FillColor = Color.DarkGoldenrod;
            btnDrinks.onHoverState.ForeColor = Color.White;
            btnDrinks.onHoverState.IconLeftImage = Properties.Resources.mezcal;
            btnDrinks.onHoverState.IconRightImage = null;
            btnDrinks.OnIdleState.BorderColor = Color.DarkGoldenrod;
            btnDrinks.OnIdleState.BorderRadius = 15;
            btnDrinks.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnDrinks.OnIdleState.BorderThickness = 1;
            btnDrinks.OnIdleState.FillColor = Color.White;
            btnDrinks.OnIdleState.ForeColor = Color.DarkGoldenrod;
            btnDrinks.OnIdleState.IconLeftImage = Properties.Resources.mezcal;
            btnDrinks.OnIdleState.IconRightImage = null;
            btnDrinks.OnPressedState.BorderColor = Color.Gray;
            btnDrinks.OnPressedState.BorderRadius = 15;
            btnDrinks.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnDrinks.OnPressedState.BorderThickness = 1;
            btnDrinks.OnPressedState.FillColor = Color.DarkGoldenrod;
            btnDrinks.OnPressedState.ForeColor = Color.White;
            btnDrinks.OnPressedState.IconLeftImage = null;
            btnDrinks.OnPressedState.IconRightImage = null;
            btnDrinks.Size = new Size(120, 39);
            btnDrinks.TabIndex = 19;
            btnDrinks.TextAlign = ContentAlignment.MiddleCenter;
            btnDrinks.TextAlignment = HorizontalAlignment.Center;
            btnDrinks.TextMarginLeft = 0;
            btnDrinks.TextPadding = new Padding(10, 0, 0, 0);
            btnDrinks.UseDefaultRadiusAndThickness = true;
            // 
            // panDisplayItem
            // 
            panDisplayItem.BackgroundColor = Color.White;
            panDisplayItem.BackgroundImage = (Image)resources.GetObject("panDisplayItem.BackgroundImage");
            panDisplayItem.BackgroundImageLayout = ImageLayout.Stretch;
            panDisplayItem.BorderColor = Color.White;
            panDisplayItem.BorderRadius = 3;
            panDisplayItem.BorderThickness = 1;
            panDisplayItem.Location = new Point(123, 139);
            panDisplayItem.Name = "panDisplayItem";
            panDisplayItem.ShowBorders = true;
            panDisplayItem.Size = new Size(959, 637);
            panDisplayItem.TabIndex = 21;
            // 
            // sliderPriceFilter
            // 
            sliderPriceFilter.AllowCursorChanges = true;
            sliderPriceFilter.AllowHomeEndKeysDetection = false;
            sliderPriceFilter.AllowIncrementalClickMoves = true;
            sliderPriceFilter.AllowMouseDownEffects = false;
            sliderPriceFilter.AllowMouseHoverEffects = false;
            sliderPriceFilter.AllowScrollingAnimations = true;
            sliderPriceFilter.AllowScrollKeysDetection = true;
            sliderPriceFilter.AllowScrollOptionsMenu = true;
            sliderPriceFilter.AllowShrinkingOnFocusLost = false;
            sliderPriceFilter.BackColor = Color.Transparent;
            sliderPriceFilter.BackgroundImage = (Image)resources.GetObject("sliderPriceFilter.BackgroundImage");
            sliderPriceFilter.BindingContainer = null;
            sliderPriceFilter.BorderRadius = 2;
            sliderPriceFilter.BorderThickness = 1;
            sliderPriceFilter.DrawThickBorder = false;
            sliderPriceFilter.DurationBeforeShrink = 2000;
            sliderPriceFilter.ElapsedColor = Color.DodgerBlue;
            sliderPriceFilter.LargeChange = 1;
            sliderPriceFilter.Location = new Point(822, 102);
            sliderPriceFilter.Maximum = 5;
            sliderPriceFilter.Minimum = 0;
            sliderPriceFilter.MinimumSize = new Size(0, 31);
            sliderPriceFilter.MinimumThumbLength = 18;
            sliderPriceFilter.Name = "sliderPriceFilter";
            sliderPriceFilter.OnDisable.ScrollBarBorderColor = Color.Silver;
            sliderPriceFilter.OnDisable.ScrollBarColor = Color.Transparent;
            sliderPriceFilter.OnDisable.ThumbColor = Color.Silver;
            sliderPriceFilter.ScrollBarBorderColor = Color.FromArgb(210, 232, 255);
            sliderPriceFilter.ScrollBarColor = Color.FromArgb(210, 232, 255);
            sliderPriceFilter.ShrinkSizeLimit = 3;
            sliderPriceFilter.Size = new Size(188, 31);
            sliderPriceFilter.SliderColor = Color.FromArgb(210, 232, 255);
            sliderPriceFilter.SliderStyle = Bunifu.UI.WinForms.BunifuHSlider.SliderStyles.Thin;
            sliderPriceFilter.SliderThumbStyle = Utilities.BunifuSlider.BunifuHScrollBar.SliderThumbStyles.Circular;
            sliderPriceFilter.SmallChange = 1;
            sliderPriceFilter.TabIndex = 0;
            sliderPriceFilter.ThumbColor = Color.DodgerBlue;
            sliderPriceFilter.ThumbFillColor = SystemColors.Control;
            sliderPriceFilter.ThumbLength = 31;
            sliderPriceFilter.ThumbMargin = 1;
            sliderPriceFilter.ThumbSize = Bunifu.UI.WinForms.BunifuHSlider.ThumbSizes.Medium;
            sliderPriceFilter.ThumbStyle = Bunifu.UI.WinForms.BunifuHSlider.ThumbStyles.Outline;
            sliderPriceFilter.Value = 0;
            // 
            // lblPriceRange
            // 
            lblPriceRange.AllowParentOverrides = false;
            lblPriceRange.AutoEllipsis = false;
            lblPriceRange.CursorType = Cursors.Default;
            lblPriceRange.Font = new Font("Verdana", 9.75F, FontStyle.Bold, GraphicsUnit.Point, 0);
            lblPriceRange.Location = new Point(1016, 117);
            lblPriceRange.Name = "lblPriceRange";
            lblPriceRange.RightToLeft = RightToLeft.No;
            lblPriceRange.Size = new Size(66, 16);
            lblPriceRange.TabIndex = 0;
            lblPriceRange.Text = "All Prices";
            lblPriceRange.TextAlignment = ContentAlignment.TopLeft;
            lblPriceRange.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuFormDock1
            // 
            bunifuFormDock1.AllowFormDragging = true;
            bunifuFormDock1.AllowFormDropShadow = true;
            bunifuFormDock1.AllowFormResizing = false;
            bunifuFormDock1.AllowHidingBottomRegion = true;
            bunifuFormDock1.AllowOpacityChangesWhileDragging = false;
            bunifuFormDock1.BorderOptions.BottomBorder.BorderColor = Color.Silver;
            bunifuFormDock1.BorderOptions.BottomBorder.BorderThickness = 1;
            bunifuFormDock1.BorderOptions.BottomBorder.ShowBorder = true;
            bunifuFormDock1.BorderOptions.LeftBorder.BorderColor = Color.Silver;
            bunifuFormDock1.BorderOptions.LeftBorder.BorderThickness = 1;
            bunifuFormDock1.BorderOptions.LeftBorder.ShowBorder = true;
            bunifuFormDock1.BorderOptions.RightBorder.BorderColor = Color.Silver;
            bunifuFormDock1.BorderOptions.RightBorder.BorderThickness = 1;
            bunifuFormDock1.BorderOptions.RightBorder.ShowBorder = true;
            bunifuFormDock1.BorderOptions.TopBorder.BorderColor = Color.Silver;
            bunifuFormDock1.BorderOptions.TopBorder.BorderThickness = 1;
            bunifuFormDock1.BorderOptions.TopBorder.ShowBorder = true;
            bunifuFormDock1.ContainerControl = this;
            bunifuFormDock1.DockingIndicatorsColor = Color.FromArgb(202, 215, 233);
            bunifuFormDock1.DockingIndicatorsOpacity = 0.5D;
            bunifuFormDock1.DockingOptions.DockAll = true;
            bunifuFormDock1.DockingOptions.DockBottomLeft = true;
            bunifuFormDock1.DockingOptions.DockBottomRight = true;
            bunifuFormDock1.DockingOptions.DockFullScreen = true;
            bunifuFormDock1.DockingOptions.DockLeft = true;
            bunifuFormDock1.DockingOptions.DockRight = true;
            bunifuFormDock1.DockingOptions.DockTopLeft = true;
            bunifuFormDock1.DockingOptions.DockTopRight = true;
            bunifuFormDock1.FormDraggingOpacity = 0.9D;
            bunifuFormDock1.ParentForm = this;
            bunifuFormDock1.ShowCursorChanges = true;
            bunifuFormDock1.ShowDockingIndicators = true;
            bunifuFormDock1.TitleBarOptions.AllowFormDragging = true;
            bunifuFormDock1.TitleBarOptions.BunifuFormDock = bunifuFormDock1;
            bunifuFormDock1.TitleBarOptions.DoubleClickToExpandWindow = true;
            bunifuFormDock1.TitleBarOptions.TitleBarControl = null;
            bunifuFormDock1.TitleBarOptions.UseBackColorOnDockingIndicators = false;
            // 
            // Dashboard
            // 
            AutoScaleDimensions = new SizeF(7F, 15F);
            AutoScaleMode = AutoScaleMode.Font;
            ClientSize = new Size(1386, 788);
            Controls.Add(lblPriceRange);
            Controls.Add(sliderPriceFilter);
            Controls.Add(btnDrinks);
            Controls.Add(btnFoods);
            Controls.Add(btnServices);
            Controls.Add(txtSearch);
            Controls.Add(bunifuLabel2);
            Controls.Add(bunifuLabel1);
            Controls.Add(bunifuPanel2);
            Controls.Add(bunifuPanel1);
            Controls.Add(panDisplayItem);
            FormBorderStyle = FormBorderStyle.None;
            Name = "Dashboard";
            StartPosition = FormStartPosition.CenterScreen;
            Text = "Dashboard";
            bunifuPanel1.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)LogoImage).EndInit();
            bunifuPanel2.ResumeLayout(false);
            bunifuPanel2.PerformLayout();
            bunifuPanel9.ResumeLayout(false);
            bunifuPanel9.PerformLayout();
            ResumeLayout(false);
            PerformLayout();
        }

        #endregion

        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel1;
        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel2;
        private Bunifu.UI.WinForms.BunifuPictureBox LogoImage;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnAllForm;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnInvoice;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnStatistic;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnLogout;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnSetting;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 bunifuButton25;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel2;
        private Bunifu.UI.WinForms.BunifuTextBox txtSearch;
        private Bunifu.UI.WinForms.BunifuButton.BunifuIconButton btnExitProgram;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel27;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnServices;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnFoods;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnDrinks;
        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel9;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel35;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel34;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnCheckout;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel40;
        private Bunifu.UI.WinForms.BunifuSeparator bunifuSeparator1;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel38;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel36;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel37;
        private Bunifu.UI.WinForms.BunifuTextBox txtCustomerID;
        private Bunifu.UI.WinForms.BunifuLabel txtCardStatus;
        private Bunifu.UI.WinForms.BunifuPanel panOrderDetailOuter;
        private Bunifu.UI.WinForms.BunifuPanel panDisplayItem;
        private Bunifu.UI.WinForms.BunifuHSlider sliderPriceFilter;
        private Bunifu.UI.WinForms.BunifuLabel lblPriceRange;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnRefresh;
        private Bunifu.UI.WinForms.BunifuFormDock bunifuFormDock1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnPayment;
    }
}