namespace Spa_Management_System
{
    partial class Dashboard
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Dashboard));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            bunifuPanel1 = new Bunifu.UI.WinForms.BunifuPanel();
            bunifuPanel2 = new Bunifu.UI.WinForms.BunifuPanel();
            bunifuPictureBox1 = new Bunifu.UI.WinForms.BunifuPictureBox();
            bunifuButton21 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            bunifuButton22 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            bunifuButton23 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            bunifuButton24 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            bunifuButton25 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            bunifuButton26 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            bunifuButton27 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            bunifuPanel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)bunifuPictureBox1).BeginInit();
            SuspendLayout();
            // 
            // bunifuPanel1
            // 
            bunifuPanel1.BackgroundColor = Color.White;
            bunifuPanel1.BackgroundImage = (Image)resources.GetObject("bunifuPanel1.BackgroundImage");
            bunifuPanel1.BackgroundImageLayout = ImageLayout.Stretch;
            bunifuPanel1.BorderColor = Color.White;
            bunifuPanel1.BorderRadius = 3;
            bunifuPanel1.BorderThickness = 1;
            bunifuPanel1.Controls.Add(bunifuButton26);
            bunifuPanel1.Controls.Add(bunifuButton27);
            bunifuPanel1.Controls.Add(bunifuButton25);
            bunifuPanel1.Controls.Add(bunifuButton24);
            bunifuPanel1.Controls.Add(bunifuButton23);
            bunifuPanel1.Controls.Add(bunifuButton22);
            bunifuPanel1.Controls.Add(bunifuButton21);
            bunifuPanel1.Controls.Add(bunifuPictureBox1);
            bunifuPanel1.Dock = DockStyle.Left;
            bunifuPanel1.Location = new Point(0, 0);
            bunifuPanel1.Name = "bunifuPanel1";
            bunifuPanel1.ShowBorders = true;
            bunifuPanel1.Size = new Size(132, 788);
            bunifuPanel1.TabIndex = 0;
            // 
            // bunifuPanel2
            // 
            bunifuPanel2.BackgroundColor = Color.White;
            bunifuPanel2.BackgroundImage = (Image)resources.GetObject("bunifuPanel2.BackgroundImage");
            bunifuPanel2.BackgroundImageLayout = ImageLayout.Stretch;
            bunifuPanel2.BorderColor = Color.White;
            bunifuPanel2.BorderRadius = 3;
            bunifuPanel2.BorderThickness = 1;
            bunifuPanel2.Dock = DockStyle.Right;
            bunifuPanel2.Location = new Point(1186, 0);
            bunifuPanel2.Name = "bunifuPanel2";
            bunifuPanel2.ShowBorders = true;
            bunifuPanel2.Size = new Size(200, 788);
            bunifuPanel2.TabIndex = 1;
            // 
            // bunifuPictureBox1
            // 
            bunifuPictureBox1.AllowFocused = false;
            bunifuPictureBox1.AutoSizeHeight = true;
            bunifuPictureBox1.BackColor = Color.White;
            bunifuPictureBox1.BorderRadius = 35;
            bunifuPictureBox1.Image = (Image)resources.GetObject("bunifuPictureBox1.Image");
            bunifuPictureBox1.InitialImage = null;
            bunifuPictureBox1.IsCircle = true;
            bunifuPictureBox1.Location = new Point(26, 12);
            bunifuPictureBox1.Name = "bunifuPictureBox1";
            bunifuPictureBox1.Size = new Size(70, 70);
            bunifuPictureBox1.SizeMode = PictureBoxSizeMode.Zoom;
            bunifuPictureBox1.TabIndex = 2;
            bunifuPictureBox1.TabStop = false;
            bunifuPictureBox1.Type = Bunifu.UI.WinForms.BunifuPictureBox.Types.Circle;
            // 
            // bunifuButton21
            // 
            bunifuButton21.AllowAnimations = true;
            bunifuButton21.AllowMouseEffects = true;
            bunifuButton21.AllowToggling = false;
            bunifuButton21.AnimationSpeed = 200;
            bunifuButton21.AutoGenerateColors = false;
            bunifuButton21.AutoRoundBorders = false;
            bunifuButton21.AutoSizeLeftIcon = true;
            bunifuButton21.AutoSizeRightIcon = true;
            bunifuButton21.BackColor = Color.Transparent;
            bunifuButton21.BackColor1 = Color.White;
            bunifuButton21.BackgroundImage = (Image)resources.GetObject("bunifuButton21.BackgroundImage");
            bunifuButton21.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            bunifuButton21.ButtonText = "";
            bunifuButton21.ButtonTextMarginLeft = 0;
            bunifuButton21.ColorContrastOnClick = 45;
            bunifuButton21.ColorContrastOnHover = 45;
            borderEdges7.BottomLeft = true;
            borderEdges7.BottomRight = true;
            borderEdges7.TopLeft = true;
            borderEdges7.TopRight = true;
            bunifuButton21.CustomizableEdges = borderEdges7;
            bunifuButton21.DialogResult = DialogResult.None;
            bunifuButton21.DisabledBorderColor = Color.FromArgb(191, 191, 191);
            bunifuButton21.DisabledFillColor = Color.FromArgb(204, 204, 204);
            bunifuButton21.DisabledForecolor = Color.FromArgb(168, 160, 168);
            bunifuButton21.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            bunifuButton21.Font = new Font("Segoe UI", 9F);
            bunifuButton21.ForeColor = Color.White;
            bunifuButton21.IconLeftAlign = ContentAlignment.MiddleLeft;
            bunifuButton21.IconLeftCursor = Cursors.Default;
            bunifuButton21.IconLeftPadding = new Padding(11, 3, 3, 3);
            bunifuButton21.IconMarginLeft = 11;
            bunifuButton21.IconPadding = 10;
            bunifuButton21.IconRightAlign = ContentAlignment.MiddleRight;
            bunifuButton21.IconRightCursor = Cursors.Default;
            bunifuButton21.IconRightPadding = new Padding(3, 3, 7, 3);
            bunifuButton21.IconSize = 25;
            bunifuButton21.IdleBorderColor = Color.White;
            bunifuButton21.IdleBorderRadius = 1;
            bunifuButton21.IdleBorderThickness = 1;
            bunifuButton21.IdleFillColor = Color.White;
            bunifuButton21.IdleIconLeftImage = (Image)resources.GetObject("bunifuButton21.IdleIconLeftImage");
            bunifuButton21.IdleIconRightImage = null;
            bunifuButton21.IndicateFocus = false;
            bunifuButton21.Location = new Point(35, 139);
            bunifuButton21.Name = "bunifuButton21";
            bunifuButton21.OnDisabledState.BorderColor = Color.FromArgb(191, 191, 191);
            bunifuButton21.OnDisabledState.BorderRadius = 1;
            bunifuButton21.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            bunifuButton21.OnDisabledState.BorderThickness = 1;
            bunifuButton21.OnDisabledState.FillColor = Color.FromArgb(204, 204, 204);
            bunifuButton21.OnDisabledState.ForeColor = Color.FromArgb(168, 160, 168);
            bunifuButton21.OnDisabledState.IconLeftImage = null;
            bunifuButton21.OnDisabledState.IconRightImage = null;
            bunifuButton21.onHoverState.BorderColor = Color.DarkGoldenrod;
            bunifuButton21.onHoverState.BorderRadius = 1;
            bunifuButton21.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            bunifuButton21.onHoverState.BorderThickness = 1;
            bunifuButton21.onHoverState.FillColor = Color.White;
            bunifuButton21.onHoverState.ForeColor = Color.White;
            bunifuButton21.onHoverState.IconLeftImage = null;
            bunifuButton21.onHoverState.IconRightImage = null;
            bunifuButton21.OnIdleState.BorderColor = Color.White;
            bunifuButton21.OnIdleState.BorderRadius = 1;
            bunifuButton21.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            bunifuButton21.OnIdleState.BorderThickness = 1;
            bunifuButton21.OnIdleState.FillColor = Color.White;
            bunifuButton21.OnIdleState.ForeColor = Color.White;
            bunifuButton21.OnIdleState.IconLeftImage = (Image)resources.GetObject("bunifuButton21.OnIdleState.IconLeftImage");
            bunifuButton21.OnIdleState.IconRightImage = null;
            bunifuButton21.OnPressedState.BorderColor = Color.Lime;
            bunifuButton21.OnPressedState.BorderRadius = 1;
            bunifuButton21.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            bunifuButton21.OnPressedState.BorderThickness = 1;
            bunifuButton21.OnPressedState.FillColor = Color.White;
            bunifuButton21.OnPressedState.ForeColor = Color.White;
            bunifuButton21.OnPressedState.IconLeftImage = null;
            bunifuButton21.OnPressedState.IconRightImage = null;
            bunifuButton21.Size = new Size(61, 58);
            bunifuButton21.TabIndex = 2;
            bunifuButton21.TextAlign = ContentAlignment.MiddleCenter;
            bunifuButton21.TextAlignment = HorizontalAlignment.Center;
            bunifuButton21.TextMarginLeft = 0;
            bunifuButton21.TextPadding = new Padding(0);
            bunifuButton21.UseDefaultRadiusAndThickness = true;
            // 
            // bunifuButton22
            // 
            bunifuButton22.AllowAnimations = true;
            bunifuButton22.AllowMouseEffects = true;
            bunifuButton22.AllowToggling = false;
            bunifuButton22.AnimationSpeed = 200;
            bunifuButton22.AutoGenerateColors = false;
            bunifuButton22.AutoRoundBorders = false;
            bunifuButton22.AutoSizeLeftIcon = true;
            bunifuButton22.AutoSizeRightIcon = true;
            bunifuButton22.BackColor = Color.Transparent;
            bunifuButton22.BackColor1 = Color.White;
            bunifuButton22.BackgroundImage = (Image)resources.GetObject("bunifuButton22.BackgroundImage");
            bunifuButton22.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            bunifuButton22.ButtonText = "";
            bunifuButton22.ButtonTextMarginLeft = 0;
            bunifuButton22.ColorContrastOnClick = 45;
            bunifuButton22.ColorContrastOnHover = 45;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            bunifuButton22.CustomizableEdges = borderEdges6;
            bunifuButton22.DialogResult = DialogResult.None;
            bunifuButton22.DisabledBorderColor = Color.FromArgb(191, 191, 191);
            bunifuButton22.DisabledFillColor = Color.FromArgb(204, 204, 204);
            bunifuButton22.DisabledForecolor = Color.FromArgb(168, 160, 168);
            bunifuButton22.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            bunifuButton22.Font = new Font("Segoe UI", 9F);
            bunifuButton22.ForeColor = Color.White;
            bunifuButton22.IconLeftAlign = ContentAlignment.MiddleLeft;
            bunifuButton22.IconLeftCursor = Cursors.Default;
            bunifuButton22.IconLeftPadding = new Padding(11, 3, 3, 3);
            bunifuButton22.IconMarginLeft = 11;
            bunifuButton22.IconPadding = 10;
            bunifuButton22.IconRightAlign = ContentAlignment.MiddleRight;
            bunifuButton22.IconRightCursor = Cursors.Default;
            bunifuButton22.IconRightPadding = new Padding(3, 3, 7, 3);
            bunifuButton22.IconSize = 25;
            bunifuButton22.IdleBorderColor = Color.White;
            bunifuButton22.IdleBorderRadius = 1;
            bunifuButton22.IdleBorderThickness = 1;
            bunifuButton22.IdleFillColor = Color.White;
            bunifuButton22.IdleIconLeftImage = (Image)resources.GetObject("bunifuButton22.IdleIconLeftImage");
            bunifuButton22.IdleIconRightImage = null;
            bunifuButton22.IndicateFocus = false;
            bunifuButton22.Location = new Point(35, 213);
            bunifuButton22.Name = "bunifuButton22";
            bunifuButton22.OnDisabledState.BorderColor = Color.FromArgb(191, 191, 191);
            bunifuButton22.OnDisabledState.BorderRadius = 1;
            bunifuButton22.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            bunifuButton22.OnDisabledState.BorderThickness = 1;
            bunifuButton22.OnDisabledState.FillColor = Color.FromArgb(204, 204, 204);
            bunifuButton22.OnDisabledState.ForeColor = Color.FromArgb(168, 160, 168);
            bunifuButton22.OnDisabledState.IconLeftImage = null;
            bunifuButton22.OnDisabledState.IconRightImage = null;
            bunifuButton22.onHoverState.BorderColor = Color.DarkGoldenrod;
            bunifuButton22.onHoverState.BorderRadius = 1;
            bunifuButton22.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            bunifuButton22.onHoverState.BorderThickness = 1;
            bunifuButton22.onHoverState.FillColor = Color.White;
            bunifuButton22.onHoverState.ForeColor = Color.White;
            bunifuButton22.onHoverState.IconLeftImage = null;
            bunifuButton22.onHoverState.IconRightImage = null;
            bunifuButton22.OnIdleState.BorderColor = Color.White;
            bunifuButton22.OnIdleState.BorderRadius = 1;
            bunifuButton22.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            bunifuButton22.OnIdleState.BorderThickness = 1;
            bunifuButton22.OnIdleState.FillColor = Color.White;
            bunifuButton22.OnIdleState.ForeColor = Color.White;
            bunifuButton22.OnIdleState.IconLeftImage = (Image)resources.GetObject("bunifuButton22.OnIdleState.IconLeftImage");
            bunifuButton22.OnIdleState.IconRightImage = null;
            bunifuButton22.OnPressedState.BorderColor = Color.Lime;
            bunifuButton22.OnPressedState.BorderRadius = 1;
            bunifuButton22.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            bunifuButton22.OnPressedState.BorderThickness = 1;
            bunifuButton22.OnPressedState.FillColor = Color.White;
            bunifuButton22.OnPressedState.ForeColor = Color.White;
            bunifuButton22.OnPressedState.IconLeftImage = null;
            bunifuButton22.OnPressedState.IconRightImage = null;
            bunifuButton22.Size = new Size(61, 58);
            bunifuButton22.TabIndex = 3;
            bunifuButton22.TextAlign = ContentAlignment.MiddleCenter;
            bunifuButton22.TextAlignment = HorizontalAlignment.Center;
            bunifuButton22.TextMarginLeft = 0;
            bunifuButton22.TextPadding = new Padding(0);
            bunifuButton22.UseDefaultRadiusAndThickness = true;
            // 
            // bunifuButton23
            // 
            bunifuButton23.AllowAnimations = true;
            bunifuButton23.AllowMouseEffects = true;
            bunifuButton23.AllowToggling = false;
            bunifuButton23.AnimationSpeed = 200;
            bunifuButton23.AutoGenerateColors = false;
            bunifuButton23.AutoRoundBorders = false;
            bunifuButton23.AutoSizeLeftIcon = true;
            bunifuButton23.AutoSizeRightIcon = true;
            bunifuButton23.BackColor = Color.Transparent;
            bunifuButton23.BackColor1 = Color.White;
            bunifuButton23.BackgroundImage = (Image)resources.GetObject("bunifuButton23.BackgroundImage");
            bunifuButton23.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            bunifuButton23.ButtonText = "";
            bunifuButton23.ButtonTextMarginLeft = 0;
            bunifuButton23.ColorContrastOnClick = 45;
            bunifuButton23.ColorContrastOnHover = 45;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            bunifuButton23.CustomizableEdges = borderEdges5;
            bunifuButton23.DialogResult = DialogResult.None;
            bunifuButton23.DisabledBorderColor = Color.FromArgb(191, 191, 191);
            bunifuButton23.DisabledFillColor = Color.FromArgb(204, 204, 204);
            bunifuButton23.DisabledForecolor = Color.FromArgb(168, 160, 168);
            bunifuButton23.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            bunifuButton23.Font = new Font("Segoe UI", 9F);
            bunifuButton23.ForeColor = Color.White;
            bunifuButton23.IconLeftAlign = ContentAlignment.MiddleLeft;
            bunifuButton23.IconLeftCursor = Cursors.Default;
            bunifuButton23.IconLeftPadding = new Padding(11, 3, 3, 3);
            bunifuButton23.IconMarginLeft = 11;
            bunifuButton23.IconPadding = 10;
            bunifuButton23.IconRightAlign = ContentAlignment.MiddleRight;
            bunifuButton23.IconRightCursor = Cursors.Default;
            bunifuButton23.IconRightPadding = new Padding(3, 3, 7, 3);
            bunifuButton23.IconSize = 25;
            bunifuButton23.IdleBorderColor = Color.White;
            bunifuButton23.IdleBorderRadius = 1;
            bunifuButton23.IdleBorderThickness = 1;
            bunifuButton23.IdleFillColor = Color.White;
            bunifuButton23.IdleIconLeftImage = (Image)resources.GetObject("bunifuButton23.IdleIconLeftImage");
            bunifuButton23.IdleIconRightImage = null;
            bunifuButton23.IndicateFocus = false;
            bunifuButton23.Location = new Point(35, 287);
            bunifuButton23.Name = "bunifuButton23";
            bunifuButton23.OnDisabledState.BorderColor = Color.FromArgb(191, 191, 191);
            bunifuButton23.OnDisabledState.BorderRadius = 1;
            bunifuButton23.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            bunifuButton23.OnDisabledState.BorderThickness = 1;
            bunifuButton23.OnDisabledState.FillColor = Color.FromArgb(204, 204, 204);
            bunifuButton23.OnDisabledState.ForeColor = Color.FromArgb(168, 160, 168);
            bunifuButton23.OnDisabledState.IconLeftImage = null;
            bunifuButton23.OnDisabledState.IconRightImage = null;
            bunifuButton23.onHoverState.BorderColor = Color.DarkGoldenrod;
            bunifuButton23.onHoverState.BorderRadius = 1;
            bunifuButton23.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            bunifuButton23.onHoverState.BorderThickness = 1;
            bunifuButton23.onHoverState.FillColor = Color.White;
            bunifuButton23.onHoverState.ForeColor = Color.White;
            bunifuButton23.onHoverState.IconLeftImage = null;
            bunifuButton23.onHoverState.IconRightImage = null;
            bunifuButton23.OnIdleState.BorderColor = Color.White;
            bunifuButton23.OnIdleState.BorderRadius = 1;
            bunifuButton23.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            bunifuButton23.OnIdleState.BorderThickness = 1;
            bunifuButton23.OnIdleState.FillColor = Color.White;
            bunifuButton23.OnIdleState.ForeColor = Color.White;
            bunifuButton23.OnIdleState.IconLeftImage = (Image)resources.GetObject("bunifuButton23.OnIdleState.IconLeftImage");
            bunifuButton23.OnIdleState.IconRightImage = null;
            bunifuButton23.OnPressedState.BorderColor = Color.Lime;
            bunifuButton23.OnPressedState.BorderRadius = 1;
            bunifuButton23.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            bunifuButton23.OnPressedState.BorderThickness = 1;
            bunifuButton23.OnPressedState.FillColor = Color.White;
            bunifuButton23.OnPressedState.ForeColor = Color.White;
            bunifuButton23.OnPressedState.IconLeftImage = null;
            bunifuButton23.OnPressedState.IconRightImage = null;
            bunifuButton23.Size = new Size(61, 58);
            bunifuButton23.TabIndex = 4;
            bunifuButton23.TextAlign = ContentAlignment.MiddleCenter;
            bunifuButton23.TextAlignment = HorizontalAlignment.Center;
            bunifuButton23.TextMarginLeft = 0;
            bunifuButton23.TextPadding = new Padding(0);
            bunifuButton23.UseDefaultRadiusAndThickness = true;
            // 
            // bunifuButton24
            // 
            bunifuButton24.AllowAnimations = true;
            bunifuButton24.AllowMouseEffects = true;
            bunifuButton24.AllowToggling = false;
            bunifuButton24.AnimationSpeed = 200;
            bunifuButton24.AutoGenerateColors = false;
            bunifuButton24.AutoRoundBorders = false;
            bunifuButton24.AutoSizeLeftIcon = true;
            bunifuButton24.AutoSizeRightIcon = true;
            bunifuButton24.BackColor = Color.Transparent;
            bunifuButton24.BackColor1 = Color.White;
            bunifuButton24.BackgroundImage = (Image)resources.GetObject("bunifuButton24.BackgroundImage");
            bunifuButton24.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            bunifuButton24.ButtonText = "";
            bunifuButton24.ButtonTextMarginLeft = 0;
            bunifuButton24.ColorContrastOnClick = 45;
            bunifuButton24.ColorContrastOnHover = 45;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            bunifuButton24.CustomizableEdges = borderEdges4;
            bunifuButton24.DialogResult = DialogResult.None;
            bunifuButton24.DisabledBorderColor = Color.FromArgb(191, 191, 191);
            bunifuButton24.DisabledFillColor = Color.FromArgb(204, 204, 204);
            bunifuButton24.DisabledForecolor = Color.FromArgb(168, 160, 168);
            bunifuButton24.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            bunifuButton24.Font = new Font("Segoe UI", 9F);
            bunifuButton24.ForeColor = Color.White;
            bunifuButton24.IconLeftAlign = ContentAlignment.MiddleLeft;
            bunifuButton24.IconLeftCursor = Cursors.Default;
            bunifuButton24.IconLeftPadding = new Padding(11, 3, 3, 3);
            bunifuButton24.IconMarginLeft = 11;
            bunifuButton24.IconPadding = 10;
            bunifuButton24.IconRightAlign = ContentAlignment.MiddleRight;
            bunifuButton24.IconRightCursor = Cursors.Default;
            bunifuButton24.IconRightPadding = new Padding(3, 3, 7, 3);
            bunifuButton24.IconSize = 25;
            bunifuButton24.IdleBorderColor = Color.White;
            bunifuButton24.IdleBorderRadius = 1;
            bunifuButton24.IdleBorderThickness = 1;
            bunifuButton24.IdleFillColor = Color.White;
            bunifuButton24.IdleIconLeftImage = (Image)resources.GetObject("bunifuButton24.IdleIconLeftImage");
            bunifuButton24.IdleIconRightImage = null;
            bunifuButton24.IndicateFocus = false;
            bunifuButton24.Location = new Point(35, 361);
            bunifuButton24.Name = "bunifuButton24";
            bunifuButton24.OnDisabledState.BorderColor = Color.FromArgb(191, 191, 191);
            bunifuButton24.OnDisabledState.BorderRadius = 1;
            bunifuButton24.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            bunifuButton24.OnDisabledState.BorderThickness = 1;
            bunifuButton24.OnDisabledState.FillColor = Color.FromArgb(204, 204, 204);
            bunifuButton24.OnDisabledState.ForeColor = Color.FromArgb(168, 160, 168);
            bunifuButton24.OnDisabledState.IconLeftImage = null;
            bunifuButton24.OnDisabledState.IconRightImage = null;
            bunifuButton24.onHoverState.BorderColor = Color.DarkGoldenrod;
            bunifuButton24.onHoverState.BorderRadius = 1;
            bunifuButton24.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            bunifuButton24.onHoverState.BorderThickness = 1;
            bunifuButton24.onHoverState.FillColor = Color.White;
            bunifuButton24.onHoverState.ForeColor = Color.White;
            bunifuButton24.onHoverState.IconLeftImage = null;
            bunifuButton24.onHoverState.IconRightImage = null;
            bunifuButton24.OnIdleState.BorderColor = Color.White;
            bunifuButton24.OnIdleState.BorderRadius = 1;
            bunifuButton24.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            bunifuButton24.OnIdleState.BorderThickness = 1;
            bunifuButton24.OnIdleState.FillColor = Color.White;
            bunifuButton24.OnIdleState.ForeColor = Color.White;
            bunifuButton24.OnIdleState.IconLeftImage = (Image)resources.GetObject("bunifuButton24.OnIdleState.IconLeftImage");
            bunifuButton24.OnIdleState.IconRightImage = null;
            bunifuButton24.OnPressedState.BorderColor = Color.Lime;
            bunifuButton24.OnPressedState.BorderRadius = 1;
            bunifuButton24.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            bunifuButton24.OnPressedState.BorderThickness = 1;
            bunifuButton24.OnPressedState.FillColor = Color.White;
            bunifuButton24.OnPressedState.ForeColor = Color.White;
            bunifuButton24.OnPressedState.IconLeftImage = null;
            bunifuButton24.OnPressedState.IconRightImage = null;
            bunifuButton24.Size = new Size(61, 58);
            bunifuButton24.TabIndex = 5;
            bunifuButton24.TextAlign = ContentAlignment.MiddleCenter;
            bunifuButton24.TextAlignment = HorizontalAlignment.Center;
            bunifuButton24.TextMarginLeft = 0;
            bunifuButton24.TextPadding = new Padding(0);
            bunifuButton24.UseDefaultRadiusAndThickness = true;
            // 
            // bunifuButton25
            // 
            bunifuButton25.AllowAnimations = true;
            bunifuButton25.AllowMouseEffects = true;
            bunifuButton25.AllowToggling = false;
            bunifuButton25.AnimationSpeed = 200;
            bunifuButton25.AutoGenerateColors = false;
            bunifuButton25.AutoRoundBorders = false;
            bunifuButton25.AutoSizeLeftIcon = true;
            bunifuButton25.AutoSizeRightIcon = true;
            bunifuButton25.BackColor = Color.Transparent;
            bunifuButton25.BackColor1 = Color.White;
            bunifuButton25.BackgroundImage = (Image)resources.GetObject("bunifuButton25.BackgroundImage");
            bunifuButton25.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            bunifuButton25.ButtonText = "";
            bunifuButton25.ButtonTextMarginLeft = 0;
            bunifuButton25.ColorContrastOnClick = 45;
            bunifuButton25.ColorContrastOnHover = 45;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            bunifuButton25.CustomizableEdges = borderEdges3;
            bunifuButton25.DialogResult = DialogResult.None;
            bunifuButton25.DisabledBorderColor = Color.FromArgb(191, 191, 191);
            bunifuButton25.DisabledFillColor = Color.FromArgb(204, 204, 204);
            bunifuButton25.DisabledForecolor = Color.FromArgb(168, 160, 168);
            bunifuButton25.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            bunifuButton25.Font = new Font("Segoe UI", 9F);
            bunifuButton25.ForeColor = Color.White;
            bunifuButton25.IconLeftAlign = ContentAlignment.MiddleLeft;
            bunifuButton25.IconLeftCursor = Cursors.Default;
            bunifuButton25.IconLeftPadding = new Padding(11, 3, 3, 3);
            bunifuButton25.IconMarginLeft = 11;
            bunifuButton25.IconPadding = 10;
            bunifuButton25.IconRightAlign = ContentAlignment.MiddleRight;
            bunifuButton25.IconRightCursor = Cursors.Default;
            bunifuButton25.IconRightPadding = new Padding(3, 3, 7, 3);
            bunifuButton25.IconSize = 25;
            bunifuButton25.IdleBorderColor = Color.White;
            bunifuButton25.IdleBorderRadius = 1;
            bunifuButton25.IdleBorderThickness = 1;
            bunifuButton25.IdleFillColor = Color.White;
            bunifuButton25.IdleIconLeftImage = (Image)resources.GetObject("bunifuButton25.IdleIconLeftImage");
            bunifuButton25.IdleIconRightImage = null;
            bunifuButton25.IndicateFocus = false;
            bunifuButton25.Location = new Point(35, 435);
            bunifuButton25.Name = "bunifuButton25";
            bunifuButton25.OnDisabledState.BorderColor = Color.FromArgb(191, 191, 191);
            bunifuButton25.OnDisabledState.BorderRadius = 1;
            bunifuButton25.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            bunifuButton25.OnDisabledState.BorderThickness = 1;
            bunifuButton25.OnDisabledState.FillColor = Color.FromArgb(204, 204, 204);
            bunifuButton25.OnDisabledState.ForeColor = Color.FromArgb(168, 160, 168);
            bunifuButton25.OnDisabledState.IconLeftImage = null;
            bunifuButton25.OnDisabledState.IconRightImage = null;
            bunifuButton25.onHoverState.BorderColor = Color.DarkGoldenrod;
            bunifuButton25.onHoverState.BorderRadius = 1;
            bunifuButton25.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            bunifuButton25.onHoverState.BorderThickness = 1;
            bunifuButton25.onHoverState.FillColor = Color.White;
            bunifuButton25.onHoverState.ForeColor = Color.White;
            bunifuButton25.onHoverState.IconLeftImage = null;
            bunifuButton25.onHoverState.IconRightImage = null;
            bunifuButton25.OnIdleState.BorderColor = Color.White;
            bunifuButton25.OnIdleState.BorderRadius = 1;
            bunifuButton25.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            bunifuButton25.OnIdleState.BorderThickness = 1;
            bunifuButton25.OnIdleState.FillColor = Color.White;
            bunifuButton25.OnIdleState.ForeColor = Color.White;
            bunifuButton25.OnIdleState.IconLeftImage = (Image)resources.GetObject("bunifuButton25.OnIdleState.IconLeftImage");
            bunifuButton25.OnIdleState.IconRightImage = null;
            bunifuButton25.OnPressedState.BorderColor = Color.Lime;
            bunifuButton25.OnPressedState.BorderRadius = 1;
            bunifuButton25.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            bunifuButton25.OnPressedState.BorderThickness = 1;
            bunifuButton25.OnPressedState.FillColor = Color.White;
            bunifuButton25.OnPressedState.ForeColor = Color.White;
            bunifuButton25.OnPressedState.IconLeftImage = null;
            bunifuButton25.OnPressedState.IconRightImage = null;
            bunifuButton25.Size = new Size(61, 58);
            bunifuButton25.TabIndex = 6;
            bunifuButton25.TextAlign = ContentAlignment.MiddleCenter;
            bunifuButton25.TextAlignment = HorizontalAlignment.Center;
            bunifuButton25.TextMarginLeft = 0;
            bunifuButton25.TextPadding = new Padding(0);
            bunifuButton25.UseDefaultRadiusAndThickness = true;
            // 
            // bunifuButton26
            // 
            bunifuButton26.AllowAnimations = true;
            bunifuButton26.AllowMouseEffects = true;
            bunifuButton26.AllowToggling = false;
            bunifuButton26.AnimationSpeed = 200;
            bunifuButton26.AutoGenerateColors = false;
            bunifuButton26.AutoRoundBorders = false;
            bunifuButton26.AutoSizeLeftIcon = true;
            bunifuButton26.AutoSizeRightIcon = true;
            bunifuButton26.BackColor = Color.Transparent;
            bunifuButton26.BackColor1 = Color.White;
            bunifuButton26.BackgroundImage = (Image)resources.GetObject("bunifuButton26.BackgroundImage");
            bunifuButton26.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            bunifuButton26.ButtonText = "";
            bunifuButton26.ButtonTextMarginLeft = 0;
            bunifuButton26.ColorContrastOnClick = 45;
            bunifuButton26.ColorContrastOnHover = 45;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            bunifuButton26.CustomizableEdges = borderEdges1;
            bunifuButton26.DialogResult = DialogResult.None;
            bunifuButton26.DisabledBorderColor = Color.FromArgb(191, 191, 191);
            bunifuButton26.DisabledFillColor = Color.FromArgb(204, 204, 204);
            bunifuButton26.DisabledForecolor = Color.FromArgb(168, 160, 168);
            bunifuButton26.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            bunifuButton26.Font = new Font("Segoe UI", 9F);
            bunifuButton26.ForeColor = Color.White;
            bunifuButton26.IconLeftAlign = ContentAlignment.MiddleLeft;
            bunifuButton26.IconLeftCursor = Cursors.Default;
            bunifuButton26.IconLeftPadding = new Padding(11, 3, 3, 3);
            bunifuButton26.IconMarginLeft = 11;
            bunifuButton26.IconPadding = 10;
            bunifuButton26.IconRightAlign = ContentAlignment.MiddleRight;
            bunifuButton26.IconRightCursor = Cursors.Default;
            bunifuButton26.IconRightPadding = new Padding(3, 3, 7, 3);
            bunifuButton26.IconSize = 25;
            bunifuButton26.IdleBorderColor = Color.White;
            bunifuButton26.IdleBorderRadius = 1;
            bunifuButton26.IdleBorderThickness = 1;
            bunifuButton26.IdleFillColor = Color.White;
            bunifuButton26.IdleIconLeftImage = (Image)resources.GetObject("bunifuButton26.IdleIconLeftImage");
            bunifuButton26.IdleIconRightImage = null;
            bunifuButton26.IndicateFocus = false;
            bunifuButton26.Location = new Point(35, 712);
            bunifuButton26.Name = "bunifuButton26";
            bunifuButton26.OnDisabledState.BorderColor = Color.FromArgb(191, 191, 191);
            bunifuButton26.OnDisabledState.BorderRadius = 1;
            bunifuButton26.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            bunifuButton26.OnDisabledState.BorderThickness = 1;
            bunifuButton26.OnDisabledState.FillColor = Color.FromArgb(204, 204, 204);
            bunifuButton26.OnDisabledState.ForeColor = Color.FromArgb(168, 160, 168);
            bunifuButton26.OnDisabledState.IconLeftImage = null;
            bunifuButton26.OnDisabledState.IconRightImage = null;
            bunifuButton26.onHoverState.BorderColor = Color.DarkGoldenrod;
            bunifuButton26.onHoverState.BorderRadius = 1;
            bunifuButton26.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            bunifuButton26.onHoverState.BorderThickness = 1;
            bunifuButton26.onHoverState.FillColor = Color.White;
            bunifuButton26.onHoverState.ForeColor = Color.White;
            bunifuButton26.onHoverState.IconLeftImage = null;
            bunifuButton26.onHoverState.IconRightImage = null;
            bunifuButton26.OnIdleState.BorderColor = Color.White;
            bunifuButton26.OnIdleState.BorderRadius = 1;
            bunifuButton26.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            bunifuButton26.OnIdleState.BorderThickness = 1;
            bunifuButton26.OnIdleState.FillColor = Color.White;
            bunifuButton26.OnIdleState.ForeColor = Color.White;
            bunifuButton26.OnIdleState.IconLeftImage = (Image)resources.GetObject("bunifuButton26.OnIdleState.IconLeftImage");
            bunifuButton26.OnIdleState.IconRightImage = null;
            bunifuButton26.OnPressedState.BorderColor = Color.Lime;
            bunifuButton26.OnPressedState.BorderRadius = 1;
            bunifuButton26.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            bunifuButton26.OnPressedState.BorderThickness = 1;
            bunifuButton26.OnPressedState.FillColor = Color.White;
            bunifuButton26.OnPressedState.ForeColor = Color.White;
            bunifuButton26.OnPressedState.IconLeftImage = null;
            bunifuButton26.OnPressedState.IconRightImage = null;
            bunifuButton26.Size = new Size(61, 58);
            bunifuButton26.TabIndex = 8;
            bunifuButton26.TextAlign = ContentAlignment.MiddleCenter;
            bunifuButton26.TextAlignment = HorizontalAlignment.Center;
            bunifuButton26.TextMarginLeft = 0;
            bunifuButton26.TextPadding = new Padding(0);
            bunifuButton26.UseDefaultRadiusAndThickness = true;
            // 
            // bunifuButton27
            // 
            bunifuButton27.AllowAnimations = true;
            bunifuButton27.AllowMouseEffects = true;
            bunifuButton27.AllowToggling = false;
            bunifuButton27.AnimationSpeed = 200;
            bunifuButton27.AutoGenerateColors = false;
            bunifuButton27.AutoRoundBorders = false;
            bunifuButton27.AutoSizeLeftIcon = true;
            bunifuButton27.AutoSizeRightIcon = true;
            bunifuButton27.BackColor = Color.Transparent;
            bunifuButton27.BackColor1 = Color.White;
            bunifuButton27.BackgroundImage = (Image)resources.GetObject("bunifuButton27.BackgroundImage");
            bunifuButton27.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            bunifuButton27.ButtonText = "";
            bunifuButton27.ButtonTextMarginLeft = 0;
            bunifuButton27.ColorContrastOnClick = 45;
            bunifuButton27.ColorContrastOnHover = 45;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            bunifuButton27.CustomizableEdges = borderEdges2;
            bunifuButton27.DialogResult = DialogResult.None;
            bunifuButton27.DisabledBorderColor = Color.FromArgb(191, 191, 191);
            bunifuButton27.DisabledFillColor = Color.FromArgb(204, 204, 204);
            bunifuButton27.DisabledForecolor = Color.FromArgb(168, 160, 168);
            bunifuButton27.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            bunifuButton27.Font = new Font("Segoe UI", 9F);
            bunifuButton27.ForeColor = Color.White;
            bunifuButton27.IconLeftAlign = ContentAlignment.MiddleLeft;
            bunifuButton27.IconLeftCursor = Cursors.Default;
            bunifuButton27.IconLeftPadding = new Padding(11, 3, 3, 3);
            bunifuButton27.IconMarginLeft = 11;
            bunifuButton27.IconPadding = 10;
            bunifuButton27.IconRightAlign = ContentAlignment.MiddleRight;
            bunifuButton27.IconRightCursor = Cursors.Default;
            bunifuButton27.IconRightPadding = new Padding(3, 3, 7, 3);
            bunifuButton27.IconSize = 25;
            bunifuButton27.IdleBorderColor = Color.White;
            bunifuButton27.IdleBorderRadius = 1;
            bunifuButton27.IdleBorderThickness = 1;
            bunifuButton27.IdleFillColor = Color.White;
            bunifuButton27.IdleIconLeftImage = (Image)resources.GetObject("bunifuButton27.IdleIconLeftImage");
            bunifuButton27.IdleIconRightImage = null;
            bunifuButton27.IndicateFocus = false;
            bunifuButton27.Location = new Point(35, 638);
            bunifuButton27.Name = "bunifuButton27";
            bunifuButton27.OnDisabledState.BorderColor = Color.FromArgb(191, 191, 191);
            bunifuButton27.OnDisabledState.BorderRadius = 1;
            bunifuButton27.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            bunifuButton27.OnDisabledState.BorderThickness = 1;
            bunifuButton27.OnDisabledState.FillColor = Color.FromArgb(204, 204, 204);
            bunifuButton27.OnDisabledState.ForeColor = Color.FromArgb(168, 160, 168);
            bunifuButton27.OnDisabledState.IconLeftImage = null;
            bunifuButton27.OnDisabledState.IconRightImage = null;
            bunifuButton27.onHoverState.BorderColor = Color.DarkGoldenrod;
            bunifuButton27.onHoverState.BorderRadius = 1;
            bunifuButton27.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            bunifuButton27.onHoverState.BorderThickness = 1;
            bunifuButton27.onHoverState.FillColor = Color.White;
            bunifuButton27.onHoverState.ForeColor = Color.White;
            bunifuButton27.onHoverState.IconLeftImage = null;
            bunifuButton27.onHoverState.IconRightImage = null;
            bunifuButton27.OnIdleState.BorderColor = Color.White;
            bunifuButton27.OnIdleState.BorderRadius = 1;
            bunifuButton27.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            bunifuButton27.OnIdleState.BorderThickness = 1;
            bunifuButton27.OnIdleState.FillColor = Color.White;
            bunifuButton27.OnIdleState.ForeColor = Color.White;
            bunifuButton27.OnIdleState.IconLeftImage = (Image)resources.GetObject("bunifuButton27.OnIdleState.IconLeftImage");
            bunifuButton27.OnIdleState.IconRightImage = null;
            bunifuButton27.OnPressedState.BorderColor = Color.Lime;
            bunifuButton27.OnPressedState.BorderRadius = 1;
            bunifuButton27.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            bunifuButton27.OnPressedState.BorderThickness = 1;
            bunifuButton27.OnPressedState.FillColor = Color.White;
            bunifuButton27.OnPressedState.ForeColor = Color.White;
            bunifuButton27.OnPressedState.IconLeftImage = null;
            bunifuButton27.OnPressedState.IconRightImage = null;
            bunifuButton27.Size = new Size(61, 58);
            bunifuButton27.TabIndex = 7;
            bunifuButton27.TextAlign = ContentAlignment.MiddleCenter;
            bunifuButton27.TextAlignment = HorizontalAlignment.Center;
            bunifuButton27.TextMarginLeft = 0;
            bunifuButton27.TextPadding = new Padding(0);
            bunifuButton27.UseDefaultRadiusAndThickness = true;
            // 
            // Dashboard
            // 
            AutoScaleDimensions = new SizeF(7F, 15F);
            AutoScaleMode = AutoScaleMode.Font;
            ClientSize = new Size(1386, 788);
            Controls.Add(bunifuPanel2);
            Controls.Add(bunifuPanel1);
            FormBorderStyle = FormBorderStyle.None;
            Name = "Dashboard";
            StartPosition = FormStartPosition.CenterScreen;
            Text = "Dashboard";
            bunifuPanel1.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)bunifuPictureBox1).EndInit();
            ResumeLayout(false);
        }

        #endregion

        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel1;
        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel2;
        private Bunifu.UI.WinForms.BunifuPictureBox bunifuPictureBox1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 bunifuButton21;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 bunifuButton22;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 bunifuButton24;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 bunifuButton23;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 bunifuButton26;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 bunifuButton27;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 bunifuButton25;
    }
}