namespace Spa_Management_System
{
    partial class Invoice
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Invoice));
            Bunifu.UI.WinForms.BunifuButton.BunifuIconButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuIconButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            DataGridViewCellStyle dataGridViewCellStyle1 = new DataGridViewCellStyle();
            DataGridViewCellStyle dataGridViewCellStyle2 = new DataGridViewCellStyle();
            DataGridViewCellStyle dataGridViewCellStyle3 = new DataGridViewCellStyle();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            bunifuPanel2 = new Bunifu.UI.WinForms.BunifuPanel();
            label11 = new Label();
            btnExitProgram = new Bunifu.UI.WinForms.BunifuButton.BunifuIconButton();
            btnClear = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            btnDelete = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            btnUpdate = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            btnInsert = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            btnNew = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            txtSearch = new Bunifu.UI.WinForms.BunifuTextBox();
            dgvInvoice = new Bunifu.UI.WinForms.BunifuDataGridView();
            txtID = new Bunifu.UI.WinForms.BunifuTextBox();
            label1 = new Label();
            txtOrderID = new Bunifu.UI.WinForms.BunifuTextBox();
            label2 = new Label();
            txtInvoiceDate = new Bunifu.UI.WinForms.BunifuTextBox();
            label3 = new Label();
            txtTotalAmount = new Bunifu.UI.WinForms.BunifuTextBox();
            label4 = new Label();
            txtNotes = new Bunifu.UI.WinForms.BunifuTextBox();
            label5 = new Label();
            FormDock = new Bunifu.UI.WinForms.BunifuFormDock();
            bunifuPanel2.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)dgvInvoice).BeginInit();
            SuspendLayout();
            // 
            // bunifuPanel2
            // 
            bunifuPanel2.BackgroundColor = Color.White;
            bunifuPanel2.BackgroundImage = (Image)resources.GetObject("bunifuPanel2.BackgroundImage");
            bunifuPanel2.BackgroundImageLayout = ImageLayout.Stretch;
            bunifuPanel2.BorderColor = Color.Transparent;
            bunifuPanel2.BorderRadius = 3;
            bunifuPanel2.BorderThickness = 1;
            bunifuPanel2.Controls.Add(label11);
            bunifuPanel2.Controls.Add(btnExitProgram);
            bunifuPanel2.Dock = DockStyle.Top;
            bunifuPanel2.Location = new Point(0, 0);
            bunifuPanel2.Name = "bunifuPanel2";
            bunifuPanel2.ShowBorders = true;
            bunifuPanel2.Size = new Size(1149, 65);
            bunifuPanel2.TabIndex = 90;
            // 
            // label11
            // 
            label11.AutoSize = true;
            label11.BackColor = Color.Transparent;
            label11.Font = new Font("Microsoft Sans Serif", 14.25F, FontStyle.Bold, GraphicsUnit.Point, 0);
            label11.Location = new Point(474, 15);
            label11.Name = "label11";
            label11.Size = new Size(204, 24);
            label11.TabIndex = 74;
            label11.Text = "Invoice Management";
            // 
            // btnExitProgram
            // 
            btnExitProgram.AllowAnimations = true;
            btnExitProgram.AllowBorderColorChanges = true;
            btnExitProgram.AllowMouseEffects = true;
            btnExitProgram.AnimationSpeed = 200;
            btnExitProgram.BackColor = Color.Transparent;
            btnExitProgram.BackgroundColor = Color.Transparent;
            btnExitProgram.BorderColor = Color.Transparent;
            btnExitProgram.BorderRadius = 1;
            btnExitProgram.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuIconButton.BorderStyles.Solid;
            btnExitProgram.BorderThickness = 1;
            btnExitProgram.ColorContrastOnClick = 30;
            btnExitProgram.ColorContrastOnHover = -30;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            btnExitProgram.CustomizableEdges = borderEdges1;
            btnExitProgram.DialogResult = DialogResult.None;
            btnExitProgram.Image = (Image)resources.GetObject("btnExitProgram.Image");
            btnExitProgram.ImageMargin = new Padding(0);
            btnExitProgram.Location = new Point(1113, 12);
            btnExitProgram.Name = "btnExitProgram";
            btnExitProgram.RoundBorders = true;
            btnExitProgram.ShowBorders = true;
            btnExitProgram.Size = new Size(26, 26);
            btnExitProgram.Style = Bunifu.UI.WinForms.BunifuButton.BunifuIconButton.ButtonStyles.Round;
            btnExitProgram.TabIndex = 69;
            btnExitProgram.Click += btnExitProgram_Click;
            // 
            // btnClear
            // 
            btnClear.AllowAnimations = true;
            btnClear.AllowMouseEffects = true;
            btnClear.AllowToggling = false;
            btnClear.AnimationSpeed = 200;
            btnClear.AutoGenerateColors = false;
            btnClear.AutoRoundBorders = false;
            btnClear.AutoSizeLeftIcon = true;
            btnClear.AutoSizeRightIcon = true;
            btnClear.BackColor = Color.Transparent;
            btnClear.BackColor1 = Color.White;
            btnClear.BackgroundImage = (Image)resources.GetObject("btnClear.BackgroundImage");
            btnClear.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnClear.ButtonText = "Clear";
            btnClear.ButtonTextMarginLeft = 0;
            btnClear.ColorContrastOnClick = 45;
            btnClear.ColorContrastOnHover = 45;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            btnClear.CustomizableEdges = borderEdges2;
            btnClear.DialogResult = DialogResult.None;
            btnClear.DisabledBorderColor = Color.FromArgb(191, 191, 191);
            btnClear.DisabledFillColor = Color.FromArgb(204, 204, 204);
            btnClear.DisabledForecolor = Color.FromArgb(168, 160, 168);
            btnClear.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            btnClear.Font = new Font("Sitka Text", 9F);
            btnClear.ForeColor = Color.Black;
            btnClear.IconLeftAlign = ContentAlignment.MiddleLeft;
            btnClear.IconLeftCursor = Cursors.Default;
            btnClear.IconLeftPadding = new Padding(11, 3, 3, 3);
            btnClear.IconMarginLeft = 11;
            btnClear.IconPadding = 10;
            btnClear.IconRightAlign = ContentAlignment.MiddleRight;
            btnClear.IconRightCursor = Cursors.Default;
            btnClear.IconRightPadding = new Padding(3, 3, 7, 3);
            btnClear.IconSize = 25;
            btnClear.IdleBorderColor = Color.White;
            btnClear.IdleBorderRadius = 35;
            btnClear.IdleBorderThickness = 1;
            btnClear.IdleFillColor = Color.White;
            btnClear.IdleIconLeftImage = null;
            btnClear.IdleIconRightImage = null;
            btnClear.IndicateFocus = false;
            btnClear.Location = new Point(354, 76);
            btnClear.Name = "btnClear";
            btnClear.OnDisabledState.BorderColor = Color.FromArgb(191, 191, 191);
            btnClear.OnDisabledState.BorderRadius = 35;
            btnClear.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnClear.OnDisabledState.BorderThickness = 1;
            btnClear.OnDisabledState.FillColor = Color.FromArgb(204, 204, 204);
            btnClear.OnDisabledState.ForeColor = Color.FromArgb(168, 160, 168);
            btnClear.OnDisabledState.IconLeftImage = null;
            btnClear.OnDisabledState.IconRightImage = null;
            btnClear.onHoverState.BorderColor = Color.DarkGoldenrod;
            btnClear.onHoverState.BorderRadius = 35;
            btnClear.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnClear.onHoverState.BorderThickness = 1;
            btnClear.onHoverState.FillColor = Color.White;
            btnClear.onHoverState.ForeColor = Color.Black;
            btnClear.onHoverState.IconLeftImage = null;
            btnClear.onHoverState.IconRightImage = null;
            btnClear.OnIdleState.BorderColor = Color.White;
            btnClear.OnIdleState.BorderRadius = 35;
            btnClear.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnClear.OnIdleState.BorderThickness = 1;
            btnClear.OnIdleState.FillColor = Color.White;
            btnClear.OnIdleState.ForeColor = Color.Black;
            btnClear.OnIdleState.IconLeftImage = null;
            btnClear.OnIdleState.IconRightImage = null;
            btnClear.OnPressedState.BorderColor = Color.FromArgb(40, 96, 144);
            btnClear.OnPressedState.BorderRadius = 35;
            btnClear.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnClear.OnPressedState.BorderThickness = 1;
            btnClear.OnPressedState.FillColor = Color.FromArgb(40, 96, 144);
            btnClear.OnPressedState.ForeColor = Color.White;
            btnClear.OnPressedState.IconLeftImage = null;
            btnClear.OnPressedState.IconRightImage = null;
            btnClear.Size = new Size(80, 39);
            btnClear.TabIndex = 110;
            btnClear.TextAlign = ContentAlignment.MiddleCenter;
            btnClear.TextAlignment = HorizontalAlignment.Center;
            btnClear.TextMarginLeft = 0;
            btnClear.TextPadding = new Padding(0);
            btnClear.UseDefaultRadiusAndThickness = true;
            // 
            // btnDelete
            // 
            btnDelete.AllowAnimations = true;
            btnDelete.AllowMouseEffects = true;
            btnDelete.AllowToggling = false;
            btnDelete.AnimationSpeed = 200;
            btnDelete.AutoGenerateColors = false;
            btnDelete.AutoRoundBorders = false;
            btnDelete.AutoSizeLeftIcon = true;
            btnDelete.AutoSizeRightIcon = true;
            btnDelete.BackColor = Color.Transparent;
            btnDelete.BackColor1 = Color.White;
            btnDelete.BackgroundImage = (Image)resources.GetObject("btnDelete.BackgroundImage");
            btnDelete.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnDelete.ButtonText = "Delete";
            btnDelete.ButtonTextMarginLeft = 0;
            btnDelete.ColorContrastOnClick = 45;
            btnDelete.ColorContrastOnHover = 45;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            btnDelete.CustomizableEdges = borderEdges3;
            btnDelete.DialogResult = DialogResult.None;
            btnDelete.DisabledBorderColor = Color.FromArgb(191, 191, 191);
            btnDelete.DisabledFillColor = Color.FromArgb(204, 204, 204);
            btnDelete.DisabledForecolor = Color.FromArgb(168, 160, 168);
            btnDelete.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            btnDelete.Font = new Font("Sitka Text", 9F);
            btnDelete.ForeColor = Color.Black;
            btnDelete.IconLeftAlign = ContentAlignment.MiddleLeft;
            btnDelete.IconLeftCursor = Cursors.Default;
            btnDelete.IconLeftPadding = new Padding(11, 3, 3, 3);
            btnDelete.IconMarginLeft = 11;
            btnDelete.IconPadding = 10;
            btnDelete.IconRightAlign = ContentAlignment.MiddleRight;
            btnDelete.IconRightCursor = Cursors.Default;
            btnDelete.IconRightPadding = new Padding(3, 3, 7, 3);
            btnDelete.IconSize = 25;
            btnDelete.IdleBorderColor = Color.White;
            btnDelete.IdleBorderRadius = 35;
            btnDelete.IdleBorderThickness = 1;
            btnDelete.IdleFillColor = Color.White;
            btnDelete.IdleIconLeftImage = null;
            btnDelete.IdleIconRightImage = null;
            btnDelete.IndicateFocus = false;
            btnDelete.Location = new Point(268, 76);
            btnDelete.Name = "btnDelete";
            btnDelete.OnDisabledState.BorderColor = Color.FromArgb(191, 191, 191);
            btnDelete.OnDisabledState.BorderRadius = 35;
            btnDelete.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnDelete.OnDisabledState.BorderThickness = 1;
            btnDelete.OnDisabledState.FillColor = Color.FromArgb(204, 204, 204);
            btnDelete.OnDisabledState.ForeColor = Color.FromArgb(168, 160, 168);
            btnDelete.OnDisabledState.IconLeftImage = null;
            btnDelete.OnDisabledState.IconRightImage = null;
            btnDelete.onHoverState.BorderColor = Color.DarkGoldenrod;
            btnDelete.onHoverState.BorderRadius = 35;
            btnDelete.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnDelete.onHoverState.BorderThickness = 1;
            btnDelete.onHoverState.FillColor = Color.White;
            btnDelete.onHoverState.ForeColor = Color.Black;
            btnDelete.onHoverState.IconLeftImage = null;
            btnDelete.onHoverState.IconRightImage = null;
            btnDelete.OnIdleState.BorderColor = Color.White;
            btnDelete.OnIdleState.BorderRadius = 35;
            btnDelete.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnDelete.OnIdleState.BorderThickness = 1;
            btnDelete.OnIdleState.FillColor = Color.White;
            btnDelete.OnIdleState.ForeColor = Color.Black;
            btnDelete.OnIdleState.IconLeftImage = null;
            btnDelete.OnIdleState.IconRightImage = null;
            btnDelete.OnPressedState.BorderColor = Color.FromArgb(40, 96, 144);
            btnDelete.OnPressedState.BorderRadius = 35;
            btnDelete.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnDelete.OnPressedState.BorderThickness = 1;
            btnDelete.OnPressedState.FillColor = Color.FromArgb(40, 96, 144);
            btnDelete.OnPressedState.ForeColor = Color.White;
            btnDelete.OnPressedState.IconLeftImage = null;
            btnDelete.OnPressedState.IconRightImage = null;
            btnDelete.Size = new Size(80, 39);
            btnDelete.TabIndex = 109;
            btnDelete.TextAlign = ContentAlignment.MiddleCenter;
            btnDelete.TextAlignment = HorizontalAlignment.Center;
            btnDelete.TextMarginLeft = 0;
            btnDelete.TextPadding = new Padding(0);
            btnDelete.UseDefaultRadiusAndThickness = true;
            // 
            // btnUpdate
            // 
            btnUpdate.AllowAnimations = true;
            btnUpdate.AllowMouseEffects = true;
            btnUpdate.AllowToggling = false;
            btnUpdate.AnimationSpeed = 200;
            btnUpdate.AutoGenerateColors = false;
            btnUpdate.AutoRoundBorders = false;
            btnUpdate.AutoSizeLeftIcon = true;
            btnUpdate.AutoSizeRightIcon = true;
            btnUpdate.BackColor = Color.Transparent;
            btnUpdate.BackColor1 = Color.White;
            btnUpdate.BackgroundImage = (Image)resources.GetObject("btnUpdate.BackgroundImage");
            btnUpdate.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnUpdate.ButtonText = "Update";
            btnUpdate.ButtonTextMarginLeft = 0;
            btnUpdate.ColorContrastOnClick = 45;
            btnUpdate.ColorContrastOnHover = 45;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            btnUpdate.CustomizableEdges = borderEdges4;
            btnUpdate.DialogResult = DialogResult.None;
            btnUpdate.DisabledBorderColor = Color.FromArgb(191, 191, 191);
            btnUpdate.DisabledFillColor = Color.FromArgb(204, 204, 204);
            btnUpdate.DisabledForecolor = Color.FromArgb(168, 160, 168);
            btnUpdate.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            btnUpdate.Font = new Font("Sitka Text", 9F);
            btnUpdate.ForeColor = Color.Black;
            btnUpdate.IconLeftAlign = ContentAlignment.MiddleLeft;
            btnUpdate.IconLeftCursor = Cursors.Default;
            btnUpdate.IconLeftPadding = new Padding(11, 3, 3, 3);
            btnUpdate.IconMarginLeft = 11;
            btnUpdate.IconPadding = 10;
            btnUpdate.IconRightAlign = ContentAlignment.MiddleRight;
            btnUpdate.IconRightCursor = Cursors.Default;
            btnUpdate.IconRightPadding = new Padding(3, 3, 7, 3);
            btnUpdate.IconSize = 25;
            btnUpdate.IdleBorderColor = Color.White;
            btnUpdate.IdleBorderRadius = 35;
            btnUpdate.IdleBorderThickness = 1;
            btnUpdate.IdleFillColor = Color.White;
            btnUpdate.IdleIconLeftImage = null;
            btnUpdate.IdleIconRightImage = null;
            btnUpdate.IndicateFocus = false;
            btnUpdate.Location = new Point(182, 76);
            btnUpdate.Name = "btnUpdate";
            btnUpdate.OnDisabledState.BorderColor = Color.FromArgb(191, 191, 191);
            btnUpdate.OnDisabledState.BorderRadius = 35;
            btnUpdate.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnUpdate.OnDisabledState.BorderThickness = 1;
            btnUpdate.OnDisabledState.FillColor = Color.FromArgb(204, 204, 204);
            btnUpdate.OnDisabledState.ForeColor = Color.FromArgb(168, 160, 168);
            btnUpdate.OnDisabledState.IconLeftImage = null;
            btnUpdate.OnDisabledState.IconRightImage = null;
            btnUpdate.onHoverState.BorderColor = Color.DarkGoldenrod;
            btnUpdate.onHoverState.BorderRadius = 35;
            btnUpdate.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnUpdate.onHoverState.BorderThickness = 1;
            btnUpdate.onHoverState.FillColor = Color.White;
            btnUpdate.onHoverState.ForeColor = Color.Black;
            btnUpdate.onHoverState.IconLeftImage = null;
            btnUpdate.onHoverState.IconRightImage = null;
            btnUpdate.OnIdleState.BorderColor = Color.White;
            btnUpdate.OnIdleState.BorderRadius = 35;
            btnUpdate.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnUpdate.OnIdleState.BorderThickness = 1;
            btnUpdate.OnIdleState.FillColor = Color.White;
            btnUpdate.OnIdleState.ForeColor = Color.Black;
            btnUpdate.OnIdleState.IconLeftImage = null;
            btnUpdate.OnIdleState.IconRightImage = null;
            btnUpdate.OnPressedState.BorderColor = Color.FromArgb(40, 96, 144);
            btnUpdate.OnPressedState.BorderRadius = 35;
            btnUpdate.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnUpdate.OnPressedState.BorderThickness = 1;
            btnUpdate.OnPressedState.FillColor = Color.FromArgb(40, 96, 144);
            btnUpdate.OnPressedState.ForeColor = Color.White;
            btnUpdate.OnPressedState.IconLeftImage = null;
            btnUpdate.OnPressedState.IconRightImage = null;
            btnUpdate.Size = new Size(80, 39);
            btnUpdate.TabIndex = 108;
            btnUpdate.TextAlign = ContentAlignment.MiddleCenter;
            btnUpdate.TextAlignment = HorizontalAlignment.Center;
            btnUpdate.TextMarginLeft = 0;
            btnUpdate.TextPadding = new Padding(0);
            btnUpdate.UseDefaultRadiusAndThickness = true;
            // 
            // btnInsert
            // 
            btnInsert.AllowAnimations = true;
            btnInsert.AllowMouseEffects = true;
            btnInsert.AllowToggling = false;
            btnInsert.AnimationSpeed = 200;
            btnInsert.AutoGenerateColors = false;
            btnInsert.AutoRoundBorders = false;
            btnInsert.AutoSizeLeftIcon = true;
            btnInsert.AutoSizeRightIcon = true;
            btnInsert.BackColor = Color.Transparent;
            btnInsert.BackColor1 = Color.White;
            btnInsert.BackgroundImage = (Image)resources.GetObject("btnInsert.BackgroundImage");
            btnInsert.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnInsert.ButtonText = "Insert";
            btnInsert.ButtonTextMarginLeft = 0;
            btnInsert.ColorContrastOnClick = 45;
            btnInsert.ColorContrastOnHover = 45;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            btnInsert.CustomizableEdges = borderEdges5;
            btnInsert.DialogResult = DialogResult.None;
            btnInsert.DisabledBorderColor = Color.FromArgb(191, 191, 191);
            btnInsert.DisabledFillColor = Color.FromArgb(204, 204, 204);
            btnInsert.DisabledForecolor = Color.FromArgb(168, 160, 168);
            btnInsert.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            btnInsert.Font = new Font("Sitka Text", 9F);
            btnInsert.ForeColor = Color.Black;
            btnInsert.IconLeftAlign = ContentAlignment.MiddleLeft;
            btnInsert.IconLeftCursor = Cursors.Default;
            btnInsert.IconLeftPadding = new Padding(11, 3, 3, 3);
            btnInsert.IconMarginLeft = 11;
            btnInsert.IconPadding = 10;
            btnInsert.IconRightAlign = ContentAlignment.MiddleRight;
            btnInsert.IconRightCursor = Cursors.Default;
            btnInsert.IconRightPadding = new Padding(3, 3, 7, 3);
            btnInsert.IconSize = 25;
            btnInsert.IdleBorderColor = Color.White;
            btnInsert.IdleBorderRadius = 35;
            btnInsert.IdleBorderThickness = 1;
            btnInsert.IdleFillColor = Color.White;
            btnInsert.IdleIconLeftImage = null;
            btnInsert.IdleIconRightImage = null;
            btnInsert.IndicateFocus = false;
            btnInsert.Location = new Point(96, 76);
            btnInsert.Name = "btnInsert";
            btnInsert.OnDisabledState.BorderColor = Color.FromArgb(191, 191, 191);
            btnInsert.OnDisabledState.BorderRadius = 35;
            btnInsert.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnInsert.OnDisabledState.BorderThickness = 1;
            btnInsert.OnDisabledState.FillColor = Color.FromArgb(204, 204, 204);
            btnInsert.OnDisabledState.ForeColor = Color.FromArgb(168, 160, 168);
            btnInsert.OnDisabledState.IconLeftImage = null;
            btnInsert.OnDisabledState.IconRightImage = null;
            btnInsert.onHoverState.BorderColor = Color.DarkGoldenrod;
            btnInsert.onHoverState.BorderRadius = 35;
            btnInsert.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnInsert.onHoverState.BorderThickness = 1;
            btnInsert.onHoverState.FillColor = Color.White;
            btnInsert.onHoverState.ForeColor = Color.Black;
            btnInsert.onHoverState.IconLeftImage = null;
            btnInsert.onHoverState.IconRightImage = null;
            btnInsert.OnIdleState.BorderColor = Color.White;
            btnInsert.OnIdleState.BorderRadius = 35;
            btnInsert.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnInsert.OnIdleState.BorderThickness = 1;
            btnInsert.OnIdleState.FillColor = Color.White;
            btnInsert.OnIdleState.ForeColor = Color.Black;
            btnInsert.OnIdleState.IconLeftImage = null;
            btnInsert.OnIdleState.IconRightImage = null;
            btnInsert.OnPressedState.BorderColor = Color.FromArgb(40, 96, 144);
            btnInsert.OnPressedState.BorderRadius = 35;
            btnInsert.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnInsert.OnPressedState.BorderThickness = 1;
            btnInsert.OnPressedState.FillColor = Color.FromArgb(40, 96, 144);
            btnInsert.OnPressedState.ForeColor = Color.White;
            btnInsert.OnPressedState.IconLeftImage = null;
            btnInsert.OnPressedState.IconRightImage = null;
            btnInsert.Size = new Size(80, 39);
            btnInsert.TabIndex = 107;
            btnInsert.TextAlign = ContentAlignment.MiddleCenter;
            btnInsert.TextAlignment = HorizontalAlignment.Center;
            btnInsert.TextMarginLeft = 0;
            btnInsert.TextPadding = new Padding(0);
            btnInsert.UseDefaultRadiusAndThickness = true;
            // 
            // btnNew
            // 
            btnNew.AllowAnimations = true;
            btnNew.AllowMouseEffects = true;
            btnNew.AllowToggling = false;
            btnNew.AnimationSpeed = 200;
            btnNew.AutoGenerateColors = false;
            btnNew.AutoRoundBorders = false;
            btnNew.AutoSizeLeftIcon = true;
            btnNew.AutoSizeRightIcon = true;
            btnNew.BackColor = Color.Transparent;
            btnNew.BackColor1 = Color.White;
            btnNew.BackgroundImage = (Image)resources.GetObject("btnNew.BackgroundImage");
            btnNew.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnNew.ButtonText = "New";
            btnNew.ButtonTextMarginLeft = 0;
            btnNew.ColorContrastOnClick = 45;
            btnNew.ColorContrastOnHover = 45;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            btnNew.CustomizableEdges = borderEdges6;
            btnNew.DialogResult = DialogResult.None;
            btnNew.DisabledBorderColor = Color.FromArgb(191, 191, 191);
            btnNew.DisabledFillColor = Color.FromArgb(204, 204, 204);
            btnNew.DisabledForecolor = Color.FromArgb(168, 160, 168);
            btnNew.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            btnNew.Font = new Font("Sitka Text", 9F);
            btnNew.ForeColor = Color.Black;
            btnNew.IconLeftAlign = ContentAlignment.MiddleLeft;
            btnNew.IconLeftCursor = Cursors.Default;
            btnNew.IconLeftPadding = new Padding(11, 3, 3, 3);
            btnNew.IconMarginLeft = 11;
            btnNew.IconPadding = 10;
            btnNew.IconRightAlign = ContentAlignment.MiddleRight;
            btnNew.IconRightCursor = Cursors.Default;
            btnNew.IconRightPadding = new Padding(3, 3, 7, 3);
            btnNew.IconSize = 25;
            btnNew.IdleBorderColor = Color.White;
            btnNew.IdleBorderRadius = 35;
            btnNew.IdleBorderThickness = 1;
            btnNew.IdleFillColor = Color.White;
            btnNew.IdleIconLeftImage = null;
            btnNew.IdleIconRightImage = null;
            btnNew.IndicateFocus = false;
            btnNew.Location = new Point(10, 76);
            btnNew.Name = "btnNew";
            btnNew.OnDisabledState.BorderColor = Color.FromArgb(191, 191, 191);
            btnNew.OnDisabledState.BorderRadius = 35;
            btnNew.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnNew.OnDisabledState.BorderThickness = 1;
            btnNew.OnDisabledState.FillColor = Color.FromArgb(204, 204, 204);
            btnNew.OnDisabledState.ForeColor = Color.FromArgb(168, 160, 168);
            btnNew.OnDisabledState.IconLeftImage = null;
            btnNew.OnDisabledState.IconRightImage = null;
            btnNew.onHoverState.BorderColor = Color.DarkGoldenrod;
            btnNew.onHoverState.BorderRadius = 35;
            btnNew.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnNew.onHoverState.BorderThickness = 1;
            btnNew.onHoverState.FillColor = Color.White;
            btnNew.onHoverState.ForeColor = Color.Black;
            btnNew.onHoverState.IconLeftImage = null;
            btnNew.onHoverState.IconRightImage = null;
            btnNew.OnIdleState.BorderColor = Color.White;
            btnNew.OnIdleState.BorderRadius = 35;
            btnNew.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnNew.OnIdleState.BorderThickness = 1;
            btnNew.OnIdleState.FillColor = Color.White;
            btnNew.OnIdleState.ForeColor = Color.Black;
            btnNew.OnIdleState.IconLeftImage = null;
            btnNew.OnIdleState.IconRightImage = null;
            btnNew.OnPressedState.BorderColor = Color.FromArgb(40, 96, 144);
            btnNew.OnPressedState.BorderRadius = 35;
            btnNew.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnNew.OnPressedState.BorderThickness = 1;
            btnNew.OnPressedState.FillColor = Color.FromArgb(40, 96, 144);
            btnNew.OnPressedState.ForeColor = Color.White;
            btnNew.OnPressedState.IconLeftImage = null;
            btnNew.OnPressedState.IconRightImage = null;
            btnNew.Size = new Size(80, 39);
            btnNew.TabIndex = 106;
            btnNew.TextAlign = ContentAlignment.MiddleCenter;
            btnNew.TextAlignment = HorizontalAlignment.Center;
            btnNew.TextMarginLeft = 0;
            btnNew.TextPadding = new Padding(0);
            btnNew.UseDefaultRadiusAndThickness = true;
            // 
            // txtSearch
            // 
            txtSearch.AcceptsReturn = false;
            txtSearch.AcceptsTab = false;
            txtSearch.AnimationSpeed = 200;
            txtSearch.AutoCompleteMode = AutoCompleteMode.None;
            txtSearch.AutoCompleteSource = AutoCompleteSource.None;
            txtSearch.AutoSizeHeight = true;
            txtSearch.BackColor = Color.Transparent;
            txtSearch.BackgroundImage = (Image)resources.GetObject("txtSearch.BackgroundImage");
            txtSearch.BorderColorActive = Color.DarkGoldenrod;
            txtSearch.BorderColorDisabled = Color.FromArgb(204, 204, 204);
            txtSearch.BorderColorHover = Color.DarkGoldenrod;
            txtSearch.BorderColorIdle = Color.Silver;
            txtSearch.BorderRadius = 35;
            txtSearch.BorderThickness = 1;
            txtSearch.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            txtSearch.CharacterCasing = CharacterCasing.Normal;
            txtSearch.DefaultFont = new Font("Microsoft Sans Serif", 9F, FontStyle.Regular, GraphicsUnit.Point, 0);
            txtSearch.DefaultText = "";
            txtSearch.FillColor = Color.White;
            txtSearch.HideSelection = true;
            txtSearch.IconLeft = null;
            txtSearch.IconLeftCursor = Cursors.IBeam;
            txtSearch.IconPadding = 10;
            txtSearch.IconRight = null;
            txtSearch.IconRightCursor = Cursors.IBeam;
            txtSearch.Location = new Point(474, 80);
            txtSearch.MaxLength = 32767;
            txtSearch.MinimumSize = new Size(1, 1);
            txtSearch.Modified = false;
            txtSearch.Multiline = false;
            txtSearch.Name = "txtSearch";
            stateProperties1.BorderColor = Color.DarkGoldenrod;
            stateProperties1.FillColor = Color.Empty;
            stateProperties1.ForeColor = Color.Empty;
            stateProperties1.PlaceholderForeColor = Color.Empty;
            txtSearch.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = Color.FromArgb(204, 204, 204);
            stateProperties2.FillColor = Color.FromArgb(240, 240, 240);
            stateProperties2.ForeColor = Color.FromArgb(109, 109, 109);
            stateProperties2.PlaceholderForeColor = Color.DarkGray;
            txtSearch.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = Color.DarkGoldenrod;
            stateProperties3.FillColor = Color.Empty;
            stateProperties3.ForeColor = Color.Empty;
            stateProperties3.PlaceholderForeColor = Color.Empty;
            txtSearch.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = Color.Silver;
            stateProperties4.FillColor = Color.White;
            stateProperties4.ForeColor = Color.Empty;
            stateProperties4.PlaceholderForeColor = Color.Empty;
            txtSearch.OnIdleState = stateProperties4;
            txtSearch.Padding = new Padding(3);
            txtSearch.PasswordChar = '\0';
            txtSearch.PlaceholderForeColor = Color.Silver;
            txtSearch.PlaceholderText = "Search ...";
            txtSearch.ReadOnly = false;
            txtSearch.ScrollBars = ScrollBars.None;
            txtSearch.SelectedText = "";
            txtSearch.SelectionLength = 0;
            txtSearch.SelectionStart = 0;
            txtSearch.ShortcutsEnabled = true;
            txtSearch.Size = new Size(661, 44);
            txtSearch.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            txtSearch.TabIndex = 111;
            txtSearch.TextAlign = HorizontalAlignment.Left;
            txtSearch.TextMarginBottom = 0;
            txtSearch.TextMarginLeft = 3;
            txtSearch.TextMarginTop = 1;
            txtSearch.TextPlaceholder = "Search ...";
            txtSearch.UseSystemPasswordChar = false;
            txtSearch.WordWrap = true;
            // 
            // dgvInvoice
            // 
            dgvInvoice.AllowCustomTheming = false;
            dataGridViewCellStyle1.BackColor = Color.FromArgb(255, 232, 191);
            dataGridViewCellStyle1.Font = new Font("Microsoft Sans Serif", 8.25F, FontStyle.Bold, GraphicsUnit.Point, 0);
            dataGridViewCellStyle1.ForeColor = Color.Black;
            dgvInvoice.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle1;
            dgvInvoice.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
            dgvInvoice.BackgroundColor = Color.White;
            dgvInvoice.BorderStyle = BorderStyle.None;
            dgvInvoice.CellBorderStyle = DataGridViewCellBorderStyle.SingleHorizontal;
            dgvInvoice.ColumnHeadersBorderStyle = DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle2.Alignment = DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle2.BackColor = Color.Orange;
            dataGridViewCellStyle2.Font = new Font("Segoe UI Semibold", 11.75F, FontStyle.Bold);
            dataGridViewCellStyle2.ForeColor = Color.White;
            dataGridViewCellStyle2.SelectionBackColor = Color.FromArgb(204, 132, 0);
            dataGridViewCellStyle2.SelectionForeColor = Color.White;
            dataGridViewCellStyle2.WrapMode = DataGridViewTriState.True;
            dgvInvoice.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2;
            dgvInvoice.ColumnHeadersHeight = 40;
            dgvInvoice.CurrentTheme.AlternatingRowsStyle.BackColor = Color.FromArgb(255, 232, 191);
            dgvInvoice.CurrentTheme.AlternatingRowsStyle.Font = new Font("Segoe UI Semibold", 9.75F, FontStyle.Bold);
            dgvInvoice.CurrentTheme.AlternatingRowsStyle.ForeColor = Color.Black;
            dgvInvoice.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = Color.FromArgb(255, 201, 102);
            dgvInvoice.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = Color.Black;
            dgvInvoice.CurrentTheme.BackColor = Color.Orange;
            dgvInvoice.CurrentTheme.GridColor = Color.FromArgb(255, 226, 173);
            dgvInvoice.CurrentTheme.HeaderStyle.BackColor = Color.Orange;
            dgvInvoice.CurrentTheme.HeaderStyle.Font = new Font("Segoe UI Semibold", 11.75F, FontStyle.Bold);
            dgvInvoice.CurrentTheme.HeaderStyle.ForeColor = Color.White;
            dgvInvoice.CurrentTheme.HeaderStyle.SelectionBackColor = Color.FromArgb(204, 132, 0);
            dgvInvoice.CurrentTheme.HeaderStyle.SelectionForeColor = Color.White;
            dgvInvoice.CurrentTheme.Name = null;
            dgvInvoice.CurrentTheme.RowsStyle.BackColor = Color.FromArgb(255, 237, 204);
            dgvInvoice.CurrentTheme.RowsStyle.Font = new Font("Segoe UI Semibold", 9.75F, FontStyle.Bold);
            dgvInvoice.CurrentTheme.RowsStyle.ForeColor = Color.Black;
            dgvInvoice.CurrentTheme.RowsStyle.SelectionBackColor = Color.FromArgb(255, 201, 102);
            dgvInvoice.CurrentTheme.RowsStyle.SelectionForeColor = Color.Black;
            dataGridViewCellStyle3.Alignment = DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle3.BackColor = Color.FromArgb(255, 237, 204);
            dataGridViewCellStyle3.Font = new Font("Segoe UI Semibold", 9.75F, FontStyle.Bold);
            dataGridViewCellStyle3.ForeColor = Color.Black;
            dataGridViewCellStyle3.SelectionBackColor = Color.FromArgb(255, 201, 102);
            dataGridViewCellStyle3.SelectionForeColor = Color.Black;
            dataGridViewCellStyle3.WrapMode = DataGridViewTriState.False;
            dgvInvoice.DefaultCellStyle = dataGridViewCellStyle3;
            dgvInvoice.EnableHeadersVisualStyles = false;
            dgvInvoice.GridColor = Color.FromArgb(255, 226, 173);
            dgvInvoice.HeaderBackColor = Color.Orange;
            dgvInvoice.HeaderBgColor = Color.Empty;
            dgvInvoice.HeaderForeColor = Color.White;
            dgvInvoice.Location = new Point(474, 150);
            dgvInvoice.Name = "dgvInvoice";
            dgvInvoice.RowHeadersVisible = false;
            dgvInvoice.RowTemplate.Height = 40;
            dgvInvoice.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
            dgvInvoice.Size = new Size(665, 506);
            dgvInvoice.TabIndex = 112;
            dgvInvoice.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.Orange;
            // 
            // txtID
            // 
            txtID.AcceptsReturn = false;
            txtID.AcceptsTab = false;
            txtID.AnimationSpeed = 200;
            txtID.AutoCompleteMode = AutoCompleteMode.None;
            txtID.AutoCompleteSource = AutoCompleteSource.None;
            txtID.AutoSizeHeight = true;
            txtID.BackColor = Color.Transparent;
            txtID.BackgroundImage = (Image)resources.GetObject("txtID.BackgroundImage");
            txtID.BorderColorActive = Color.DarkGoldenrod;
            txtID.BorderColorDisabled = Color.FromArgb(204, 204, 204);
            txtID.BorderColorHover = Color.DarkGoldenrod;
            txtID.BorderColorIdle = Color.Silver;
            txtID.BorderRadius = 35;
            txtID.BorderThickness = 1;
            txtID.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            txtID.CharacterCasing = CharacterCasing.Normal;
            txtID.DefaultFont = new Font("Microsoft Sans Serif", 9F, FontStyle.Bold);
            txtID.DefaultText = "";
            txtID.Enabled = false;
            txtID.FillColor = Color.White;
            txtID.HideSelection = true;
            txtID.IconLeft = null;
            txtID.IconLeftCursor = Cursors.IBeam;
            txtID.IconPadding = 10;
            txtID.IconRight = null;
            txtID.IconRightCursor = Cursors.IBeam;
            txtID.Location = new Point(163, 150);
            txtID.MaxLength = 32767;
            txtID.MinimumSize = new Size(1, 1);
            txtID.Modified = false;
            txtID.Multiline = false;
            txtID.Name = "txtID";
            stateProperties5.BorderColor = Color.DarkGoldenrod;
            stateProperties5.FillColor = Color.Empty;
            stateProperties5.ForeColor = Color.Empty;
            stateProperties5.PlaceholderForeColor = Color.Empty;
            txtID.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = Color.FromArgb(204, 204, 204);
            stateProperties6.FillColor = Color.FromArgb(240, 240, 240);
            stateProperties6.ForeColor = Color.FromArgb(109, 109, 109);
            stateProperties6.PlaceholderForeColor = Color.DarkGray;
            txtID.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = Color.DarkGoldenrod;
            stateProperties7.FillColor = Color.Empty;
            stateProperties7.ForeColor = Color.Empty;
            stateProperties7.PlaceholderForeColor = Color.Empty;
            txtID.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = Color.Silver;
            stateProperties8.FillColor = Color.White;
            stateProperties8.ForeColor = Color.Empty;
            stateProperties8.PlaceholderForeColor = Color.Empty;
            txtID.OnIdleState = stateProperties8;
            txtID.Padding = new Padding(3);
            txtID.PasswordChar = '\0';
            txtID.PlaceholderForeColor = Color.Silver;
            txtID.PlaceholderText = "Enter text";
            txtID.ReadOnly = true;
            txtID.ScrollBars = ScrollBars.None;
            txtID.SelectedText = "";
            txtID.SelectionLength = 0;
            txtID.SelectionStart = 0;
            txtID.ShortcutsEnabled = true;
            txtID.Size = new Size(271, 44);
            txtID.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            txtID.TabIndex = 114;
            txtID.TextAlign = HorizontalAlignment.Left;
            txtID.TextMarginBottom = 0;
            txtID.TextMarginLeft = 3;
            txtID.TextMarginTop = 1;
            txtID.TextPlaceholder = "Enter text";
            txtID.UseSystemPasswordChar = false;
            txtID.WordWrap = true;
            // 
            // label1
            // 
            label1.AutoSize = true;
            label1.Font = new Font("Sitka Text", 14.2499981F);
            label1.Location = new Point(10, 150);
            label1.Name = "label1";
            label1.Size = new Size(32, 28);
            label1.TabIndex = 113;
            label1.Text = "ID";
            // 
            // txtOrderID
            // 
            txtOrderID.AcceptsReturn = false;
            txtOrderID.AcceptsTab = false;
            txtOrderID.AnimationSpeed = 200;
            txtOrderID.AutoCompleteMode = AutoCompleteMode.None;
            txtOrderID.AutoCompleteSource = AutoCompleteSource.None;
            txtOrderID.AutoSizeHeight = true;
            txtOrderID.BackColor = Color.Transparent;
            txtOrderID.BackgroundImage = (Image)resources.GetObject("txtOrderID.BackgroundImage");
            txtOrderID.BorderColorActive = Color.DarkGoldenrod;
            txtOrderID.BorderColorDisabled = Color.FromArgb(204, 204, 204);
            txtOrderID.BorderColorHover = Color.DarkGoldenrod;
            txtOrderID.BorderColorIdle = Color.Silver;
            txtOrderID.BorderRadius = 35;
            txtOrderID.BorderThickness = 1;
            txtOrderID.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            txtOrderID.CharacterCasing = CharacterCasing.Normal;
            txtOrderID.DefaultFont = new Font("Microsoft Sans Serif", 9F, FontStyle.Bold);
            txtOrderID.DefaultText = "";
            txtOrderID.Enabled = false;
            txtOrderID.FillColor = Color.White;
            txtOrderID.HideSelection = true;
            txtOrderID.IconLeft = null;
            txtOrderID.IconLeftCursor = Cursors.IBeam;
            txtOrderID.IconPadding = 10;
            txtOrderID.IconRight = null;
            txtOrderID.IconRightCursor = Cursors.IBeam;
            txtOrderID.Location = new Point(163, 200);
            txtOrderID.MaxLength = 32767;
            txtOrderID.MinimumSize = new Size(1, 1);
            txtOrderID.Modified = false;
            txtOrderID.Multiline = false;
            txtOrderID.Name = "txtOrderID";
            stateProperties9.BorderColor = Color.DarkGoldenrod;
            stateProperties9.FillColor = Color.Empty;
            stateProperties9.ForeColor = Color.Empty;
            stateProperties9.PlaceholderForeColor = Color.Empty;
            txtOrderID.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = Color.FromArgb(204, 204, 204);
            stateProperties10.FillColor = Color.FromArgb(240, 240, 240);
            stateProperties10.ForeColor = Color.FromArgb(109, 109, 109);
            stateProperties10.PlaceholderForeColor = Color.DarkGray;
            txtOrderID.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = Color.DarkGoldenrod;
            stateProperties11.FillColor = Color.Empty;
            stateProperties11.ForeColor = Color.Empty;
            stateProperties11.PlaceholderForeColor = Color.Empty;
            txtOrderID.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = Color.Silver;
            stateProperties12.FillColor = Color.White;
            stateProperties12.ForeColor = Color.Empty;
            stateProperties12.PlaceholderForeColor = Color.Empty;
            txtOrderID.OnIdleState = stateProperties12;
            txtOrderID.Padding = new Padding(3);
            txtOrderID.PasswordChar = '\0';
            txtOrderID.PlaceholderForeColor = Color.Silver;
            txtOrderID.PlaceholderText = "Enter text";
            txtOrderID.ReadOnly = true;
            txtOrderID.ScrollBars = ScrollBars.None;
            txtOrderID.SelectedText = "";
            txtOrderID.SelectionLength = 0;
            txtOrderID.SelectionStart = 0;
            txtOrderID.ShortcutsEnabled = true;
            txtOrderID.Size = new Size(271, 44);
            txtOrderID.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            txtOrderID.TabIndex = 116;
            txtOrderID.TextAlign = HorizontalAlignment.Left;
            txtOrderID.TextMarginBottom = 0;
            txtOrderID.TextMarginLeft = 3;
            txtOrderID.TextMarginTop = 1;
            txtOrderID.TextPlaceholder = "Enter text";
            txtOrderID.UseSystemPasswordChar = false;
            txtOrderID.WordWrap = true;
            // 
            // label2
            // 
            label2.AutoSize = true;
            label2.Font = new Font("Sitka Text", 14.2499981F);
            label2.Location = new Point(10, 200);
            label2.Name = "label2";
            label2.Size = new Size(89, 28);
            label2.TabIndex = 115;
            label2.Text = "Order ID";
            // 
            // txtInvoiceDate
            // 
            txtInvoiceDate.AcceptsReturn = false;
            txtInvoiceDate.AcceptsTab = false;
            txtInvoiceDate.AnimationSpeed = 200;
            txtInvoiceDate.AutoCompleteMode = AutoCompleteMode.None;
            txtInvoiceDate.AutoCompleteSource = AutoCompleteSource.None;
            txtInvoiceDate.AutoSizeHeight = true;
            txtInvoiceDate.BackColor = Color.Transparent;
            txtInvoiceDate.BackgroundImage = (Image)resources.GetObject("txtInvoiceDate.BackgroundImage");
            txtInvoiceDate.BorderColorActive = Color.DarkGoldenrod;
            txtInvoiceDate.BorderColorDisabled = Color.FromArgb(204, 204, 204);
            txtInvoiceDate.BorderColorHover = Color.DarkGoldenrod;
            txtInvoiceDate.BorderColorIdle = Color.Silver;
            txtInvoiceDate.BorderRadius = 35;
            txtInvoiceDate.BorderThickness = 1;
            txtInvoiceDate.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            txtInvoiceDate.CharacterCasing = CharacterCasing.Normal;
            txtInvoiceDate.DefaultFont = new Font("Microsoft Sans Serif", 9F, FontStyle.Bold);
            txtInvoiceDate.DefaultText = "";
            txtInvoiceDate.Enabled = false;
            txtInvoiceDate.FillColor = Color.White;
            txtInvoiceDate.HideSelection = true;
            txtInvoiceDate.IconLeft = null;
            txtInvoiceDate.IconLeftCursor = Cursors.IBeam;
            txtInvoiceDate.IconPadding = 10;
            txtInvoiceDate.IconRight = null;
            txtInvoiceDate.IconRightCursor = Cursors.IBeam;
            txtInvoiceDate.Location = new Point(163, 250);
            txtInvoiceDate.MaxLength = 32767;
            txtInvoiceDate.MinimumSize = new Size(1, 1);
            txtInvoiceDate.Modified = false;
            txtInvoiceDate.Multiline = false;
            txtInvoiceDate.Name = "txtInvoiceDate";
            stateProperties13.BorderColor = Color.DarkGoldenrod;
            stateProperties13.FillColor = Color.Empty;
            stateProperties13.ForeColor = Color.Empty;
            stateProperties13.PlaceholderForeColor = Color.Empty;
            txtInvoiceDate.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = Color.FromArgb(204, 204, 204);
            stateProperties14.FillColor = Color.FromArgb(240, 240, 240);
            stateProperties14.ForeColor = Color.FromArgb(109, 109, 109);
            stateProperties14.PlaceholderForeColor = Color.DarkGray;
            txtInvoiceDate.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = Color.DarkGoldenrod;
            stateProperties15.FillColor = Color.Empty;
            stateProperties15.ForeColor = Color.Empty;
            stateProperties15.PlaceholderForeColor = Color.Empty;
            txtInvoiceDate.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = Color.Silver;
            stateProperties16.FillColor = Color.White;
            stateProperties16.ForeColor = Color.Empty;
            stateProperties16.PlaceholderForeColor = Color.Empty;
            txtInvoiceDate.OnIdleState = stateProperties16;
            txtInvoiceDate.Padding = new Padding(3);
            txtInvoiceDate.PasswordChar = '\0';
            txtInvoiceDate.PlaceholderForeColor = Color.Silver;
            txtInvoiceDate.PlaceholderText = "Enter text";
            txtInvoiceDate.ReadOnly = true;
            txtInvoiceDate.ScrollBars = ScrollBars.None;
            txtInvoiceDate.SelectedText = "";
            txtInvoiceDate.SelectionLength = 0;
            txtInvoiceDate.SelectionStart = 0;
            txtInvoiceDate.ShortcutsEnabled = true;
            txtInvoiceDate.Size = new Size(271, 44);
            txtInvoiceDate.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            txtInvoiceDate.TabIndex = 118;
            txtInvoiceDate.TextAlign = HorizontalAlignment.Left;
            txtInvoiceDate.TextMarginBottom = 0;
            txtInvoiceDate.TextMarginLeft = 3;
            txtInvoiceDate.TextMarginTop = 1;
            txtInvoiceDate.TextPlaceholder = "Enter text";
            txtInvoiceDate.UseSystemPasswordChar = false;
            txtInvoiceDate.WordWrap = true;
            // 
            // label3
            // 
            label3.AutoSize = true;
            label3.Font = new Font("Sitka Text", 14.2499981F);
            label3.Location = new Point(10, 250);
            label3.Name = "label3";
            label3.Size = new Size(122, 28);
            label3.TabIndex = 117;
            label3.Text = "Invoice Date";
            // 
            // txtTotalAmount
            // 
            txtTotalAmount.AcceptsReturn = false;
            txtTotalAmount.AcceptsTab = false;
            txtTotalAmount.AnimationSpeed = 200;
            txtTotalAmount.AutoCompleteMode = AutoCompleteMode.None;
            txtTotalAmount.AutoCompleteSource = AutoCompleteSource.None;
            txtTotalAmount.AutoSizeHeight = true;
            txtTotalAmount.BackColor = Color.Transparent;
            txtTotalAmount.BackgroundImage = (Image)resources.GetObject("txtTotalAmount.BackgroundImage");
            txtTotalAmount.BorderColorActive = Color.DarkGoldenrod;
            txtTotalAmount.BorderColorDisabled = Color.FromArgb(204, 204, 204);
            txtTotalAmount.BorderColorHover = Color.DarkGoldenrod;
            txtTotalAmount.BorderColorIdle = Color.Silver;
            txtTotalAmount.BorderRadius = 35;
            txtTotalAmount.BorderThickness = 1;
            txtTotalAmount.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            txtTotalAmount.CharacterCasing = CharacterCasing.Normal;
            txtTotalAmount.DefaultFont = new Font("Microsoft Sans Serif", 9F, FontStyle.Bold);
            txtTotalAmount.DefaultText = "";
            txtTotalAmount.FillColor = Color.White;
            txtTotalAmount.HideSelection = true;
            txtTotalAmount.IconLeft = null;
            txtTotalAmount.IconLeftCursor = Cursors.IBeam;
            txtTotalAmount.IconPadding = 10;
            txtTotalAmount.IconRight = null;
            txtTotalAmount.IconRightCursor = Cursors.IBeam;
            txtTotalAmount.Location = new Point(163, 300);
            txtTotalAmount.MaxLength = 32767;
            txtTotalAmount.MinimumSize = new Size(1, 1);
            txtTotalAmount.Modified = false;
            txtTotalAmount.Multiline = false;
            txtTotalAmount.Name = "txtTotalAmount";
            stateProperties17.BorderColor = Color.DarkGoldenrod;
            stateProperties17.FillColor = Color.Empty;
            stateProperties17.ForeColor = Color.Empty;
            stateProperties17.PlaceholderForeColor = Color.Empty;
            txtTotalAmount.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = Color.FromArgb(204, 204, 204);
            stateProperties18.FillColor = Color.FromArgb(240, 240, 240);
            stateProperties18.ForeColor = Color.FromArgb(109, 109, 109);
            stateProperties18.PlaceholderForeColor = Color.DarkGray;
            txtTotalAmount.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = Color.DarkGoldenrod;
            stateProperties19.FillColor = Color.Empty;
            stateProperties19.ForeColor = Color.Empty;
            stateProperties19.PlaceholderForeColor = Color.Empty;
            txtTotalAmount.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = Color.Silver;
            stateProperties20.FillColor = Color.White;
            stateProperties20.ForeColor = Color.Empty;
            stateProperties20.PlaceholderForeColor = Color.Empty;
            txtTotalAmount.OnIdleState = stateProperties20;
            txtTotalAmount.Padding = new Padding(3);
            txtTotalAmount.PasswordChar = '\0';
            txtTotalAmount.PlaceholderForeColor = Color.Silver;
            txtTotalAmount.PlaceholderText = "Enter text";
            txtTotalAmount.ReadOnly = false;
            txtTotalAmount.ScrollBars = ScrollBars.None;
            txtTotalAmount.SelectedText = "";
            txtTotalAmount.SelectionLength = 0;
            txtTotalAmount.SelectionStart = 0;
            txtTotalAmount.ShortcutsEnabled = true;
            txtTotalAmount.Size = new Size(271, 44);
            txtTotalAmount.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            txtTotalAmount.TabIndex = 120;
            txtTotalAmount.TextAlign = HorizontalAlignment.Left;
            txtTotalAmount.TextMarginBottom = 0;
            txtTotalAmount.TextMarginLeft = 3;
            txtTotalAmount.TextMarginTop = 1;
            txtTotalAmount.TextPlaceholder = "Enter text";
            txtTotalAmount.UseSystemPasswordChar = false;
            txtTotalAmount.WordWrap = true;
            // 
            // label4
            // 
            label4.AutoSize = true;
            label4.Font = new Font("Sitka Text", 14.2499981F);
            label4.Location = new Point(10, 300);
            label4.Name = "label4";
            label4.Size = new Size(132, 28);
            label4.TabIndex = 119;
            label4.Text = "Total Amount";
            // 
            // txtNotes
            // 
            txtNotes.AcceptsReturn = false;
            txtNotes.AcceptsTab = false;
            txtNotes.AnimationSpeed = 200;
            txtNotes.AutoCompleteMode = AutoCompleteMode.None;
            txtNotes.AutoCompleteSource = AutoCompleteSource.None;
            txtNotes.AutoSizeHeight = true;
            txtNotes.BackColor = Color.Transparent;
            txtNotes.BackgroundImage = (Image)resources.GetObject("txtNotes.BackgroundImage");
            txtNotes.BorderColorActive = Color.DarkGoldenrod;
            txtNotes.BorderColorDisabled = Color.FromArgb(204, 204, 204);
            txtNotes.BorderColorHover = Color.DarkGoldenrod;
            txtNotes.BorderColorIdle = Color.Silver;
            txtNotes.BorderRadius = 35;
            txtNotes.BorderThickness = 1;
            txtNotes.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            txtNotes.CharacterCasing = CharacterCasing.Normal;
            txtNotes.DefaultFont = new Font("Microsoft Sans Serif", 9F, FontStyle.Bold);
            txtNotes.DefaultText = "";
            txtNotes.FillColor = Color.White;
            txtNotes.HideSelection = true;
            txtNotes.IconLeft = null;
            txtNotes.IconLeftCursor = Cursors.IBeam;
            txtNotes.IconPadding = 10;
            txtNotes.IconRight = null;
            txtNotes.IconRightCursor = Cursors.IBeam;
            txtNotes.Location = new Point(163, 350);
            txtNotes.MaxLength = 32767;
            txtNotes.MinimumSize = new Size(1, 1);
            txtNotes.Modified = false;
            txtNotes.Multiline = false;
            txtNotes.Name = "txtNotes";
            stateProperties21.BorderColor = Color.DarkGoldenrod;
            stateProperties21.FillColor = Color.Empty;
            stateProperties21.ForeColor = Color.Empty;
            stateProperties21.PlaceholderForeColor = Color.Empty;
            txtNotes.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = Color.FromArgb(204, 204, 204);
            stateProperties22.FillColor = Color.FromArgb(240, 240, 240);
            stateProperties22.ForeColor = Color.FromArgb(109, 109, 109);
            stateProperties22.PlaceholderForeColor = Color.DarkGray;
            txtNotes.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = Color.DarkGoldenrod;
            stateProperties23.FillColor = Color.Empty;
            stateProperties23.ForeColor = Color.Empty;
            stateProperties23.PlaceholderForeColor = Color.Empty;
            txtNotes.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = Color.Silver;
            stateProperties24.FillColor = Color.White;
            stateProperties24.ForeColor = Color.Empty;
            stateProperties24.PlaceholderForeColor = Color.Empty;
            txtNotes.OnIdleState = stateProperties24;
            txtNotes.Padding = new Padding(3);
            txtNotes.PasswordChar = '\0';
            txtNotes.PlaceholderForeColor = Color.Silver;
            txtNotes.PlaceholderText = "Enter text";
            txtNotes.ReadOnly = false;
            txtNotes.ScrollBars = ScrollBars.None;
            txtNotes.SelectedText = "";
            txtNotes.SelectionLength = 0;
            txtNotes.SelectionStart = 0;
            txtNotes.ShortcutsEnabled = true;
            txtNotes.Size = new Size(271, 44);
            txtNotes.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            txtNotes.TabIndex = 122;
            txtNotes.TextAlign = HorizontalAlignment.Left;
            txtNotes.TextMarginBottom = 0;
            txtNotes.TextMarginLeft = 3;
            txtNotes.TextMarginTop = 1;
            txtNotes.TextPlaceholder = "Enter text";
            txtNotes.UseSystemPasswordChar = false;
            txtNotes.WordWrap = true;
            // 
            // label5
            // 
            label5.AutoSize = true;
            label5.Font = new Font("Sitka Text", 14.2499981F);
            label5.Location = new Point(10, 350);
            label5.Name = "label5";
            label5.Size = new Size(64, 28);
            label5.TabIndex = 121;
            label5.Text = "Notes";
            // 
            // FormDock
            // 
            FormDock.AllowFormDragging = true;
            FormDock.AllowFormDropShadow = true;
            FormDock.AllowFormResizing = true;
            FormDock.AllowHidingBottomRegion = true;
            FormDock.AllowOpacityChangesWhileDragging = false;
            FormDock.BorderOptions.BottomBorder.BorderColor = Color.Silver;
            FormDock.BorderOptions.BottomBorder.BorderThickness = 1;
            FormDock.BorderOptions.BottomBorder.ShowBorder = true;
            FormDock.BorderOptions.LeftBorder.BorderColor = Color.Silver;
            FormDock.BorderOptions.LeftBorder.BorderThickness = 1;
            FormDock.BorderOptions.LeftBorder.ShowBorder = true;
            FormDock.BorderOptions.RightBorder.BorderColor = Color.Silver;
            FormDock.BorderOptions.RightBorder.BorderThickness = 1;
            FormDock.BorderOptions.RightBorder.ShowBorder = true;
            FormDock.BorderOptions.TopBorder.BorderColor = Color.Silver;
            FormDock.BorderOptions.TopBorder.BorderThickness = 1;
            FormDock.BorderOptions.TopBorder.ShowBorder = true;
            FormDock.ContainerControl = this;
            FormDock.DockingIndicatorsColor = Color.FromArgb(202, 215, 233);
            FormDock.DockingIndicatorsOpacity = 0.5D;
            FormDock.DockingOptions.DockAll = true;
            FormDock.DockingOptions.DockBottomLeft = true;
            FormDock.DockingOptions.DockBottomRight = true;
            FormDock.DockingOptions.DockFullScreen = true;
            FormDock.DockingOptions.DockLeft = true;
            FormDock.DockingOptions.DockRight = true;
            FormDock.DockingOptions.DockTopLeft = true;
            FormDock.DockingOptions.DockTopRight = true;
            FormDock.FormDraggingOpacity = 0.9D;
            FormDock.ParentForm = this;
            FormDock.ShowCursorChanges = true;
            FormDock.ShowDockingIndicators = true;
            FormDock.TitleBarOptions.AllowFormDragging = true;
            FormDock.TitleBarOptions.BunifuFormDock = FormDock;
            FormDock.TitleBarOptions.DoubleClickToExpandWindow = true;
            FormDock.TitleBarOptions.TitleBarControl = null;
            FormDock.TitleBarOptions.UseBackColorOnDockingIndicators = false;
            // 
            // Invoice
            // 
            AutoScaleDimensions = new SizeF(7F, 15F);
            AutoScaleMode = AutoScaleMode.Font;
            ClientSize = new Size(1149, 665);
            Controls.Add(txtNotes);
            Controls.Add(label5);
            Controls.Add(txtTotalAmount);
            Controls.Add(label4);
            Controls.Add(txtInvoiceDate);
            Controls.Add(label3);
            Controls.Add(txtOrderID);
            Controls.Add(label2);
            Controls.Add(txtID);
            Controls.Add(label1);
            Controls.Add(dgvInvoice);
            Controls.Add(txtSearch);
            Controls.Add(btnClear);
            Controls.Add(btnDelete);
            Controls.Add(btnUpdate);
            Controls.Add(btnInsert);
            Controls.Add(btnNew);
            Controls.Add(bunifuPanel2);
            FormBorderStyle = FormBorderStyle.None;
            Name = "Invoice";
            StartPosition = FormStartPosition.CenterScreen;
            Text = "Invoice Management";
            bunifuPanel2.ResumeLayout(false);
            bunifuPanel2.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)dgvInvoice).EndInit();
            ResumeLayout(false);
            PerformLayout();
        }

        #endregion
        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel2;
        private Label label11;
        private Bunifu.UI.WinForms.BunifuButton.BunifuIconButton btnExitProgram;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnClear;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnDelete;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnUpdate;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnInsert;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnNew;
        private Bunifu.UI.WinForms.BunifuTextBox txtSearch;
        private Bunifu.UI.WinForms.BunifuDataGridView dgvInvoice;
        private Bunifu.UI.WinForms.BunifuTextBox txtID;
        private Label label1;
        private Bunifu.UI.WinForms.BunifuTextBox txtOrderID;
        private Label label2;
        private Bunifu.UI.WinForms.BunifuTextBox txtInvoiceDate;
        private Label label3;
        private Bunifu.UI.WinForms.BunifuTextBox txtTotalAmount;
        private Label label4;
        private Bunifu.UI.WinForms.BunifuTextBox txtNotes;
        private Label label5;
        private Bunifu.UI.WinForms.BunifuFormDock FormDock;
    }
}