namespace Spa_Management_System
{
    partial class Order
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Order));
            Bunifu.UI.WinForms.BunifuButton.BunifuIconButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuIconButton.BorderEdges();
            DataGridViewCellStyle dataGridViewCellStyle1 = new DataGridViewCellStyle();
            DataGridViewCellStyle dataGridViewCellStyle2 = new DataGridViewCellStyle();
            DataGridViewCellStyle dataGridViewCellStyle3 = new DataGridViewCellStyle();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties25 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties26 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties27 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties28 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties29 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties30 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties31 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties32 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties33 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties34 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties35 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties36 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties37 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties38 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties39 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties40 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            bunifuPanel2 = new Bunifu.UI.WinForms.BunifuPanel();
            label11 = new Label();
            btnExitProgram = new Bunifu.UI.WinForms.BunifuButton.BunifuIconButton();
            dgvPayment = new Bunifu.UI.WinForms.BunifuDataGridView();
            txtSearch = new Bunifu.UI.WinForms.BunifuTextBox();
            btnClear = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            btnDelete = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            btnUpdate = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            btnInsert = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            btnNew = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            txtID = new Bunifu.UI.WinForms.BunifuTextBox();
            label1 = new Label();
            txtCustomerID = new Bunifu.UI.WinForms.BunifuTextBox();
            label2 = new Label();
            txtUserID = new Bunifu.UI.WinForms.BunifuTextBox();
            label4 = new Label();
            txtOrderTime = new Bunifu.UI.WinForms.BunifuTextBox();
            label3 = new Label();
            txtTotalAmount = new Bunifu.UI.WinForms.BunifuTextBox();
            label8 = new Label();
            txtDiscount = new Bunifu.UI.WinForms.BunifuTextBox();
            label5 = new Label();
            txtFinalAmount = new Bunifu.UI.WinForms.BunifuTextBox();
            label9 = new Label();
            txtNotes = new Bunifu.UI.WinForms.BunifuTextBox();
            label6 = new Label();
            txtStatus = new Bunifu.UI.WinForms.BunifuTextBox();
            label7 = new Label();
            bunifuPanel2.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)dgvPayment).BeginInit();
            SuspendLayout();
            // 
            // bunifuPanel2
            // 
            bunifuPanel2.BackgroundColor = Color.White;
            bunifuPanel2.BackgroundImage = (Image)resources.GetObject("bunifuPanel2.BackgroundImage");
            bunifuPanel2.BackgroundImageLayout = ImageLayout.Stretch;
            bunifuPanel2.BorderColor = Color.Transparent;
            bunifuPanel2.BorderRadius = 3;
            bunifuPanel2.BorderThickness = 1;
            bunifuPanel2.Controls.Add(label11);
            bunifuPanel2.Controls.Add(btnExitProgram);
            bunifuPanel2.Dock = DockStyle.Top;
            bunifuPanel2.Location = new Point(0, 0);
            bunifuPanel2.Name = "bunifuPanel2";
            bunifuPanel2.ShowBorders = true;
            bunifuPanel2.Size = new Size(1370, 65);
            bunifuPanel2.TabIndex = 89;
            // 
            // label11
            // 
            label11.AutoSize = true;
            label11.BackColor = Color.Transparent;
            label11.Font = new Font("Microsoft Sans Serif", 14.25F, FontStyle.Bold, GraphicsUnit.Point, 0);
            label11.Location = new Point(474, 15);
            label11.Name = "label11";
            label11.Size = new Size(191, 24);
            label11.TabIndex = 74;
            label11.Text = "Order Management";
            // 
            // btnExitProgram
            // 
            btnExitProgram.AllowAnimations = true;
            btnExitProgram.AllowBorderColorChanges = true;
            btnExitProgram.AllowMouseEffects = true;
            btnExitProgram.AnimationSpeed = 200;
            btnExitProgram.BackColor = Color.Transparent;
            btnExitProgram.BackgroundColor = Color.Transparent;
            btnExitProgram.BorderColor = Color.Transparent;
            btnExitProgram.BorderRadius = 1;
            btnExitProgram.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuIconButton.BorderStyles.Solid;
            btnExitProgram.BorderThickness = 1;
            btnExitProgram.ColorContrastOnClick = 30;
            btnExitProgram.ColorContrastOnHover = -30;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            btnExitProgram.CustomizableEdges = borderEdges1;
            btnExitProgram.DialogResult = DialogResult.None;
            btnExitProgram.Image = (Image)resources.GetObject("btnExitProgram.Image");
            btnExitProgram.ImageMargin = new Padding(0);
            btnExitProgram.Location = new Point(1237, 12);
            btnExitProgram.Name = "btnExitProgram";
            btnExitProgram.RoundBorders = true;
            btnExitProgram.ShowBorders = true;
            btnExitProgram.Size = new Size(26, 26);
            btnExitProgram.Style = Bunifu.UI.WinForms.BunifuButton.BunifuIconButton.ButtonStyles.Round;
            btnExitProgram.TabIndex = 69;
            btnExitProgram.Click += btnExitProgram_Click;
            // 
            // dgvPayment
            // 
            dgvPayment.AllowCustomTheming = false;
            dataGridViewCellStyle1.BackColor = Color.FromArgb(248, 251, 255);
            dataGridViewCellStyle1.Font = new Font("Microsoft Sans Serif", 8.25F, FontStyle.Bold, GraphicsUnit.Point, 0);
            dataGridViewCellStyle1.ForeColor = Color.Black;
            dgvPayment.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle1;
            dgvPayment.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
            dgvPayment.BackgroundColor = Color.White;
            dgvPayment.BorderStyle = BorderStyle.None;
            dgvPayment.CellBorderStyle = DataGridViewCellBorderStyle.SingleHorizontal;
            dgvPayment.ColumnHeadersBorderStyle = DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle2.Alignment = DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle2.BackColor = Color.DodgerBlue;
            dataGridViewCellStyle2.Font = new Font("Segoe UI Semibold", 11.75F, FontStyle.Bold);
            dataGridViewCellStyle2.ForeColor = Color.White;
            dataGridViewCellStyle2.SelectionBackColor = Color.FromArgb(24, 115, 204);
            dataGridViewCellStyle2.SelectionForeColor = Color.White;
            dataGridViewCellStyle2.WrapMode = DataGridViewTriState.True;
            dgvPayment.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2;
            dgvPayment.ColumnHeadersHeight = 40;
            dgvPayment.CurrentTheme.AlternatingRowsStyle.BackColor = Color.FromArgb(248, 251, 255);
            dgvPayment.CurrentTheme.AlternatingRowsStyle.Font = new Font("Segoe UI Semibold", 9.75F, FontStyle.Bold);
            dgvPayment.CurrentTheme.AlternatingRowsStyle.ForeColor = Color.Black;
            dgvPayment.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = Color.FromArgb(210, 232, 255);
            dgvPayment.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = Color.Black;
            dgvPayment.CurrentTheme.BackColor = Color.White;
            dgvPayment.CurrentTheme.GridColor = Color.FromArgb(221, 238, 255);
            dgvPayment.CurrentTheme.HeaderStyle.BackColor = Color.DodgerBlue;
            dgvPayment.CurrentTheme.HeaderStyle.Font = new Font("Segoe UI Semibold", 11.75F, FontStyle.Bold);
            dgvPayment.CurrentTheme.HeaderStyle.ForeColor = Color.White;
            dgvPayment.CurrentTheme.HeaderStyle.SelectionBackColor = Color.FromArgb(24, 115, 204);
            dgvPayment.CurrentTheme.HeaderStyle.SelectionForeColor = Color.White;
            dgvPayment.CurrentTheme.Name = null;
            dgvPayment.CurrentTheme.RowsStyle.BackColor = Color.White;
            dgvPayment.CurrentTheme.RowsStyle.Font = new Font("Segoe UI Semibold", 9.75F, FontStyle.Bold);
            dgvPayment.CurrentTheme.RowsStyle.ForeColor = Color.Black;
            dgvPayment.CurrentTheme.RowsStyle.SelectionBackColor = Color.FromArgb(210, 232, 255);
            dgvPayment.CurrentTheme.RowsStyle.SelectionForeColor = Color.Black;
            dataGridViewCellStyle3.Alignment = DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle3.BackColor = Color.White;
            dataGridViewCellStyle3.Font = new Font("Segoe UI Semibold", 9.75F, FontStyle.Bold);
            dataGridViewCellStyle3.ForeColor = Color.Black;
            dataGridViewCellStyle3.SelectionBackColor = Color.FromArgb(210, 232, 255);
            dataGridViewCellStyle3.SelectionForeColor = Color.Black;
            dataGridViewCellStyle3.WrapMode = DataGridViewTriState.False;
            dgvPayment.DefaultCellStyle = dataGridViewCellStyle3;
            dgvPayment.EnableHeadersVisualStyles = false;
            dgvPayment.GridColor = Color.FromArgb(221, 238, 255);
            dgvPayment.HeaderBackColor = Color.DodgerBlue;
            dgvPayment.HeaderBgColor = Color.Empty;
            dgvPayment.HeaderForeColor = Color.White;
            dgvPayment.Location = new Point(685, 210);
            dgvPayment.Name = "dgvPayment";
            dgvPayment.RowHeadersVisible = false;
            dgvPayment.RowTemplate.Height = 40;
            dgvPayment.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
            dgvPayment.Size = new Size(665, 506);
            dgvPayment.TabIndex = 99;
            dgvPayment.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.Light;
            // 
            // txtSearch
            // 
            txtSearch.AcceptsReturn = false;
            txtSearch.AcceptsTab = false;
            txtSearch.AnimationSpeed = 200;
            txtSearch.AutoCompleteMode = AutoCompleteMode.None;
            txtSearch.AutoCompleteSource = AutoCompleteSource.None;
            txtSearch.AutoSizeHeight = true;
            txtSearch.BackColor = Color.Transparent;
            txtSearch.BackgroundImage = (Image)resources.GetObject("txtSearch.BackgroundImage");
            txtSearch.BorderColorActive = Color.DarkGoldenrod;
            txtSearch.BorderColorDisabled = Color.FromArgb(204, 204, 204);
            txtSearch.BorderColorHover = Color.DarkGoldenrod;
            txtSearch.BorderColorIdle = Color.Silver;
            txtSearch.BorderRadius = 35;
            txtSearch.BorderThickness = 1;
            txtSearch.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            txtSearch.CharacterCasing = CharacterCasing.Normal;
            txtSearch.DefaultFont = new Font("Microsoft Sans Serif", 9F, FontStyle.Regular, GraphicsUnit.Point, 0);
            txtSearch.DefaultText = "";
            txtSearch.FillColor = Color.White;
            txtSearch.HideSelection = true;
            txtSearch.IconLeft = null;
            txtSearch.IconLeftCursor = Cursors.IBeam;
            txtSearch.IconPadding = 10;
            txtSearch.IconRight = null;
            txtSearch.IconRightCursor = Cursors.IBeam;
            txtSearch.Location = new Point(685, 140);
            txtSearch.MaxLength = 32767;
            txtSearch.MinimumSize = new Size(1, 1);
            txtSearch.Modified = false;
            txtSearch.Multiline = false;
            txtSearch.Name = "txtSearch";
            stateProperties1.BorderColor = Color.DarkGoldenrod;
            stateProperties1.FillColor = Color.Empty;
            stateProperties1.ForeColor = Color.Empty;
            stateProperties1.PlaceholderForeColor = Color.Empty;
            txtSearch.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = Color.FromArgb(204, 204, 204);
            stateProperties2.FillColor = Color.FromArgb(240, 240, 240);
            stateProperties2.ForeColor = Color.FromArgb(109, 109, 109);
            stateProperties2.PlaceholderForeColor = Color.DarkGray;
            txtSearch.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = Color.DarkGoldenrod;
            stateProperties3.FillColor = Color.Empty;
            stateProperties3.ForeColor = Color.Empty;
            stateProperties3.PlaceholderForeColor = Color.Empty;
            txtSearch.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = Color.Silver;
            stateProperties4.FillColor = Color.White;
            stateProperties4.ForeColor = Color.Empty;
            stateProperties4.PlaceholderForeColor = Color.Empty;
            txtSearch.OnIdleState = stateProperties4;
            txtSearch.Padding = new Padding(3);
            txtSearch.PasswordChar = '\0';
            txtSearch.PlaceholderForeColor = Color.Silver;
            txtSearch.PlaceholderText = "Search ...";
            txtSearch.ReadOnly = false;
            txtSearch.ScrollBars = ScrollBars.None;
            txtSearch.SelectedText = "";
            txtSearch.SelectionLength = 0;
            txtSearch.SelectionStart = 0;
            txtSearch.ShortcutsEnabled = true;
            txtSearch.Size = new Size(661, 44);
            txtSearch.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            txtSearch.TabIndex = 100;
            txtSearch.TextAlign = HorizontalAlignment.Left;
            txtSearch.TextMarginBottom = 0;
            txtSearch.TextMarginLeft = 3;
            txtSearch.TextMarginTop = 1;
            txtSearch.TextPlaceholder = "Search ...";
            txtSearch.UseSystemPasswordChar = false;
            txtSearch.WordWrap = true;
            // 
            // btnClear
            // 
            btnClear.AllowAnimations = true;
            btnClear.AllowMouseEffects = true;
            btnClear.AllowToggling = false;
            btnClear.AnimationSpeed = 200;
            btnClear.AutoGenerateColors = false;
            btnClear.AutoRoundBorders = false;
            btnClear.AutoSizeLeftIcon = true;
            btnClear.AutoSizeRightIcon = true;
            btnClear.BackColor = Color.Transparent;
            btnClear.BackColor1 = Color.White;
            btnClear.BackgroundImage = (Image)resources.GetObject("btnClear.BackgroundImage");
            btnClear.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnClear.ButtonText = "Clear";
            btnClear.ButtonTextMarginLeft = 0;
            btnClear.ColorContrastOnClick = 45;
            btnClear.ColorContrastOnHover = 45;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            btnClear.CustomizableEdges = borderEdges2;
            btnClear.DialogResult = DialogResult.None;
            btnClear.DisabledBorderColor = Color.FromArgb(191, 191, 191);
            btnClear.DisabledFillColor = Color.FromArgb(204, 204, 204);
            btnClear.DisabledForecolor = Color.FromArgb(168, 160, 168);
            btnClear.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            btnClear.Font = new Font("Microsoft Sans Serif", 9F, FontStyle.Bold, GraphicsUnit.Point, 0);
            btnClear.ForeColor = Color.Black;
            btnClear.IconLeftAlign = ContentAlignment.MiddleLeft;
            btnClear.IconLeftCursor = Cursors.Default;
            btnClear.IconLeftPadding = new Padding(11, 3, 3, 3);
            btnClear.IconMarginLeft = 11;
            btnClear.IconPadding = 10;
            btnClear.IconRightAlign = ContentAlignment.MiddleRight;
            btnClear.IconRightCursor = Cursors.Default;
            btnClear.IconRightPadding = new Padding(3, 3, 7, 3);
            btnClear.IconSize = 25;
            btnClear.IdleBorderColor = Color.White;
            btnClear.IdleBorderRadius = 35;
            btnClear.IdleBorderThickness = 1;
            btnClear.IdleFillColor = Color.White;
            btnClear.IdleIconLeftImage = null;
            btnClear.IdleIconRightImage = null;
            btnClear.IndicateFocus = false;
            btnClear.Location = new Point(437, 139);
            btnClear.Name = "btnClear";
            btnClear.OnDisabledState.BorderColor = Color.FromArgb(191, 191, 191);
            btnClear.OnDisabledState.BorderRadius = 35;
            btnClear.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnClear.OnDisabledState.BorderThickness = 1;
            btnClear.OnDisabledState.FillColor = Color.FromArgb(204, 204, 204);
            btnClear.OnDisabledState.ForeColor = Color.FromArgb(168, 160, 168);
            btnClear.OnDisabledState.IconLeftImage = null;
            btnClear.OnDisabledState.IconRightImage = null;
            btnClear.onHoverState.BorderColor = Color.DarkGoldenrod;
            btnClear.onHoverState.BorderRadius = 35;
            btnClear.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnClear.onHoverState.BorderThickness = 1;
            btnClear.onHoverState.FillColor = Color.White;
            btnClear.onHoverState.ForeColor = Color.Black;
            btnClear.onHoverState.IconLeftImage = null;
            btnClear.onHoverState.IconRightImage = null;
            btnClear.OnIdleState.BorderColor = Color.White;
            btnClear.OnIdleState.BorderRadius = 35;
            btnClear.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnClear.OnIdleState.BorderThickness = 1;
            btnClear.OnIdleState.FillColor = Color.White;
            btnClear.OnIdleState.ForeColor = Color.Black;
            btnClear.OnIdleState.IconLeftImage = null;
            btnClear.OnIdleState.IconRightImage = null;
            btnClear.OnPressedState.BorderColor = Color.FromArgb(40, 96, 144);
            btnClear.OnPressedState.BorderRadius = 35;
            btnClear.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnClear.OnPressedState.BorderThickness = 1;
            btnClear.OnPressedState.FillColor = Color.FromArgb(40, 96, 144);
            btnClear.OnPressedState.ForeColor = Color.White;
            btnClear.OnPressedState.IconLeftImage = null;
            btnClear.OnPressedState.IconRightImage = null;
            btnClear.Size = new Size(80, 39);
            btnClear.TabIndex = 105;
            btnClear.TextAlign = ContentAlignment.MiddleCenter;
            btnClear.TextAlignment = HorizontalAlignment.Center;
            btnClear.TextMarginLeft = 0;
            btnClear.TextPadding = new Padding(0);
            btnClear.UseDefaultRadiusAndThickness = true;
            // 
            // btnDelete
            // 
            btnDelete.AllowAnimations = true;
            btnDelete.AllowMouseEffects = true;
            btnDelete.AllowToggling = false;
            btnDelete.AnimationSpeed = 200;
            btnDelete.AutoGenerateColors = false;
            btnDelete.AutoRoundBorders = false;
            btnDelete.AutoSizeLeftIcon = true;
            btnDelete.AutoSizeRightIcon = true;
            btnDelete.BackColor = Color.Transparent;
            btnDelete.BackColor1 = Color.White;
            btnDelete.BackgroundImage = (Image)resources.GetObject("btnDelete.BackgroundImage");
            btnDelete.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnDelete.ButtonText = "Delete";
            btnDelete.ButtonTextMarginLeft = 0;
            btnDelete.ColorContrastOnClick = 45;
            btnDelete.ColorContrastOnHover = 45;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            btnDelete.CustomizableEdges = borderEdges3;
            btnDelete.DialogResult = DialogResult.None;
            btnDelete.DisabledBorderColor = Color.FromArgb(191, 191, 191);
            btnDelete.DisabledFillColor = Color.FromArgb(204, 204, 204);
            btnDelete.DisabledForecolor = Color.FromArgb(168, 160, 168);
            btnDelete.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            btnDelete.Font = new Font("Microsoft Sans Serif", 9F, FontStyle.Bold, GraphicsUnit.Point, 0);
            btnDelete.ForeColor = Color.Black;
            btnDelete.IconLeftAlign = ContentAlignment.MiddleLeft;
            btnDelete.IconLeftCursor = Cursors.Default;
            btnDelete.IconLeftPadding = new Padding(11, 3, 3, 3);
            btnDelete.IconMarginLeft = 11;
            btnDelete.IconPadding = 10;
            btnDelete.IconRightAlign = ContentAlignment.MiddleRight;
            btnDelete.IconRightCursor = Cursors.Default;
            btnDelete.IconRightPadding = new Padding(3, 3, 7, 3);
            btnDelete.IconSize = 25;
            btnDelete.IdleBorderColor = Color.White;
            btnDelete.IdleBorderRadius = 35;
            btnDelete.IdleBorderThickness = 1;
            btnDelete.IdleFillColor = Color.White;
            btnDelete.IdleIconLeftImage = null;
            btnDelete.IdleIconRightImage = null;
            btnDelete.IndicateFocus = false;
            btnDelete.Location = new Point(351, 139);
            btnDelete.Name = "btnDelete";
            btnDelete.OnDisabledState.BorderColor = Color.FromArgb(191, 191, 191);
            btnDelete.OnDisabledState.BorderRadius = 35;
            btnDelete.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnDelete.OnDisabledState.BorderThickness = 1;
            btnDelete.OnDisabledState.FillColor = Color.FromArgb(204, 204, 204);
            btnDelete.OnDisabledState.ForeColor = Color.FromArgb(168, 160, 168);
            btnDelete.OnDisabledState.IconLeftImage = null;
            btnDelete.OnDisabledState.IconRightImage = null;
            btnDelete.onHoverState.BorderColor = Color.DarkGoldenrod;
            btnDelete.onHoverState.BorderRadius = 35;
            btnDelete.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnDelete.onHoverState.BorderThickness = 1;
            btnDelete.onHoverState.FillColor = Color.White;
            btnDelete.onHoverState.ForeColor = Color.Black;
            btnDelete.onHoverState.IconLeftImage = null;
            btnDelete.onHoverState.IconRightImage = null;
            btnDelete.OnIdleState.BorderColor = Color.White;
            btnDelete.OnIdleState.BorderRadius = 35;
            btnDelete.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnDelete.OnIdleState.BorderThickness = 1;
            btnDelete.OnIdleState.FillColor = Color.White;
            btnDelete.OnIdleState.ForeColor = Color.Black;
            btnDelete.OnIdleState.IconLeftImage = null;
            btnDelete.OnIdleState.IconRightImage = null;
            btnDelete.OnPressedState.BorderColor = Color.FromArgb(40, 96, 144);
            btnDelete.OnPressedState.BorderRadius = 35;
            btnDelete.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnDelete.OnPressedState.BorderThickness = 1;
            btnDelete.OnPressedState.FillColor = Color.FromArgb(40, 96, 144);
            btnDelete.OnPressedState.ForeColor = Color.White;
            btnDelete.OnPressedState.IconLeftImage = null;
            btnDelete.OnPressedState.IconRightImage = null;
            btnDelete.Size = new Size(80, 39);
            btnDelete.TabIndex = 104;
            btnDelete.TextAlign = ContentAlignment.MiddleCenter;
            btnDelete.TextAlignment = HorizontalAlignment.Center;
            btnDelete.TextMarginLeft = 0;
            btnDelete.TextPadding = new Padding(0);
            btnDelete.UseDefaultRadiusAndThickness = true;
            // 
            // btnUpdate
            // 
            btnUpdate.AllowAnimations = true;
            btnUpdate.AllowMouseEffects = true;
            btnUpdate.AllowToggling = false;
            btnUpdate.AnimationSpeed = 200;
            btnUpdate.AutoGenerateColors = false;
            btnUpdate.AutoRoundBorders = false;
            btnUpdate.AutoSizeLeftIcon = true;
            btnUpdate.AutoSizeRightIcon = true;
            btnUpdate.BackColor = Color.Transparent;
            btnUpdate.BackColor1 = Color.White;
            btnUpdate.BackgroundImage = (Image)resources.GetObject("btnUpdate.BackgroundImage");
            btnUpdate.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnUpdate.ButtonText = "Update";
            btnUpdate.ButtonTextMarginLeft = 0;
            btnUpdate.ColorContrastOnClick = 45;
            btnUpdate.ColorContrastOnHover = 45;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            btnUpdate.CustomizableEdges = borderEdges4;
            btnUpdate.DialogResult = DialogResult.None;
            btnUpdate.DisabledBorderColor = Color.FromArgb(191, 191, 191);
            btnUpdate.DisabledFillColor = Color.FromArgb(204, 204, 204);
            btnUpdate.DisabledForecolor = Color.FromArgb(168, 160, 168);
            btnUpdate.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            btnUpdate.Font = new Font("Microsoft Sans Serif", 9F, FontStyle.Bold, GraphicsUnit.Point, 0);
            btnUpdate.ForeColor = Color.Black;
            btnUpdate.IconLeftAlign = ContentAlignment.MiddleLeft;
            btnUpdate.IconLeftCursor = Cursors.Default;
            btnUpdate.IconLeftPadding = new Padding(11, 3, 3, 3);
            btnUpdate.IconMarginLeft = 11;
            btnUpdate.IconPadding = 10;
            btnUpdate.IconRightAlign = ContentAlignment.MiddleRight;
            btnUpdate.IconRightCursor = Cursors.Default;
            btnUpdate.IconRightPadding = new Padding(3, 3, 7, 3);
            btnUpdate.IconSize = 25;
            btnUpdate.IdleBorderColor = Color.White;
            btnUpdate.IdleBorderRadius = 35;
            btnUpdate.IdleBorderThickness = 1;
            btnUpdate.IdleFillColor = Color.White;
            btnUpdate.IdleIconLeftImage = null;
            btnUpdate.IdleIconRightImage = null;
            btnUpdate.IndicateFocus = false;
            btnUpdate.Location = new Point(265, 139);
            btnUpdate.Name = "btnUpdate";
            btnUpdate.OnDisabledState.BorderColor = Color.FromArgb(191, 191, 191);
            btnUpdate.OnDisabledState.BorderRadius = 35;
            btnUpdate.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnUpdate.OnDisabledState.BorderThickness = 1;
            btnUpdate.OnDisabledState.FillColor = Color.FromArgb(204, 204, 204);
            btnUpdate.OnDisabledState.ForeColor = Color.FromArgb(168, 160, 168);
            btnUpdate.OnDisabledState.IconLeftImage = null;
            btnUpdate.OnDisabledState.IconRightImage = null;
            btnUpdate.onHoverState.BorderColor = Color.DarkGoldenrod;
            btnUpdate.onHoverState.BorderRadius = 35;
            btnUpdate.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnUpdate.onHoverState.BorderThickness = 1;
            btnUpdate.onHoverState.FillColor = Color.White;
            btnUpdate.onHoverState.ForeColor = Color.Black;
            btnUpdate.onHoverState.IconLeftImage = null;
            btnUpdate.onHoverState.IconRightImage = null;
            btnUpdate.OnIdleState.BorderColor = Color.White;
            btnUpdate.OnIdleState.BorderRadius = 35;
            btnUpdate.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnUpdate.OnIdleState.BorderThickness = 1;
            btnUpdate.OnIdleState.FillColor = Color.White;
            btnUpdate.OnIdleState.ForeColor = Color.Black;
            btnUpdate.OnIdleState.IconLeftImage = null;
            btnUpdate.OnIdleState.IconRightImage = null;
            btnUpdate.OnPressedState.BorderColor = Color.FromArgb(40, 96, 144);
            btnUpdate.OnPressedState.BorderRadius = 35;
            btnUpdate.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnUpdate.OnPressedState.BorderThickness = 1;
            btnUpdate.OnPressedState.FillColor = Color.FromArgb(40, 96, 144);
            btnUpdate.OnPressedState.ForeColor = Color.White;
            btnUpdate.OnPressedState.IconLeftImage = null;
            btnUpdate.OnPressedState.IconRightImage = null;
            btnUpdate.Size = new Size(80, 39);
            btnUpdate.TabIndex = 103;
            btnUpdate.TextAlign = ContentAlignment.MiddleCenter;
            btnUpdate.TextAlignment = HorizontalAlignment.Center;
            btnUpdate.TextMarginLeft = 0;
            btnUpdate.TextPadding = new Padding(0);
            btnUpdate.UseDefaultRadiusAndThickness = true;
            // 
            // btnInsert
            // 
            btnInsert.AllowAnimations = true;
            btnInsert.AllowMouseEffects = true;
            btnInsert.AllowToggling = false;
            btnInsert.AnimationSpeed = 200;
            btnInsert.AutoGenerateColors = false;
            btnInsert.AutoRoundBorders = false;
            btnInsert.AutoSizeLeftIcon = true;
            btnInsert.AutoSizeRightIcon = true;
            btnInsert.BackColor = Color.Transparent;
            btnInsert.BackColor1 = Color.White;
            btnInsert.BackgroundImage = (Image)resources.GetObject("btnInsert.BackgroundImage");
            btnInsert.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnInsert.ButtonText = "Insert";
            btnInsert.ButtonTextMarginLeft = 0;
            btnInsert.ColorContrastOnClick = 45;
            btnInsert.ColorContrastOnHover = 45;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            btnInsert.CustomizableEdges = borderEdges5;
            btnInsert.DialogResult = DialogResult.None;
            btnInsert.DisabledBorderColor = Color.FromArgb(191, 191, 191);
            btnInsert.DisabledFillColor = Color.FromArgb(204, 204, 204);
            btnInsert.DisabledForecolor = Color.FromArgb(168, 160, 168);
            btnInsert.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            btnInsert.Font = new Font("Microsoft Sans Serif", 9F, FontStyle.Bold, GraphicsUnit.Point, 0);
            btnInsert.ForeColor = Color.Black;
            btnInsert.IconLeftAlign = ContentAlignment.MiddleLeft;
            btnInsert.IconLeftCursor = Cursors.Default;
            btnInsert.IconLeftPadding = new Padding(11, 3, 3, 3);
            btnInsert.IconMarginLeft = 11;
            btnInsert.IconPadding = 10;
            btnInsert.IconRightAlign = ContentAlignment.MiddleRight;
            btnInsert.IconRightCursor = Cursors.Default;
            btnInsert.IconRightPadding = new Padding(3, 3, 7, 3);
            btnInsert.IconSize = 25;
            btnInsert.IdleBorderColor = Color.White;
            btnInsert.IdleBorderRadius = 35;
            btnInsert.IdleBorderThickness = 1;
            btnInsert.IdleFillColor = Color.White;
            btnInsert.IdleIconLeftImage = null;
            btnInsert.IdleIconRightImage = null;
            btnInsert.IndicateFocus = false;
            btnInsert.Location = new Point(179, 139);
            btnInsert.Name = "btnInsert";
            btnInsert.OnDisabledState.BorderColor = Color.FromArgb(191, 191, 191);
            btnInsert.OnDisabledState.BorderRadius = 35;
            btnInsert.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnInsert.OnDisabledState.BorderThickness = 1;
            btnInsert.OnDisabledState.FillColor = Color.FromArgb(204, 204, 204);
            btnInsert.OnDisabledState.ForeColor = Color.FromArgb(168, 160, 168);
            btnInsert.OnDisabledState.IconLeftImage = null;
            btnInsert.OnDisabledState.IconRightImage = null;
            btnInsert.onHoverState.BorderColor = Color.DarkGoldenrod;
            btnInsert.onHoverState.BorderRadius = 35;
            btnInsert.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnInsert.onHoverState.BorderThickness = 1;
            btnInsert.onHoverState.FillColor = Color.White;
            btnInsert.onHoverState.ForeColor = Color.Black;
            btnInsert.onHoverState.IconLeftImage = null;
            btnInsert.onHoverState.IconRightImage = null;
            btnInsert.OnIdleState.BorderColor = Color.White;
            btnInsert.OnIdleState.BorderRadius = 35;
            btnInsert.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnInsert.OnIdleState.BorderThickness = 1;
            btnInsert.OnIdleState.FillColor = Color.White;
            btnInsert.OnIdleState.ForeColor = Color.Black;
            btnInsert.OnIdleState.IconLeftImage = null;
            btnInsert.OnIdleState.IconRightImage = null;
            btnInsert.OnPressedState.BorderColor = Color.FromArgb(40, 96, 144);
            btnInsert.OnPressedState.BorderRadius = 35;
            btnInsert.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnInsert.OnPressedState.BorderThickness = 1;
            btnInsert.OnPressedState.FillColor = Color.FromArgb(40, 96, 144);
            btnInsert.OnPressedState.ForeColor = Color.White;
            btnInsert.OnPressedState.IconLeftImage = null;
            btnInsert.OnPressedState.IconRightImage = null;
            btnInsert.Size = new Size(80, 39);
            btnInsert.TabIndex = 102;
            btnInsert.TextAlign = ContentAlignment.MiddleCenter;
            btnInsert.TextAlignment = HorizontalAlignment.Center;
            btnInsert.TextMarginLeft = 0;
            btnInsert.TextPadding = new Padding(0);
            btnInsert.UseDefaultRadiusAndThickness = true;
            // 
            // btnNew
            // 
            btnNew.AllowAnimations = true;
            btnNew.AllowMouseEffects = true;
            btnNew.AllowToggling = false;
            btnNew.AnimationSpeed = 200;
            btnNew.AutoGenerateColors = false;
            btnNew.AutoRoundBorders = false;
            btnNew.AutoSizeLeftIcon = true;
            btnNew.AutoSizeRightIcon = true;
            btnNew.BackColor = Color.Transparent;
            btnNew.BackColor1 = Color.White;
            btnNew.BackgroundImage = (Image)resources.GetObject("btnNew.BackgroundImage");
            btnNew.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnNew.ButtonText = "New";
            btnNew.ButtonTextMarginLeft = 0;
            btnNew.ColorContrastOnClick = 45;
            btnNew.ColorContrastOnHover = 45;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            btnNew.CustomizableEdges = borderEdges6;
            btnNew.DialogResult = DialogResult.None;
            btnNew.DisabledBorderColor = Color.FromArgb(191, 191, 191);
            btnNew.DisabledFillColor = Color.FromArgb(204, 204, 204);
            btnNew.DisabledForecolor = Color.FromArgb(168, 160, 168);
            btnNew.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            btnNew.Font = new Font("Microsoft Sans Serif", 9F, FontStyle.Bold, GraphicsUnit.Point, 0);
            btnNew.ForeColor = Color.Black;
            btnNew.IconLeftAlign = ContentAlignment.MiddleLeft;
            btnNew.IconLeftCursor = Cursors.Default;
            btnNew.IconLeftPadding = new Padding(11, 3, 3, 3);
            btnNew.IconMarginLeft = 11;
            btnNew.IconPadding = 10;
            btnNew.IconRightAlign = ContentAlignment.MiddleRight;
            btnNew.IconRightCursor = Cursors.Default;
            btnNew.IconRightPadding = new Padding(3, 3, 7, 3);
            btnNew.IconSize = 25;
            btnNew.IdleBorderColor = Color.White;
            btnNew.IdleBorderRadius = 35;
            btnNew.IdleBorderThickness = 1;
            btnNew.IdleFillColor = Color.White;
            btnNew.IdleIconLeftImage = null;
            btnNew.IdleIconRightImage = null;
            btnNew.IndicateFocus = false;
            btnNew.Location = new Point(93, 139);
            btnNew.Name = "btnNew";
            btnNew.OnDisabledState.BorderColor = Color.FromArgb(191, 191, 191);
            btnNew.OnDisabledState.BorderRadius = 35;
            btnNew.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnNew.OnDisabledState.BorderThickness = 1;
            btnNew.OnDisabledState.FillColor = Color.FromArgb(204, 204, 204);
            btnNew.OnDisabledState.ForeColor = Color.FromArgb(168, 160, 168);
            btnNew.OnDisabledState.IconLeftImage = null;
            btnNew.OnDisabledState.IconRightImage = null;
            btnNew.onHoverState.BorderColor = Color.DarkGoldenrod;
            btnNew.onHoverState.BorderRadius = 35;
            btnNew.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnNew.onHoverState.BorderThickness = 1;
            btnNew.onHoverState.FillColor = Color.White;
            btnNew.onHoverState.ForeColor = Color.Black;
            btnNew.onHoverState.IconLeftImage = null;
            btnNew.onHoverState.IconRightImage = null;
            btnNew.OnIdleState.BorderColor = Color.White;
            btnNew.OnIdleState.BorderRadius = 35;
            btnNew.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnNew.OnIdleState.BorderThickness = 1;
            btnNew.OnIdleState.FillColor = Color.White;
            btnNew.OnIdleState.ForeColor = Color.Black;
            btnNew.OnIdleState.IconLeftImage = null;
            btnNew.OnIdleState.IconRightImage = null;
            btnNew.OnPressedState.BorderColor = Color.FromArgb(40, 96, 144);
            btnNew.OnPressedState.BorderRadius = 35;
            btnNew.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            btnNew.OnPressedState.BorderThickness = 1;
            btnNew.OnPressedState.FillColor = Color.FromArgb(40, 96, 144);
            btnNew.OnPressedState.ForeColor = Color.White;
            btnNew.OnPressedState.IconLeftImage = null;
            btnNew.OnPressedState.IconRightImage = null;
            btnNew.Size = new Size(80, 39);
            btnNew.TabIndex = 101;
            btnNew.TextAlign = ContentAlignment.MiddleCenter;
            btnNew.TextAlignment = HorizontalAlignment.Center;
            btnNew.TextMarginLeft = 0;
            btnNew.TextPadding = new Padding(0);
            btnNew.UseDefaultRadiusAndThickness = true;
            // 
            // txtID
            // 
            txtID.AcceptsReturn = false;
            txtID.AcceptsTab = false;
            txtID.AnimationSpeed = 200;
            txtID.AutoCompleteMode = AutoCompleteMode.None;
            txtID.AutoCompleteSource = AutoCompleteSource.None;
            txtID.AutoSizeHeight = true;
            txtID.BackColor = Color.Transparent;
            txtID.BackgroundImage = (Image)resources.GetObject("txtID.BackgroundImage");
            txtID.BorderColorActive = Color.DarkGoldenrod;
            txtID.BorderColorDisabled = Color.FromArgb(204, 204, 204);
            txtID.BorderColorHover = Color.DarkGoldenrod;
            txtID.BorderColorIdle = Color.Silver;
            txtID.BorderRadius = 35;
            txtID.BorderThickness = 1;
            txtID.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            txtID.CharacterCasing = CharacterCasing.Normal;
            txtID.DefaultFont = new Font("Microsoft Sans Serif", 9F, FontStyle.Bold);
            txtID.DefaultText = "";
            txtID.Enabled = false;
            txtID.FillColor = Color.White;
            txtID.HideSelection = true;
            txtID.IconLeft = null;
            txtID.IconLeftCursor = Cursors.IBeam;
            txtID.IconPadding = 10;
            txtID.IconRight = null;
            txtID.IconRightCursor = Cursors.IBeam;
            txtID.Location = new Point(265, 213);
            txtID.MaxLength = 32767;
            txtID.MinimumSize = new Size(1, 1);
            txtID.Modified = false;
            txtID.Multiline = false;
            txtID.Name = "txtID";
            stateProperties5.BorderColor = Color.DarkGoldenrod;
            stateProperties5.FillColor = Color.Empty;
            stateProperties5.ForeColor = Color.Empty;
            stateProperties5.PlaceholderForeColor = Color.Empty;
            txtID.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = Color.FromArgb(204, 204, 204);
            stateProperties6.FillColor = Color.FromArgb(240, 240, 240);
            stateProperties6.ForeColor = Color.FromArgb(109, 109, 109);
            stateProperties6.PlaceholderForeColor = Color.DarkGray;
            txtID.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = Color.DarkGoldenrod;
            stateProperties7.FillColor = Color.Empty;
            stateProperties7.ForeColor = Color.Empty;
            stateProperties7.PlaceholderForeColor = Color.Empty;
            txtID.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = Color.Silver;
            stateProperties8.FillColor = Color.White;
            stateProperties8.ForeColor = Color.Empty;
            stateProperties8.PlaceholderForeColor = Color.Empty;
            txtID.OnIdleState = stateProperties8;
            txtID.Padding = new Padding(3);
            txtID.PasswordChar = '\0';
            txtID.PlaceholderForeColor = Color.Silver;
            txtID.PlaceholderText = "Enter text";
            txtID.ReadOnly = true;
            txtID.ScrollBars = ScrollBars.None;
            txtID.SelectedText = "";
            txtID.SelectionLength = 0;
            txtID.SelectionStart = 0;
            txtID.ShortcutsEnabled = true;
            txtID.Size = new Size(271, 44);
            txtID.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            txtID.TabIndex = 107;
            txtID.TextAlign = HorizontalAlignment.Left;
            txtID.TextMarginBottom = 0;
            txtID.TextMarginLeft = 3;
            txtID.TextMarginTop = 1;
            txtID.TextPlaceholder = "Enter text";
            txtID.UseSystemPasswordChar = false;
            txtID.WordWrap = true;
            // 
            // label1
            // 
            label1.AutoSize = true;
            label1.Font = new Font("Microsoft Sans Serif", 14.25F, FontStyle.Bold);
            label1.Location = new Point(93, 213);
            label1.Name = "label1";
            label1.Size = new Size(29, 24);
            label1.TabIndex = 106;
            label1.Text = "ID";
            // 
            // txtCustomerID
            // 
            txtCustomerID.AcceptsReturn = false;
            txtCustomerID.AcceptsTab = false;
            txtCustomerID.AnimationSpeed = 200;
            txtCustomerID.AutoCompleteMode = AutoCompleteMode.None;
            txtCustomerID.AutoCompleteSource = AutoCompleteSource.None;
            txtCustomerID.AutoSizeHeight = true;
            txtCustomerID.BackColor = Color.Transparent;
            txtCustomerID.BackgroundImage = (Image)resources.GetObject("txtCustomerID.BackgroundImage");
            txtCustomerID.BorderColorActive = Color.DarkGoldenrod;
            txtCustomerID.BorderColorDisabled = Color.FromArgb(204, 204, 204);
            txtCustomerID.BorderColorHover = Color.DarkGoldenrod;
            txtCustomerID.BorderColorIdle = Color.Silver;
            txtCustomerID.BorderRadius = 35;
            txtCustomerID.BorderThickness = 1;
            txtCustomerID.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            txtCustomerID.CharacterCasing = CharacterCasing.Normal;
            txtCustomerID.DefaultFont = new Font("Microsoft Sans Serif", 9F, FontStyle.Bold);
            txtCustomerID.DefaultText = "";
            txtCustomerID.Enabled = false;
            txtCustomerID.FillColor = Color.White;
            txtCustomerID.HideSelection = true;
            txtCustomerID.IconLeft = null;
            txtCustomerID.IconLeftCursor = Cursors.IBeam;
            txtCustomerID.IconPadding = 10;
            txtCustomerID.IconRight = null;
            txtCustomerID.IconRightCursor = Cursors.IBeam;
            txtCustomerID.Location = new Point(265, 263);
            txtCustomerID.MaxLength = 32767;
            txtCustomerID.MinimumSize = new Size(1, 1);
            txtCustomerID.Modified = false;
            txtCustomerID.Multiline = false;
            txtCustomerID.Name = "txtCustomerID";
            stateProperties9.BorderColor = Color.DarkGoldenrod;
            stateProperties9.FillColor = Color.Empty;
            stateProperties9.ForeColor = Color.Empty;
            stateProperties9.PlaceholderForeColor = Color.Empty;
            txtCustomerID.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = Color.FromArgb(204, 204, 204);
            stateProperties10.FillColor = Color.FromArgb(240, 240, 240);
            stateProperties10.ForeColor = Color.FromArgb(109, 109, 109);
            stateProperties10.PlaceholderForeColor = Color.DarkGray;
            txtCustomerID.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = Color.DarkGoldenrod;
            stateProperties11.FillColor = Color.Empty;
            stateProperties11.ForeColor = Color.Empty;
            stateProperties11.PlaceholderForeColor = Color.Empty;
            txtCustomerID.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = Color.Silver;
            stateProperties12.FillColor = Color.White;
            stateProperties12.ForeColor = Color.Empty;
            stateProperties12.PlaceholderForeColor = Color.Empty;
            txtCustomerID.OnIdleState = stateProperties12;
            txtCustomerID.Padding = new Padding(3);
            txtCustomerID.PasswordChar = '\0';
            txtCustomerID.PlaceholderForeColor = Color.Silver;
            txtCustomerID.PlaceholderText = "Enter text";
            txtCustomerID.ReadOnly = false;
            txtCustomerID.ScrollBars = ScrollBars.None;
            txtCustomerID.SelectedText = "";
            txtCustomerID.SelectionLength = 0;
            txtCustomerID.SelectionStart = 0;
            txtCustomerID.ShortcutsEnabled = true;
            txtCustomerID.Size = new Size(271, 44);
            txtCustomerID.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            txtCustomerID.TabIndex = 109;
            txtCustomerID.TextAlign = HorizontalAlignment.Left;
            txtCustomerID.TextMarginBottom = 0;
            txtCustomerID.TextMarginLeft = 3;
            txtCustomerID.TextMarginTop = 1;
            txtCustomerID.TextPlaceholder = "Enter text";
            txtCustomerID.UseSystemPasswordChar = false;
            txtCustomerID.WordWrap = true;
            // 
            // label2
            // 
            label2.AutoSize = true;
            label2.Font = new Font("Microsoft Sans Serif", 14.25F, FontStyle.Bold);
            label2.Location = new Point(93, 263);
            label2.Name = "label2";
            label2.Size = new Size(124, 24);
            label2.TabIndex = 108;
            label2.Text = "Customer ID";
            // 
            // txtUserID
            // 
            txtUserID.AcceptsReturn = false;
            txtUserID.AcceptsTab = false;
            txtUserID.AnimationSpeed = 200;
            txtUserID.AutoCompleteMode = AutoCompleteMode.None;
            txtUserID.AutoCompleteSource = AutoCompleteSource.None;
            txtUserID.AutoSizeHeight = true;
            txtUserID.BackColor = Color.Transparent;
            txtUserID.BackgroundImage = (Image)resources.GetObject("txtUserID.BackgroundImage");
            txtUserID.BorderColorActive = Color.DarkGoldenrod;
            txtUserID.BorderColorDisabled = Color.FromArgb(204, 204, 204);
            txtUserID.BorderColorHover = Color.DarkGoldenrod;
            txtUserID.BorderColorIdle = Color.Silver;
            txtUserID.BorderRadius = 35;
            txtUserID.BorderThickness = 1;
            txtUserID.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            txtUserID.CharacterCasing = CharacterCasing.Normal;
            txtUserID.DefaultFont = new Font("Microsoft Sans Serif", 9F, FontStyle.Bold);
            txtUserID.DefaultText = "";
            txtUserID.Enabled = false;
            txtUserID.FillColor = Color.White;
            txtUserID.HideSelection = true;
            txtUserID.IconLeft = null;
            txtUserID.IconLeftCursor = Cursors.IBeam;
            txtUserID.IconPadding = 10;
            txtUserID.IconRight = null;
            txtUserID.IconRightCursor = Cursors.IBeam;
            txtUserID.Location = new Point(265, 313);
            txtUserID.MaxLength = 32767;
            txtUserID.MinimumSize = new Size(1, 1);
            txtUserID.Modified = false;
            txtUserID.Multiline = false;
            txtUserID.Name = "txtUserID";
            stateProperties13.BorderColor = Color.DarkGoldenrod;
            stateProperties13.FillColor = Color.Empty;
            stateProperties13.ForeColor = Color.Empty;
            stateProperties13.PlaceholderForeColor = Color.Empty;
            txtUserID.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = Color.FromArgb(204, 204, 204);
            stateProperties14.FillColor = Color.FromArgb(240, 240, 240);
            stateProperties14.ForeColor = Color.FromArgb(109, 109, 109);
            stateProperties14.PlaceholderForeColor = Color.DarkGray;
            txtUserID.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = Color.DarkGoldenrod;
            stateProperties15.FillColor = Color.Empty;
            stateProperties15.ForeColor = Color.Empty;
            stateProperties15.PlaceholderForeColor = Color.Empty;
            txtUserID.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = Color.Silver;
            stateProperties16.FillColor = Color.White;
            stateProperties16.ForeColor = Color.Empty;
            stateProperties16.PlaceholderForeColor = Color.Empty;
            txtUserID.OnIdleState = stateProperties16;
            txtUserID.Padding = new Padding(3);
            txtUserID.PasswordChar = '\0';
            txtUserID.PlaceholderForeColor = Color.Silver;
            txtUserID.PlaceholderText = "Enter text";
            txtUserID.ReadOnly = true;
            txtUserID.ScrollBars = ScrollBars.None;
            txtUserID.SelectedText = "";
            txtUserID.SelectionLength = 0;
            txtUserID.SelectionStart = 0;
            txtUserID.ShortcutsEnabled = true;
            txtUserID.Size = new Size(271, 44);
            txtUserID.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            txtUserID.TabIndex = 111;
            txtUserID.TextAlign = HorizontalAlignment.Left;
            txtUserID.TextMarginBottom = 0;
            txtUserID.TextMarginLeft = 3;
            txtUserID.TextMarginTop = 1;
            txtUserID.TextPlaceholder = "Enter text";
            txtUserID.UseSystemPasswordChar = false;
            txtUserID.WordWrap = true;
            // 
            // label4
            // 
            label4.AutoSize = true;
            label4.Font = new Font("Microsoft Sans Serif", 14.25F, FontStyle.Bold);
            label4.Location = new Point(93, 313);
            label4.Name = "label4";
            label4.Size = new Size(78, 24);
            label4.TabIndex = 110;
            label4.Text = "User ID";
            // 
            // txtOrderTime
            // 
            txtOrderTime.AcceptsReturn = false;
            txtOrderTime.AcceptsTab = false;
            txtOrderTime.AnimationSpeed = 200;
            txtOrderTime.AutoCompleteMode = AutoCompleteMode.None;
            txtOrderTime.AutoCompleteSource = AutoCompleteSource.None;
            txtOrderTime.AutoSizeHeight = true;
            txtOrderTime.BackColor = Color.Transparent;
            txtOrderTime.BackgroundImage = (Image)resources.GetObject("txtOrderTime.BackgroundImage");
            txtOrderTime.BorderColorActive = Color.DarkGoldenrod;
            txtOrderTime.BorderColorDisabled = Color.FromArgb(204, 204, 204);
            txtOrderTime.BorderColorHover = Color.DarkGoldenrod;
            txtOrderTime.BorderColorIdle = Color.Silver;
            txtOrderTime.BorderRadius = 35;
            txtOrderTime.BorderThickness = 1;
            txtOrderTime.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            txtOrderTime.CharacterCasing = CharacterCasing.Normal;
            txtOrderTime.DefaultFont = new Font("Microsoft Sans Serif", 9F, FontStyle.Bold);
            txtOrderTime.DefaultText = "";
            txtOrderTime.Enabled = false;
            txtOrderTime.FillColor = Color.White;
            txtOrderTime.HideSelection = true;
            txtOrderTime.IconLeft = null;
            txtOrderTime.IconLeftCursor = Cursors.IBeam;
            txtOrderTime.IconPadding = 10;
            txtOrderTime.IconRight = null;
            txtOrderTime.IconRightCursor = Cursors.IBeam;
            txtOrderTime.Location = new Point(265, 363);
            txtOrderTime.MaxLength = 32767;
            txtOrderTime.MinimumSize = new Size(1, 1);
            txtOrderTime.Modified = false;
            txtOrderTime.Multiline = false;
            txtOrderTime.Name = "txtOrderTime";
            stateProperties17.BorderColor = Color.DarkGoldenrod;
            stateProperties17.FillColor = Color.Empty;
            stateProperties17.ForeColor = Color.Empty;
            stateProperties17.PlaceholderForeColor = Color.Empty;
            txtOrderTime.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = Color.FromArgb(204, 204, 204);
            stateProperties18.FillColor = Color.FromArgb(240, 240, 240);
            stateProperties18.ForeColor = Color.FromArgb(109, 109, 109);
            stateProperties18.PlaceholderForeColor = Color.DarkGray;
            txtOrderTime.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = Color.DarkGoldenrod;
            stateProperties19.FillColor = Color.Empty;
            stateProperties19.ForeColor = Color.Empty;
            stateProperties19.PlaceholderForeColor = Color.Empty;
            txtOrderTime.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = Color.Silver;
            stateProperties20.FillColor = Color.White;
            stateProperties20.ForeColor = Color.Empty;
            stateProperties20.PlaceholderForeColor = Color.Empty;
            txtOrderTime.OnIdleState = stateProperties20;
            txtOrderTime.Padding = new Padding(3);
            txtOrderTime.PasswordChar = '\0';
            txtOrderTime.PlaceholderForeColor = Color.Silver;
            txtOrderTime.PlaceholderText = "Enter text";
            txtOrderTime.ReadOnly = true;
            txtOrderTime.ScrollBars = ScrollBars.None;
            txtOrderTime.SelectedText = "";
            txtOrderTime.SelectionLength = 0;
            txtOrderTime.SelectionStart = 0;
            txtOrderTime.ShortcutsEnabled = true;
            txtOrderTime.Size = new Size(271, 44);
            txtOrderTime.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            txtOrderTime.TabIndex = 113;
            txtOrderTime.TextAlign = HorizontalAlignment.Left;
            txtOrderTime.TextMarginBottom = 0;
            txtOrderTime.TextMarginLeft = 3;
            txtOrderTime.TextMarginTop = 1;
            txtOrderTime.TextPlaceholder = "Enter text";
            txtOrderTime.UseSystemPasswordChar = false;
            txtOrderTime.WordWrap = true;
            // 
            // label3
            // 
            label3.AutoSize = true;
            label3.Font = new Font("Microsoft Sans Serif", 14.25F, FontStyle.Bold);
            label3.Location = new Point(93, 363);
            label3.Name = "label3";
            label3.Size = new Size(117, 24);
            label3.TabIndex = 112;
            label3.Text = "Order Time";
            // 
            // txtTotalAmount
            // 
            txtTotalAmount.AcceptsReturn = false;
            txtTotalAmount.AcceptsTab = false;
            txtTotalAmount.AnimationSpeed = 200;
            txtTotalAmount.AutoCompleteMode = AutoCompleteMode.None;
            txtTotalAmount.AutoCompleteSource = AutoCompleteSource.None;
            txtTotalAmount.AutoSizeHeight = true;
            txtTotalAmount.BackColor = Color.Transparent;
            txtTotalAmount.BackgroundImage = (Image)resources.GetObject("txtTotalAmount.BackgroundImage");
            txtTotalAmount.BorderColorActive = Color.DarkGoldenrod;
            txtTotalAmount.BorderColorDisabled = Color.FromArgb(204, 204, 204);
            txtTotalAmount.BorderColorHover = Color.DarkGoldenrod;
            txtTotalAmount.BorderColorIdle = Color.Silver;
            txtTotalAmount.BorderRadius = 35;
            txtTotalAmount.BorderThickness = 1;
            txtTotalAmount.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            txtTotalAmount.CharacterCasing = CharacterCasing.Normal;
            txtTotalAmount.DefaultFont = new Font("Microsoft Sans Serif", 9F, FontStyle.Bold);
            txtTotalAmount.DefaultText = "";
            txtTotalAmount.Enabled = false;
            txtTotalAmount.FillColor = Color.White;
            txtTotalAmount.HideSelection = true;
            txtTotalAmount.IconLeft = null;
            txtTotalAmount.IconLeftCursor = Cursors.IBeam;
            txtTotalAmount.IconPadding = 10;
            txtTotalAmount.IconRight = null;
            txtTotalAmount.IconRightCursor = Cursors.IBeam;
            txtTotalAmount.Location = new Point(265, 413);
            txtTotalAmount.MaxLength = 32767;
            txtTotalAmount.MinimumSize = new Size(1, 1);
            txtTotalAmount.Modified = false;
            txtTotalAmount.Multiline = false;
            txtTotalAmount.Name = "txtTotalAmount";
            stateProperties21.BorderColor = Color.DarkGoldenrod;
            stateProperties21.FillColor = Color.Empty;
            stateProperties21.ForeColor = Color.Empty;
            stateProperties21.PlaceholderForeColor = Color.Empty;
            txtTotalAmount.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = Color.FromArgb(204, 204, 204);
            stateProperties22.FillColor = Color.FromArgb(240, 240, 240);
            stateProperties22.ForeColor = Color.FromArgb(109, 109, 109);
            stateProperties22.PlaceholderForeColor = Color.DarkGray;
            txtTotalAmount.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = Color.DarkGoldenrod;
            stateProperties23.FillColor = Color.Empty;
            stateProperties23.ForeColor = Color.Empty;
            stateProperties23.PlaceholderForeColor = Color.Empty;
            txtTotalAmount.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = Color.Silver;
            stateProperties24.FillColor = Color.White;
            stateProperties24.ForeColor = Color.Empty;
            stateProperties24.PlaceholderForeColor = Color.Empty;
            txtTotalAmount.OnIdleState = stateProperties24;
            txtTotalAmount.Padding = new Padding(3);
            txtTotalAmount.PasswordChar = '\0';
            txtTotalAmount.PlaceholderForeColor = Color.Silver;
            txtTotalAmount.PlaceholderText = "Enter text";
            txtTotalAmount.ReadOnly = true;
            txtTotalAmount.ScrollBars = ScrollBars.None;
            txtTotalAmount.SelectedText = "";
            txtTotalAmount.SelectionLength = 0;
            txtTotalAmount.SelectionStart = 0;
            txtTotalAmount.ShortcutsEnabled = true;
            txtTotalAmount.Size = new Size(271, 44);
            txtTotalAmount.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            txtTotalAmount.TabIndex = 115;
            txtTotalAmount.TextAlign = HorizontalAlignment.Left;
            txtTotalAmount.TextMarginBottom = 0;
            txtTotalAmount.TextMarginLeft = 3;
            txtTotalAmount.TextMarginTop = 1;
            txtTotalAmount.TextPlaceholder = "Enter text";
            txtTotalAmount.UseSystemPasswordChar = false;
            txtTotalAmount.WordWrap = true;
            // 
            // label8
            // 
            label8.AutoSize = true;
            label8.Font = new Font("Microsoft Sans Serif", 14.25F, FontStyle.Bold);
            label8.Location = new Point(93, 413);
            label8.Name = "label8";
            label8.Size = new Size(134, 24);
            label8.TabIndex = 114;
            label8.Text = "Total Amount";
            // 
            // txtDiscount
            // 
            txtDiscount.AcceptsReturn = false;
            txtDiscount.AcceptsTab = false;
            txtDiscount.AnimationSpeed = 200;
            txtDiscount.AutoCompleteMode = AutoCompleteMode.None;
            txtDiscount.AutoCompleteSource = AutoCompleteSource.None;
            txtDiscount.AutoSizeHeight = true;
            txtDiscount.BackColor = Color.Transparent;
            txtDiscount.BackgroundImage = (Image)resources.GetObject("txtDiscount.BackgroundImage");
            txtDiscount.BorderColorActive = Color.DarkGoldenrod;
            txtDiscount.BorderColorDisabled = Color.FromArgb(204, 204, 204);
            txtDiscount.BorderColorHover = Color.DarkGoldenrod;
            txtDiscount.BorderColorIdle = Color.Silver;
            txtDiscount.BorderRadius = 35;
            txtDiscount.BorderThickness = 1;
            txtDiscount.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            txtDiscount.CharacterCasing = CharacterCasing.Normal;
            txtDiscount.DefaultFont = new Font("Microsoft Sans Serif", 9F, FontStyle.Bold);
            txtDiscount.DefaultText = "";
            txtDiscount.Enabled = false;
            txtDiscount.FillColor = Color.White;
            txtDiscount.HideSelection = true;
            txtDiscount.IconLeft = null;
            txtDiscount.IconLeftCursor = Cursors.IBeam;
            txtDiscount.IconPadding = 10;
            txtDiscount.IconRight = null;
            txtDiscount.IconRightCursor = Cursors.IBeam;
            txtDiscount.Location = new Point(265, 463);
            txtDiscount.MaxLength = 32767;
            txtDiscount.MinimumSize = new Size(1, 1);
            txtDiscount.Modified = false;
            txtDiscount.Multiline = false;
            txtDiscount.Name = "txtDiscount";
            stateProperties25.BorderColor = Color.DarkGoldenrod;
            stateProperties25.FillColor = Color.Empty;
            stateProperties25.ForeColor = Color.Empty;
            stateProperties25.PlaceholderForeColor = Color.Empty;
            txtDiscount.OnActiveState = stateProperties25;
            stateProperties26.BorderColor = Color.FromArgb(204, 204, 204);
            stateProperties26.FillColor = Color.FromArgb(240, 240, 240);
            stateProperties26.ForeColor = Color.FromArgb(109, 109, 109);
            stateProperties26.PlaceholderForeColor = Color.DarkGray;
            txtDiscount.OnDisabledState = stateProperties26;
            stateProperties27.BorderColor = Color.DarkGoldenrod;
            stateProperties27.FillColor = Color.Empty;
            stateProperties27.ForeColor = Color.Empty;
            stateProperties27.PlaceholderForeColor = Color.Empty;
            txtDiscount.OnHoverState = stateProperties27;
            stateProperties28.BorderColor = Color.Silver;
            stateProperties28.FillColor = Color.White;
            stateProperties28.ForeColor = Color.Empty;
            stateProperties28.PlaceholderForeColor = Color.Empty;
            txtDiscount.OnIdleState = stateProperties28;
            txtDiscount.Padding = new Padding(3);
            txtDiscount.PasswordChar = '\0';
            txtDiscount.PlaceholderForeColor = Color.Silver;
            txtDiscount.PlaceholderText = "Enter text";
            txtDiscount.ReadOnly = true;
            txtDiscount.ScrollBars = ScrollBars.None;
            txtDiscount.SelectedText = "";
            txtDiscount.SelectionLength = 0;
            txtDiscount.SelectionStart = 0;
            txtDiscount.ShortcutsEnabled = true;
            txtDiscount.Size = new Size(271, 44);
            txtDiscount.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            txtDiscount.TabIndex = 117;
            txtDiscount.TextAlign = HorizontalAlignment.Left;
            txtDiscount.TextMarginBottom = 0;
            txtDiscount.TextMarginLeft = 3;
            txtDiscount.TextMarginTop = 1;
            txtDiscount.TextPlaceholder = "Enter text";
            txtDiscount.UseSystemPasswordChar = false;
            txtDiscount.WordWrap = true;
            // 
            // label5
            // 
            label5.AutoSize = true;
            label5.Font = new Font("Microsoft Sans Serif", 14.25F, FontStyle.Bold);
            label5.Location = new Point(93, 463);
            label5.Name = "label5";
            label5.Size = new Size(91, 24);
            label5.TabIndex = 116;
            label5.Text = "Discount";
            // 
            // txtFinalAmount
            // 
            txtFinalAmount.AcceptsReturn = false;
            txtFinalAmount.AcceptsTab = false;
            txtFinalAmount.AnimationSpeed = 200;
            txtFinalAmount.AutoCompleteMode = AutoCompleteMode.None;
            txtFinalAmount.AutoCompleteSource = AutoCompleteSource.None;
            txtFinalAmount.AutoSizeHeight = true;
            txtFinalAmount.BackColor = Color.Transparent;
            txtFinalAmount.BackgroundImage = (Image)resources.GetObject("txtFinalAmount.BackgroundImage");
            txtFinalAmount.BorderColorActive = Color.DarkGoldenrod;
            txtFinalAmount.BorderColorDisabled = Color.FromArgb(204, 204, 204);
            txtFinalAmount.BorderColorHover = Color.DarkGoldenrod;
            txtFinalAmount.BorderColorIdle = Color.Silver;
            txtFinalAmount.BorderRadius = 35;
            txtFinalAmount.BorderThickness = 1;
            txtFinalAmount.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            txtFinalAmount.CharacterCasing = CharacterCasing.Normal;
            txtFinalAmount.DefaultFont = new Font("Microsoft Sans Serif", 9F, FontStyle.Bold);
            txtFinalAmount.DefaultText = "";
            txtFinalAmount.Enabled = false;
            txtFinalAmount.FillColor = Color.White;
            txtFinalAmount.HideSelection = true;
            txtFinalAmount.IconLeft = null;
            txtFinalAmount.IconLeftCursor = Cursors.IBeam;
            txtFinalAmount.IconPadding = 10;
            txtFinalAmount.IconRight = null;
            txtFinalAmount.IconRightCursor = Cursors.IBeam;
            txtFinalAmount.Location = new Point(276, 513);
            txtFinalAmount.MaxLength = 32767;
            txtFinalAmount.MinimumSize = new Size(1, 1);
            txtFinalAmount.Modified = false;
            txtFinalAmount.Multiline = false;
            txtFinalAmount.Name = "txtFinalAmount";
            stateProperties29.BorderColor = Color.DarkGoldenrod;
            stateProperties29.FillColor = Color.Empty;
            stateProperties29.ForeColor = Color.Empty;
            stateProperties29.PlaceholderForeColor = Color.Empty;
            txtFinalAmount.OnActiveState = stateProperties29;
            stateProperties30.BorderColor = Color.FromArgb(204, 204, 204);
            stateProperties30.FillColor = Color.FromArgb(240, 240, 240);
            stateProperties30.ForeColor = Color.FromArgb(109, 109, 109);
            stateProperties30.PlaceholderForeColor = Color.DarkGray;
            txtFinalAmount.OnDisabledState = stateProperties30;
            stateProperties31.BorderColor = Color.DarkGoldenrod;
            stateProperties31.FillColor = Color.Empty;
            stateProperties31.ForeColor = Color.Empty;
            stateProperties31.PlaceholderForeColor = Color.Empty;
            txtFinalAmount.OnHoverState = stateProperties31;
            stateProperties32.BorderColor = Color.Silver;
            stateProperties32.FillColor = Color.White;
            stateProperties32.ForeColor = Color.Empty;
            stateProperties32.PlaceholderForeColor = Color.Empty;
            txtFinalAmount.OnIdleState = stateProperties32;
            txtFinalAmount.Padding = new Padding(3);
            txtFinalAmount.PasswordChar = '\0';
            txtFinalAmount.PlaceholderForeColor = Color.Silver;
            txtFinalAmount.PlaceholderText = "Enter text";
            txtFinalAmount.ReadOnly = true;
            txtFinalAmount.ScrollBars = ScrollBars.None;
            txtFinalAmount.SelectedText = "";
            txtFinalAmount.SelectionLength = 0;
            txtFinalAmount.SelectionStart = 0;
            txtFinalAmount.ShortcutsEnabled = true;
            txtFinalAmount.Size = new Size(271, 44);
            txtFinalAmount.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            txtFinalAmount.TabIndex = 119;
            txtFinalAmount.TextAlign = HorizontalAlignment.Left;
            txtFinalAmount.TextMarginBottom = 0;
            txtFinalAmount.TextMarginLeft = 3;
            txtFinalAmount.TextMarginTop = 1;
            txtFinalAmount.TextPlaceholder = "Enter text";
            txtFinalAmount.UseSystemPasswordChar = false;
            txtFinalAmount.WordWrap = true;
            // 
            // label9
            // 
            label9.AutoSize = true;
            label9.Font = new Font("Microsoft Sans Serif", 14.25F, FontStyle.Bold);
            label9.Location = new Point(93, 513);
            label9.Name = "label9";
            label9.Size = new Size(134, 24);
            label9.TabIndex = 118;
            label9.Text = "Final Amount";
            // 
            // txtNotes
            // 
            txtNotes.AcceptsReturn = false;
            txtNotes.AcceptsTab = false;
            txtNotes.AnimationSpeed = 200;
            txtNotes.AutoCompleteMode = AutoCompleteMode.None;
            txtNotes.AutoCompleteSource = AutoCompleteSource.None;
            txtNotes.AutoSizeHeight = true;
            txtNotes.BackColor = Color.Transparent;
            txtNotes.BackgroundImage = (Image)resources.GetObject("txtNotes.BackgroundImage");
            txtNotes.BorderColorActive = Color.DarkGoldenrod;
            txtNotes.BorderColorDisabled = Color.FromArgb(204, 204, 204);
            txtNotes.BorderColorHover = Color.DarkGoldenrod;
            txtNotes.BorderColorIdle = Color.Silver;
            txtNotes.BorderRadius = 35;
            txtNotes.BorderThickness = 1;
            txtNotes.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            txtNotes.CharacterCasing = CharacterCasing.Normal;
            txtNotes.DefaultFont = new Font("Microsoft Sans Serif", 9F, FontStyle.Bold);
            txtNotes.DefaultText = "";
            txtNotes.Enabled = false;
            txtNotes.FillColor = Color.White;
            txtNotes.HideSelection = true;
            txtNotes.IconLeft = null;
            txtNotes.IconLeftCursor = Cursors.IBeam;
            txtNotes.IconPadding = 10;
            txtNotes.IconRight = null;
            txtNotes.IconRightCursor = Cursors.IBeam;
            txtNotes.Location = new Point(265, 563);
            txtNotes.MaxLength = 32767;
            txtNotes.MinimumSize = new Size(1, 1);
            txtNotes.Modified = false;
            txtNotes.Multiline = false;
            txtNotes.Name = "txtNotes";
            stateProperties33.BorderColor = Color.DarkGoldenrod;
            stateProperties33.FillColor = Color.Empty;
            stateProperties33.ForeColor = Color.Empty;
            stateProperties33.PlaceholderForeColor = Color.Empty;
            txtNotes.OnActiveState = stateProperties33;
            stateProperties34.BorderColor = Color.FromArgb(204, 204, 204);
            stateProperties34.FillColor = Color.FromArgb(240, 240, 240);
            stateProperties34.ForeColor = Color.FromArgb(109, 109, 109);
            stateProperties34.PlaceholderForeColor = Color.DarkGray;
            txtNotes.OnDisabledState = stateProperties34;
            stateProperties35.BorderColor = Color.DarkGoldenrod;
            stateProperties35.FillColor = Color.Empty;
            stateProperties35.ForeColor = Color.Empty;
            stateProperties35.PlaceholderForeColor = Color.Empty;
            txtNotes.OnHoverState = stateProperties35;
            stateProperties36.BorderColor = Color.Silver;
            stateProperties36.FillColor = Color.White;
            stateProperties36.ForeColor = Color.Empty;
            stateProperties36.PlaceholderForeColor = Color.Empty;
            txtNotes.OnIdleState = stateProperties36;
            txtNotes.Padding = new Padding(3);
            txtNotes.PasswordChar = '\0';
            txtNotes.PlaceholderForeColor = Color.Silver;
            txtNotes.PlaceholderText = "Enter text";
            txtNotes.ReadOnly = true;
            txtNotes.ScrollBars = ScrollBars.None;
            txtNotes.SelectedText = "";
            txtNotes.SelectionLength = 0;
            txtNotes.SelectionStart = 0;
            txtNotes.ShortcutsEnabled = true;
            txtNotes.Size = new Size(271, 44);
            txtNotes.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            txtNotes.TabIndex = 121;
            txtNotes.TextAlign = HorizontalAlignment.Left;
            txtNotes.TextMarginBottom = 0;
            txtNotes.TextMarginLeft = 3;
            txtNotes.TextMarginTop = 1;
            txtNotes.TextPlaceholder = "Enter text";
            txtNotes.UseSystemPasswordChar = false;
            txtNotes.WordWrap = true;
            // 
            // label6
            // 
            label6.AutoSize = true;
            label6.Font = new Font("Microsoft Sans Serif", 14.25F, FontStyle.Bold);
            label6.Location = new Point(93, 563);
            label6.Name = "label6";
            label6.Size = new Size(64, 24);
            label6.TabIndex = 120;
            label6.Text = "Notes";
            // 
            // txtStatus
            // 
            txtStatus.AcceptsReturn = false;
            txtStatus.AcceptsTab = false;
            txtStatus.AnimationSpeed = 200;
            txtStatus.AutoCompleteMode = AutoCompleteMode.None;
            txtStatus.AutoCompleteSource = AutoCompleteSource.None;
            txtStatus.AutoSizeHeight = true;
            txtStatus.BackColor = Color.Transparent;
            txtStatus.BackgroundImage = (Image)resources.GetObject("txtStatus.BackgroundImage");
            txtStatus.BorderColorActive = Color.DarkGoldenrod;
            txtStatus.BorderColorDisabled = Color.FromArgb(204, 204, 204);
            txtStatus.BorderColorHover = Color.DarkGoldenrod;
            txtStatus.BorderColorIdle = Color.Silver;
            txtStatus.BorderRadius = 35;
            txtStatus.BorderThickness = 1;
            txtStatus.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            txtStatus.CharacterCasing = CharacterCasing.Normal;
            txtStatus.DefaultFont = new Font("Microsoft Sans Serif", 9F, FontStyle.Bold);
            txtStatus.DefaultText = "";
            txtStatus.Enabled = false;
            txtStatus.FillColor = Color.White;
            txtStatus.HideSelection = true;
            txtStatus.IconLeft = null;
            txtStatus.IconLeftCursor = Cursors.IBeam;
            txtStatus.IconPadding = 10;
            txtStatus.IconRight = null;
            txtStatus.IconRightCursor = Cursors.IBeam;
            txtStatus.Location = new Point(265, 613);
            txtStatus.MaxLength = 32767;
            txtStatus.MinimumSize = new Size(1, 1);
            txtStatus.Modified = false;
            txtStatus.Multiline = false;
            txtStatus.Name = "txtStatus";
            stateProperties37.BorderColor = Color.DarkGoldenrod;
            stateProperties37.FillColor = Color.Empty;
            stateProperties37.ForeColor = Color.Empty;
            stateProperties37.PlaceholderForeColor = Color.Empty;
            txtStatus.OnActiveState = stateProperties37;
            stateProperties38.BorderColor = Color.FromArgb(204, 204, 204);
            stateProperties38.FillColor = Color.FromArgb(240, 240, 240);
            stateProperties38.ForeColor = Color.FromArgb(109, 109, 109);
            stateProperties38.PlaceholderForeColor = Color.DarkGray;
            txtStatus.OnDisabledState = stateProperties38;
            stateProperties39.BorderColor = Color.DarkGoldenrod;
            stateProperties39.FillColor = Color.Empty;
            stateProperties39.ForeColor = Color.Empty;
            stateProperties39.PlaceholderForeColor = Color.Empty;
            txtStatus.OnHoverState = stateProperties39;
            stateProperties40.BorderColor = Color.Silver;
            stateProperties40.FillColor = Color.White;
            stateProperties40.ForeColor = Color.Empty;
            stateProperties40.PlaceholderForeColor = Color.Empty;
            txtStatus.OnIdleState = stateProperties40;
            txtStatus.Padding = new Padding(3);
            txtStatus.PasswordChar = '\0';
            txtStatus.PlaceholderForeColor = Color.Silver;
            txtStatus.PlaceholderText = "Enter text";
            txtStatus.ReadOnly = true;
            txtStatus.ScrollBars = ScrollBars.None;
            txtStatus.SelectedText = "";
            txtStatus.SelectionLength = 0;
            txtStatus.SelectionStart = 0;
            txtStatus.ShortcutsEnabled = true;
            txtStatus.Size = new Size(271, 44);
            txtStatus.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            txtStatus.TabIndex = 123;
            txtStatus.TextAlign = HorizontalAlignment.Left;
            txtStatus.TextMarginBottom = 0;
            txtStatus.TextMarginLeft = 3;
            txtStatus.TextMarginTop = 1;
            txtStatus.TextPlaceholder = "Enter text";
            txtStatus.UseSystemPasswordChar = false;
            txtStatus.WordWrap = true;
            // 
            // label7
            // 
            label7.AutoSize = true;
            label7.Font = new Font("Microsoft Sans Serif", 14.25F, FontStyle.Bold);
            label7.Location = new Point(93, 613);
            label7.Name = "label7";
            label7.Size = new Size(66, 24);
            label7.TabIndex = 122;
            label7.Text = "Status";
            // 
            // Order
            // 
            AutoScaleDimensions = new SizeF(7F, 15F);
            AutoScaleMode = AutoScaleMode.Font;
            ClientSize = new Size(1370, 728);
            Controls.Add(txtStatus);
            Controls.Add(label7);
            Controls.Add(txtNotes);
            Controls.Add(label6);
            Controls.Add(txtFinalAmount);
            Controls.Add(label9);
            Controls.Add(txtDiscount);
            Controls.Add(label5);
            Controls.Add(txtTotalAmount);
            Controls.Add(label8);
            Controls.Add(txtOrderTime);
            Controls.Add(label3);
            Controls.Add(txtUserID);
            Controls.Add(label4);
            Controls.Add(txtCustomerID);
            Controls.Add(label2);
            Controls.Add(txtID);
            Controls.Add(label1);
            Controls.Add(btnClear);
            Controls.Add(btnDelete);
            Controls.Add(btnUpdate);
            Controls.Add(btnInsert);
            Controls.Add(btnNew);
            Controls.Add(txtSearch);
            Controls.Add(dgvPayment);
            Controls.Add(bunifuPanel2);
            FormBorderStyle = FormBorderStyle.None;
            Name = "Order";
            StartPosition = FormStartPosition.CenterScreen;
            Text = "Order Management";
            bunifuPanel2.ResumeLayout(false);
            bunifuPanel2.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)dgvPayment).EndInit();
            ResumeLayout(false);
            PerformLayout();
        }

        #endregion
        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel2;
        private Label label11;
        private Bunifu.UI.WinForms.BunifuButton.BunifuIconButton btnExitProgram;
        private Bunifu.UI.WinForms.BunifuDataGridView dgvPayment;
        private Bunifu.UI.WinForms.BunifuTextBox txtSearch;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnClear;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnDelete;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnUpdate;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnInsert;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnNew;
        private Bunifu.UI.WinForms.BunifuTextBox txtID;
        private Label label1;
        private Bunifu.UI.WinForms.BunifuTextBox txtCustomerID;
        private Label label2;
        private Bunifu.UI.WinForms.BunifuTextBox txtUserID;
        private Label label4;
        private Bunifu.UI.WinForms.BunifuTextBox txtOrderTime;
        private Label label3;
        private Bunifu.UI.WinForms.BunifuTextBox txtTotalAmount;
        private Label label8;
        private Bunifu.UI.WinForms.BunifuTextBox txtDiscount;
        private Label label5;
        private Bunifu.UI.WinForms.BunifuTextBox txtFinalAmount;
        private Label label9;
        private Bunifu.UI.WinForms.BunifuTextBox txtNotes;
        private Label label6;
        private Bunifu.UI.WinForms.BunifuTextBox txtStatus;
        private Label label7;
    }
}